### ISSUE TITLE
git commit 6ea45040 killed my '\' key

### ISSUE THREAD

**Issue by gnuwimp** [fltk/fltk#1093] opened 2024-10-25 19:12 UTC
6ea450407b3d9e5d6f2731ee6f89b1000e1f3c22 
Windows: process the +-containing key used with Ctrl in cross-platform way
That is altgr + \ which is the +? key on my keyboard.
Sorry about my Swedish keyboard making issues.

**Comment by ManoloFLTK** [comment] 2024-10-26 13:12
Please, explain more clearly what is your problem.
Do you type altgr+\ on your keyboard and don't obtain what you expect?
Or do you use a shortcut that doesn't work?

**Comment by gnuwimp** [comment] 2024-10-26 14:34
Yes I type altgr + \ and I get a + instead.

**Comment by Albrecht-S** [comment] 2024-10-26 15:24
@ManoloFLTK I tested this and I believe that setting `Fl::event_text()` in the "Kludge to process the +-containing key" is the culprit. If I comment out these statements:
```C++
             if (plus_shift_pos) {
               Fl::e_text = ( (Fl::e_state & FL_SHIFT) ? (char*)"+" : plus_other_char_utf8 );
             } else {
               Fl::e_text = ( (Fl::e_state & FL_SHIFT) ? plus_other_char_utf8 : (char*)"+" );
             }
             Fl::e_length = strlen(Fl::e_text);
```
then I get the expected behavior WRT _**this issue** with the Swedish keyboard_.

Unfortunately this has a negative side effect on scaling shortcut processing: if I press `AltGr + '+'` instead of `Ctrl + '+'` the scaling shortcut triggers unexpectedly (it should only be triggered when Ctrl is pressed). However, Windows seems to be very inconsistently setting key event status bits when `AltGr` is pressed. As an example, this output is from `test/handle_keys` when pressing `AltGr` `m` `n` in this order:
```
[ 49] FL_KEYDOWN      0x006d  'm'           C . . . . .  'µ'   U+00b5    c2 b5
[ 50] FL_KEYDOWN      0x006e  'n'           C A . . . .  ''
```

As you can see only `Ctrl` is set when there is a "translation" for an alternate key (`µ`) but `Ctrl` + `Alt` is set when there is NO "translation" (and `Fl::event_text()` is empty).

I hope this helps but I don't have a final solution. Maybe my "patch" (to remove modification of `Fl::event_text()`) is the "better" solution than what we have now, but I'm not sure what to do. Maybe you have a better idea?

**Comment by gnuwimp** [comment] 2024-10-26 16:04
@Albrecht-S With these lines on `altgr + '\'` does not work in the editor. And also keyboard scaling does not work in the editor.

With these line off `altgr + '\'` does work. And keyboard scaling with `ctrl + '+'`.

In both cases (code on and off) I can scale other apps (when not in a editor or input widget) with `altgr + '\'`.

             if (plus_shift_pos) {
               Fl::e_text = ( (Fl::e_state & FL_SHIFT) ? (char*)"+" : plus_other_char_utf8 );
             } else {
               Fl::e_text = ( (Fl::e_state & FL_SHIFT) ? plus_other_char_utf8 : (char*)"+" );
             }
             Fl::e_length = strlen(Fl::e_text);

**Comment by ManoloFLTK** [comment] 2024-10-26 16:46
@gnuwimp The issue should be fixed with the commit mentioned above. Do you confirm?

**Comment by Albrecht-S** [comment] 2024-10-26 17:00
@ManoloFLTK With commit 94a50ecd6b9a8183ae06990f2afd5cb7984ae66b `Ctrl + '+'` (on Swedish keyboard) inserts `'+'` in the editor which is wrong, and it doesn't scale.

Again, removing the `Fl::event_text()` assignment makes it work as expected.

Disclaimer: other cases not tested!

**Comment by gnuwimp** [comment] 2024-10-26 17:01
Works same for me as for @Albrecht-S.

**Comment by Albrecht-S** [comment] 2024-10-26 17:09
@ManoloFLTK I'm not only guessing that `Fl::event_text()` should not be assigned in this "kludge", I had a bad feeling from the beginning when you added this code but I couldn't tell why - just a feeling. Now it seems (!) my feeling was correct.

Can you give an example why you believe that we need this `Fl::event_text()` assignment? What's wrong if we remove it?

Please keep in mind that we don't need to "fix" the entire keyboard handling, the main thing we need to take care of is not to introduce regressions, i.e. not to break existing code (user interface).

**Comment by ManoloFLTK** [comment] 2024-10-26 19:20
> Can you give an example why you believe that we need this Fl::event_text() assignment? 

So that Windows produce the same Fl::event_text() as other platforms when ctrl+ is hit with/without shift.

> What's wrong if we remove it?

Nothing works anymore.

I see that apps such as hello and handle_keys do zoom-in correctly with the Swedish keyboard and many others and commit 94a50ec. I'll investigate what happens with apps such as editor that consume text input.

**Comment by Albrecht-S** [comment] 2024-10-26 19:26
> > Can you give an example why you believe that we need this Fl::event_text() assignment?
> So that Windows produce the same Fl::event_text() as other platforms when ctrl+ is hit with/without shift.

That is NOT the goal. The goal must be that
1. The scaling shortcuts work (high priority) - if possible
2. Windows produces the same `Fl::event_text()` as it produces on 1.3.x

**Comment by ManoloFLTK** [comment] 2024-10-26 22:18
Commit ae55a42 should fix the issue.

**Comment by ManoloFLTK** [comment] 2024-10-27 05:08
> Can you give an example why you believe that we need this Fl::event_text() assignment?

WIthout the kludge, FLTK under Windows produces a 0-length content for `Fl::event_text()` when Ctrl+ or CtrlShft+ is pressed. This in turn has the zoom-in operation fail because this operation is triggered by `Fl::test_shortcut(FL_COMMAND+'+')` returning 1. Function `Fl::test_shortcut()` itself uses these statements to return 1:
```
  unsigned int firstChar = fl_utf8decode(Fl::event_text(), Fl::event_text()+Fl::event_length(), 0);
  if ( ! (FL_CAPS_LOCK&shift) && key==firstChar) return 1;
```
Thus, an adequate content of `Fl::event_text()` is necessary for the zoom-in to work.

**Comment by gnuwimp** [comment] 2024-10-27 11:24
@ManoloFLTK Commit ae55a42 fixed all issues. Backslash works. Scaling works in input widget and scaling with `altgr + '+'` does not work. I'm closing this issue now.

**Closed** 2024-10-27 11:25 UTC
Labels: fixed, Platform: Windows
