### ISSUE TITLE
Starting a drag  from a subwindow does not work on OpenSuse KDE wayland.

### ISSUE THREAD

**Issue by mroe1** [fltk/fltk#997] opened 2024-06-29 17:38 UTC
**Describe the bug**
Starting a drag operation doesn't work from a sub window.
The cursor changes but the drag doesn't seem to have actually started.
Works from main window.
Seems KDE Wayland only;  all X11 and e.g. on Ubuntu Wayland  its all fine.

The bug may have its home  in KDE Wayland but i also file here. Perhaps there is even something to find in FLTK Wayland implementation. 

**To Reproduce**
Have attached a small test derived from the "how to-drag-and-drop" example.
Upper box in the Sender is on the main window
Lower box is  in a sub window.

**FLTK Version**
 - Version: [e.g. 1.4.0]

**Operating System / Platform:**
 - OS:  Linux
 - OS Version: openSUSE Leap 15.5 / current Tumbleweed 

**Linux/Unix Runtime, if applicable:**
 - KDE Wayland

[test-drag-and-drop.zip](https://github.com/user-attachments/files/16041635/test-drag-and-drop.zip)

**Comment by ManoloFLTK** [comment] 2024-06-30 07:38
OK. I see the problem here under Ubuntu 24.04 with the KDE/Plasma desktop.
No problem, as reported, with the gnome desktop.

**Comment by ManoloFLTK** [comment] 2024-07-01 07:11
I've tried hard to fix that, and am left with the opinion that the problem is not in FLTK but in the KWIN compositor that doesn't support properly drag-and-drop from a subwindow (subsurface in Wayland parlance).

I therefore won't be able to fix this.

**Comment by ManoloFLTK** [comment] 2024-07-02 07:41
@mroe1  I can propose a workaround for this bug that requires to call a special purpose function with one parameter, the FLTK widget in which the Fl::dnd() function is called. That function, 
`void prepare_widget_for_dnd(Fl_Widget *wdgt)` 
is coded in the attached program which also shows how to use it. It's to be called after the parent window containing the subwindow with the Fl::dnd() call is show()'n but before that window begins to be used. That function contains this directive
`#include "../src/drivers/Wayland/Fl_Wayland_Window_Driver.H"`
which requires access to an internal header file of the FLTK source tree. The function does nothing when FLTK doesn't run Wayland, so it can be used across all FLTK platforms.

[test-drag-and-dropV2.cxx.txt](https://github.com/user-attachments/files/16063740/test-drag-and-dropV2.cxx.txt)

Given this workaround, I would suggest this issue can be closed.

**Comment by MatthiasWM** [comment] 2024-08-04 12:42
Would it make sense to add `void prepare_widget_for_dnd(Fl_Widget *wdgt)` and a call to it to `Fl_Window::show()` and `resize()` in the core library?

**Comment by ManoloFLTK** [comment] 2024-08-04 17:25
At this point, I would prefer to stay with this workaround for these reasons:
- it's a bug in KDE/Plasma, not in FLTK. DnD from a subwindow has no problem with Weston nor with Mutter, Gnome's Wayland compositor;
- the workaround acts by marking the area of the widget that starts the DnD operation as not receiving mouse and touch events, which are received by the underlying parent window for which DnD works. That may have unwanted side effects for other things.

**Comment by Albrecht-S** [comment] 2024-08-10 19:02
@ManoloFLTK wrote:
> At this point, I would prefer to stay with this workaround ...

I agree that we shouldn't change our code to work around a supposed bug in KDE that will likely be fixed sooner or later, since all the other tested compositors don't have this issue.

However, we should somehow document that there is a workaround if someone encounters this issue in their program. I imagine to do:
- add a note in README.Wayland.txt with a reference to this issue
- store the code of function `prepare_widget_for_dnd(Fl_Widget *wdgt)` somewhere, for instance in our `misc` folder

When done, close this issue. Are there better suggestions?

**Comment by ManoloFLTK** [comment] 2024-08-11 07:43
> add a note in README.Wayland.txt with a reference to this issue

Done at 48303cd.

> store the code of function prepare_widget_for_dnd(Fl_Widget *wdgt) somewhere, for instance in our misc folder

I prefer to avoid having the same code in 2 locations (issue #997 + misc folder).

**Comment by Albrecht-S** [comment] 2024-08-11 13:57
@ManoloFLTK Thanks, I'm fine with the given solution in commit 48303cd295e55d3fb51d7f4cbe534e1d6db305b3.

IMHO we can close this issue. @MatthiasWM ?

**Closed** 2024-08-12 06:11 UTC
Labels: wontfix, Platform: Wayland
