### ISSUE TITLE
CMake: Shared library + Cairo on macOS -> Missing symbols

### ISSUE THREAD

**Issue by OPNA2608** [fltk/fltk#250] opened 2021-07-12 09:17 UTC
Attempting to build shared libraries with Cairo support on macOS (via CMake, both 1.3.6 and recent master) aborts on target `fltk_cairo_SHARED`:

![Screenshot_macOS_2021-07-12_10:56:47](https://user-images.githubusercontent.com/23431373/125259741-e6b39a00-e2ff-11eb-927e-5795c76c5a71.png)

Hacking `-undefined dynamic_lookup` into our compiler's linker flags at build time (breaks GL linking if present at cmake time) fixes it for me (at least `cairo_test` seems to work). [The Darwin linker seems to wants all library symbols resolved by default, it needs this flag to disable the behaviour and act more like a Linux linker.](https://stackoverflow.com/a/5201180)

**Comment by Albrecht-S** [comment] 2021-07-12 18:11
Thanks for the report, this should be fixed now by commit 787c67afea179735f2fea12f95ad04c80b3717e7. There were some issues with dependencies which prevented clean building on macOS.

Thanks for the hint with `-undefined dynamic_lookup` but this was not necessary here.

Please report whether this fixes the issue for you and feel free to close the issue (if yes). If not, please report details, particularly macOS version, processor type (M1 ?), build setup if anything else but default, additional software libs (homebrew or anything else) etc. ...

**Comment by OPNA2608** [comment] 2021-07-12 22:26
New error while building 787c67afea179735f2fea12f95ad04c80b3717e7 (w/ `-DOPTION_CAIROEXT=ON`):

![Screenshot_macOS_2021-07-12_23:35:43](https://user-images.githubusercontent.com/23431373/125359032-02538a80-e36a-11eb-884c-11d1ac600486.png)

This is macOS 10.13, x86 processor. I'm building via Nixpkgs: https://github.com/OPNA2608/nixpkgs/blob/refactor-fltk/pkgs/development/libraries/fltk/common.nix

**Comment by Albrecht-S** [comment] 2021-07-13 00:28
> New error while building 787c67a (w/ -DOPTION_CAIROEXT=ON):

Does this mean that the previous error is fixed?

And do you say that `-DOPTION_CAIROEXT=ON` worked before commit 787c67a? (I don't think so, but I'm asking anyway.)

Honestly, I didn't test with `-DOPTION_CAIROEXT=ON` because I wanted to fix the given issue first (I assume you used `-DOPTION_CAIRO=ON`) and `OPTION_CAIROEXT` is presumably rarely used, but I was aware that something like this could happen. In this case the FLTK lib itself (not only `libfltk_cairo`) depends on `libcairo`. I'll check this...

> I'm building via Nixpkgs...

Thanks for the info, but I can't test with this setup.

**Comment by OPNA2608** [comment] 2021-07-13 11:13
Sorry. Yes, the first error message is resolved now but it fails abit later with the same CMake settings. No, `CAIROEXT` didn't work before 787c67afea179735f2fea12f95ad04c80b3717e7 either but I was using `CAIROEXT` from the beginning.

**Comment by Albrecht-S** [comment] 2021-07-13 20:07
Thanks for clarification, I'll try to fix this as well, as soon as possible, likely tomorrow (but don't hold your breath).

**Comment by Albrecht-S** [comment] 2021-07-23 12:57
Sorry, this is more complicated due to circular dependencies. Static linking works though.

I also evaluated linking with `-undefined dynamic_lookup` (manually: works as you wrote), but I'd like to keep this as a last resort. This would be platform dependent (hard to do for the Makefile build system).

I'm trying to find a better implementation.

**Comment by Albrecht-S** [comment] 2021-07-26 19:07
@OPNA2608: I created a preliminary branch `issue-250_cairoext` (beta status) [in my fork](https://github.com/Albrecht-S/fltk/) which you can [view and download/pull](https://github.com/Albrecht-S/fltk/tree/issue-250_cairoext).

Main difference: the extra Cairo library `libfltk_cairo` is gone, Cairo is integrated in `libfltk` **_if and only if_** one of the Cairo options (`OPTION_CAIRO` or `OPTION_CAIROEXT`) is enabled.

I need a break and I don't know yet whether this is the proper solution. This needs more tests on different platforms.

Excerpt from the relevant commit log:
```
Static linking is not affected by this change, but users building
with hand-made Makefiles will have to remove libfltk_cairo.

The shared FLTK library libfltk.{so|dylib|dll|..} depends on libcairo
if and only if FLTK is built with one of the Cairo options. This has
always been the case for OPTION_CAIROEXT but is now also true if only
OPTION_CAIRO is selected, i.e. FLTK programs linked with a Cairo
enabled shared FLTK library will also be linked with libcairo.
```

All feedback and test results would be welcome. TIA.

**Comment by OPNA2608** [comment] 2021-12-26 23:34
Sorry for the late feedback. Confirming that compilation with `DOPTION_CAIROEXT=ON` succeeds on the `issue-250_cairoext` branch. I ran some test binaries (including cairo_test) and everything seemed to work.

**Comment by ManoloFLTK** [comment] 2023-01-27 06:05
@Albrecht-S I propose, if you agree, to take care of this issue with the attached patch as a fix. This Fl_Plugin-based approach is already used to allow code in libfltk to use symbols from libfltk_gl when Fl_Gl_Window's are around without requiring libfltk to be dependent on libfltk_gl.

The modified code is also accessible in branch issue250 of [my FLTK fork ](https://github.com/ManoloFLTK/fltk).

[issue250.patch.txt](https://github.com/fltk/fltk/files/10515972/issue250.patch.txt)

**Comment by Albrecht-S** [comment] 2023-01-27 19:23
@ManoloFLTK I'm not sure if your patch is the correct or even a good solution. Did you look at my solution in this comment https://github.com/fltk/fltk/issues/250#issuecomment-886954470?

First of all, this issue is not only a macOS issue. It manifests on `macOS` because the default linker command doesn't allow a **_shared_** library with undefined symbols whereas this is possible on `Linux` [1]. The undefined symbols are caused by circular dependencies of `libfltk` and `libfltk_cairo` which is definitely bad (circular dependencies in libs are **always** bad).

Hence my proposed solution was (and still is) to eliminate `libfltk_cairo` completely, for two reasons:
- it contains only one object file
- it causes circular dependencies if option `HAVE_CAIRO_EXT` is on (not only on macOS)

BTW, on Windows we can currently build only one FLTK shared library that contains "everything" which doesn't have this problem. However, I still need to test a shared FLTK library on Windows with Cairo.

The only problem I see with the removal of the extra (shared and static) `libfltk_cairo` is that it would make the **_shared_** `libfltk.so` (or `libfltk.dylib`) - but not the static libfltk - depend on Cairo if FLTK was built with one of the cairo options. Currently it depends on Cairo only if option `CAIRO_EXT` is on.

The change to remove libfltk_cairo would also simplify (user) app build procedures and the documentation.

Comments welcome.

[1] Even if it's allowed, it doesn't mean that this is a good solution.

**Comment by ManoloFLTK** [comment] 2023-01-28 07:04
@Albrecht-S : Yes, I agree it's better to also remove circular dependencies in other platforms. Indeed, when building under macOS with -DOPTION_APPLE_X11=ON, the link error also appears in the unpatched source code. My new proposal is thus to apply the same fix to all 4 platforms. That's in branch issue250 of https://github.com/ManoloFLTK/fltk

I've tested it under macOS, macOS+ XQuartz, Linux. cairo_test builds with FLTK_HAVE_CAIROEXT=1 and runs OK using the autolink mechanism. I could not test it for Windows because I don't have cairo there.

If you consider better to compile Fl_Cairo.cxx inside libfltk, I agree it's also a good solution.

**Comment by Albrecht-S** [comment] 2023-01-28 17:13
@ManoloFLTK I need some to think about it and test, I'll let you know when done.

**Comment by ManoloFLTK** [comment] 2023-01-29 08:34
I the Fl_Plugin-based approach is retained, I would also like to remove the pure virtual character of class Fl_Device_Plugin, adding a do-nothing implementation to its member functions. That would prevent, for example, to have to implement member function Fl_Cairo_Device_Plugin::print() which makes no sense.

**Comment by Albrecht-S** [comment] 2023-01-29 15:19
@ManoloFLTK I see your comment and assume you closed this issue unintentionally. Reopening...

**Comment by ManoloFLTK** [comment] 2023-01-29 16:16
Yes, sorry, this closing was fully unintended.

**Comment by Albrecht-S** [comment] 2023-03-09 17:07
Commit 5175192755e57d1d7016253d48f34f9d0c2c0832 fixes the issue on macOS, Linux, and Windows. On Windows shared libs can't be built yet with Visual Studio but my tests with MinGW/MSYS2 worked.

For your info:

- The `Cairo` support library `libfltk_cairo` has been removed and should no longer be linked to your application.
- FLTK still builds an "empty" (dummy) `libfltk_cairo` as a placeholder for backwards compatibility with old (1.3.x) FLTK application build systems.
- Users should clean up their build systems to not link with `libfltk_cairo` when targeting FLTK 1.4.0 or later.
- The dummy library `libfltk_cairo` will be removed in a future release after 1.4.0.

Still to do:
- documentation (e.g. `README.Cairo.txt`) and other CMake improvements
- clean up fltk-config (this will be dealt with separately)

I consider this issue fixed.

**Comment by Albrecht-S** [comment] 2023-03-09 17:11
@OPNA2608 Sorry for the long delay, this was really hard stuff and needed a "management decision" to remove the separate lib that caused cyclic dependencies.

Can you please confirm that this fixes your linking problems and close this issue if confirmed? TIA.

**Comment by Albrecht-S** [comment] 2023-03-14 19:04
Closing this issue after 5 days w/o confirmation.

**Closed by Albrecht-S** 2023-03-14 19:04 UTC
Labels: bug, fixed, CMake, Platform: macOS, Prio 3 - Moderate
