### ISSUE TITLE
FLTK 1.4: X11 Clipping bugs

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#963] opened 2024-04-28 18:24 UTC
**Describe the bug**
In FLTK 1.4 + X11 only, rects and lines drawn by fl_draw.H are clipped incorrectly when dealing with positions/sizes greater than 16-bit.

For example, a rect will be clipped incorrectly if its width is greater than 32,767 and its x position is negative.

And a vertical yx line will have its x position clipped incorrectly if its x position is greater than 65,535.

There may be more scenarios, but these are the two that come up in my experience.

**To Reproduce**
Here is a heavily modified version of test/scroll.cxx to demonstrate the issue:

```cpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Slider.H>
#include <FL/fl_draw.H>

class Drawing : public Fl_Widget {
  void draw() override;
public:
  Drawing(int X,int Y,int W,int H,const char* L) : Fl_Widget(X,Y,W,H,L) {}
};

void Drawing::draw() {
  for (int i = 0; i < h() / 20; i++) {
    fl_rectf(x(), y() + i * 20, w(), 20, i % 2 ? FL_LIGHT1 : FL_DARK2);
  }
  fl_color(FL_BLACK);
  for (int i = 0; i < w() / 50; i++) {
    fl_yxline(x() + i * 50, y(), y()+h());
  }
}

void set_window_label(Fl_Window *w, int v) {
  char buffer[64] = {};
  sprintf(buffer, "Scroll Width: %d", v);
  w->copy_label(buffer);
}

void slider_cb(Fl_Slider *w) {
  Drawing *drawing = (Drawing *)w->user_data();
  drawing->size(w->value(), drawing->h());
  drawing->redraw();
  set_window_label(drawing->window(), (int)w->value());
}

int main(int argc, char** argv) {
  Fl_Double_Window window(5*75,320);
  window.resizable(nullptr);
  set_window_label(&window, 50*75);

  Fl_Scroll scroll(0,0,5*75,300);
  Drawing drawing(0,0,50*75,300,0);
  scroll.type(Fl_Scroll::HORIZONTAL);
  scroll.end();

  Fl_Slider slider(0, 300, 5*75, 20);
  slider.type(FL_HORIZONTAL);
  slider.value(50*75);
  slider.bounds(50*75, 5000*75);
  slider.user_data(&drawing);
  slider.callback((Fl_Callback *)slider_cb);

  window.end();
  window.show(argc,argv);
  return Fl::run();
}
```

Summary of the program:
The window contains an Fl_Scroll with a single Drawing widget inside it.
The Drawing widget uses fl_rectf() to draw horizontal stripes of alternating color that span the width of the widget, and uses fl_yxline() to draw _uniformly spaced_ black vertical lines along the width of the widget.
There is an Fl_Slider below the Fl_Scroll which controls the width of the Drawing widget. The current width of the Drawing widget is also displayed in the window's title bar for convenience.

1. Replace test/scroll.cxx with the above code
2. Compile test/scroll.cxx like normal
3. Run test/scroll
4. Use the slider to increase the width of the drawing area higher and higher
5. See that the yx lines start drawing at unexpected positions after exceeding 65,535, and continues to get worse as it gets even wider
6. Scroll the Fl_Scroll to the right to any non-zero position (to set the x position of the Drawing widget to a negative value)
7. See that the rects clip incorrectly after exceeding a width of 32,767

**Expected behavior**
Even with a width greater than 32,767 or 65,535 and with a negative x position, rects and lines should be clipped sensibly and be drawn as normal (drawn the same as with a width less than 32,767 or with a non-negative x position).

**Video**

https://github.com/fltk/fltk/assets/5231310/c3d5db3e-937d-4dd4-954d-3fb83524ea3f

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 8664fde

**FLTK Configure / Build Options**
 - ./configure

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**
This bug is not present in FLTK 1.3 on X11, and the bug is also not present in FLTK 1.4 on Windows or Mac. (I have not tested Wayland.)

The bug appears to be new to FLTK 1.4 and only occurs on X11.

Here is the same program from above working correctly on X11 using FLTK 1.3:

https://github.com/fltk/fltk/assets/5231310/4e6d3894-f6b2-475b-827a-4a1f9faba230

And here is a _very crude_ patch for Fl_Xlib_Graphics_Driver_rect.cxx which restores part of the implementation from FLTK 1.3 simply to demonstrate that this code is the source of the incorrect clipping:

```diff
diff --git a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx
index ea24eba34..cae364ee5 100644
--- a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx
+++ b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx
@@ -60,7 +60,7 @@
 int Fl_Xlib_Graphics_Driver::clip_line(int &x1, int &y1, int &x2, int &y2) {
 
   // define variables
-  float p1 = float(-(x2 - x1));
+  /* float p1 = float(-(x2 - x1));
   float p2 = float(-p1);
   float p3 = float(-(y2 - y1));
   float p4 = float(-p3);
@@ -108,7 +108,31 @@ int Fl_Xlib_Graphics_Driver::clip_line(int &x1, int &y1, int &x2, int &y2) {
   y2 = int(y1 + p4 * posmin);
 
   x1 = int(x1 + p2 * negmax);
-  y1 = int(y1 + p4 * negmax);
+  y1 = int(y1 + p4 * negmax); */
+
+  int lw = 1;
+  int kmin = -lw;
+  int kmax = 32767 - lw;
+
+  if (x1 < kmin)
+    x1 = kmin;
+  else if (x1 > kmax)
+    x1 = kmax;
+
+  if (y1 < kmin)
+    y1 = kmin;
+  else if (y1 > kmax)
+    y1 = kmax;
+
+  if (x2 < kmin)
+    x2 = kmin;
+  else if (x2 > kmax)
+    x2 = kmax;
+
+  if (y2 < kmin)
+    y2 = kmin;
+  else if (y2 > kmax)
+    y2 = kmax;
 
   return 0; // not clipped
 
@@ -173,14 +197,27 @@ int Fl_Xlib_Graphics_Driver::clip_line(int &x1, int &y1, int &x2, int &y2) {
 
 int Fl_Xlib_Graphics_Driver::clip_rect(int &x, int &y, int &w, int &h) {
 
-  if (w <= 0 || h <= 0) return 1;                       // (a)
+  /* if (w <= 0 || h <= 0) return 1;                       // (a)
   if (x+w < clip_min() || y+h < clip_min()) return 1;   // (b)
   if (x > clip_max() || y > clip_max()) return 1;       // (c)
 
   if (x < clip_min()) { w -= (clip_min()-x); x = clip_min(); }
   if (y < clip_min()) { h -= (clip_min()-y); y = clip_min(); }
   if (x+w > clip_max()) w = clip_max() - x;
-  if (y+h > clip_max()) h = clip_max() - y;
+  if (y+h > clip_max()) h = clip_max() - y; */
+
+  int lw = 1;
+  int kmin = -lw;
+  int kmax = 32767 - lw;
+
+  if (w <= 0 || h <= 0) return 1;		// (a)
+  if (x+w < kmin || y+h < kmin) return 1;	// (b)
+  if (x > kmax || y > kmax) return 1;		// (c)
+
+  if (x < kmin) { w -= (kmin-x); x = kmin; }
+  if (y < kmin) { h -= (kmin-y); y = kmin; }
+  if (x+w > kmax) w = kmax - x;
+  if (y+h > kmax) h = kmax - y;
 
   return 0;
 }
```

With this patch, the above demo program functions exactly as expected (again, only for demonstration purposes).

**Comment by Albrecht-S** [comment] 2024-04-28 21:16
Here's a first comment, only as a quick reaction. **_This was not intended as a final statement - but it became longer and more detailed than I had anticipated, and thus it may well be final. A solution is included._**

First of all, this behavior is a property of X11 because this is the only platform which is supported by FLTK and allows only 16 bits of coordinate space. Although FLTK allows larger widgets and scroll areas it is not possible to use coordinates larget than 16 bits in pure X11.

I remember to have "fixed" (more precise: improved) some of the clipping issues at some time in the past by clipping coordinates internally **before** they are applied to the X11 protocol but this is something that can't be done completely.

The only valid solution is IMHO to **_restrict coordinates in user space_** (not trying to clip inside FLTK). There may be some points where this can still improved but I'm pretty sure that we won't try to "fix" this in FLTK. It's clear that Windows and macOS support full 32-bit coordinate space which is why these issues don't exist on these platforms.

I'm not sure about Wayland though. Does Wayland support full 32-bit coordinate space? Since all drawing is done by FLTK in internal buffers using Cairo this would be something that needs to be supported by Cairo (I assume this works OOTB, and see my test results below).

Another important test would be to build FLTK on X11 with Cairo drawing, either the hybrid (Wayland + X11) build or the X11-only build with Cairo drawing:
- `./configure --enable-usecairo ...` or
- `cmake -D FLTK_GRAPHICS_CAIRO:BOOL=ON ...`

@dannye I tried your test program with the setup mentioned above (Cairo drawing) and it seems to work as intended on Linux/X11 and Linux/Wayland. As a double check I tested it with
```
./configure --disable-wayland --disable-use-cairo ; make
```
and this showed the effects as described above and seen in the video.

**_Summary after my quick tests:_** The solution to all clipping issues on X11 which uses only 16-bit coordinates (this is not a FLTK fault) is to use Cairo drawing which is available since FLTK 1.4.0 or to use Wayland which also uses Cairo drawing internally. The hybrid FLTK lib works well as both X11 and Wayland clients.

**_For the record:_** If anything regarding coordinates > 16 bit **_appears_** to work "better" in FLTK 1.3 then this is only by good luck.

**Comment by Albrecht-S** [comment] 2024-04-28 21:19
Note: I set label "fixed" because the given solution above is to use Cairo drawing which doesn't suffer from X11 constraints - unless I'm missing something.

**Comment by dannye** [comment] 2024-04-29 02:20
Thanks for the information. Cairo is something that I've just never learned what it is or what it does because it hasn't been necessary. But I compiled with Cairo enabled for the first time, and it does solve the original issue, but there are a lot of issues with the font rendering.. maybe it's fixable by tweaking some options, I don't know, but I've opted to do my own clipping without enabling Cairo.

For the horizontal stripes (fl_rectf), I'm now using the `x()` and `w()` of the parent Fl_Scroll, and not the `x()` and `w()` of the child widget getting drawn.

And for all the uniformly spaced vertical lines (fl_yxline), I'm using a small wrapper which only calls `fl_yxline()` if the x position of the line falls within the visible span of the Fl_Scroll:

```cpp
const auto yxline = [](int x, int y, int y1, int px, int pw) {
	if (x >= px && x < px + pw) fl_yxline(x, y, y1);
};
```

This seems to work okay and I haven't noticed any problems with it yet..

Feel free to close this issue and thanks again for the advice.

**Comment by Albrecht-S** [comment] 2024-04-29 10:50
OK, I'm going to close this issue.

FWIW: as you noticed you can build FLTK to make it use Cairo for (graphics) drawing w/o knowing anything about Cairo, just as many FLTK users don't know anything about X11 or macOS graphics drawing features. For proper text rendering you need to enable Pango which is probably done anyway as soon as you enable Cairo. To be sure, look at the summary output by configure. My line about "Graphics" looks like this:
```
Graphics: Wayland or X11 with cairo + Xfixes + Xinerama + Xcursor + Xrender + Pango
```

And of course, that said, we recommend to use CMake and build the "hybrid" (X11 + Wayland) FLTK library for general use. configure support will be supported in 1.4.x but dropped in 1.5.0 anyway.

**Closed by Albrecht-S** 2024-04-29 10:50 UTC
Labels: fixed, Platform: X11

**Comment by dannye** [comment] 2024-04-30 03:04
> For proper text rendering you need to enable Pango which is probably done anyway as soon as you enable Cairo. To be sure, look at the summary output by configure.

Yeah, it looks like Pango is enabled. My "Graphics" line looks like:
> Graphics: X11 + Xft + Xfixes + Xinerama + Xcursor + Xrender + Cairo + Pango

For an example of the issues I'm seeing, text usually looks like this:

![image](https://github.com/fltk/fltk/assets/5231310/82754ab5-ea13-4f87-8009-99f3a4be7d2d)

But with Cairo/Pango, it looks like:

![image](https://github.com/fltk/fltk/assets/5231310/2a52ebb4-7beb-4b57-97ad-03873eec9a4a)

(I know screenshots with no code is not very helpful, and this is all off-topic from the original issue. Just providing screenshots to give a sense of what I meant in my previous comment.)

Besides the font being different/smaller, there is a visual artifact in every instance of lowercase "d". Capital "F" always appears bold. Spaces are kinda huge.

The text is not very well centered in buttons/boxes (text is always too high):

![image](https://github.com/fltk/fltk/assets/5231310/8116f14d-a76b-4e4d-ba58-230b7c7fbf3b)
![image](https://github.com/fltk/fltk/assets/5231310/773812d2-8da4-45e6-8b7e-f63789635dd8)

![image](https://github.com/fltk/fltk/assets/5231310/ef51ca74-2505-4bdb-8806-20e19cc73c58)
![image](https://github.com/fltk/fltk/assets/5231310/2eba503b-b145-4ca8-86b1-6e67383c6560)

![image](https://github.com/fltk/fltk/assets/5231310/83d912cc-01a5-4583-9e27-108939831eda)
![image](https://github.com/fltk/fltk/assets/5231310/9d1c2bc7-eed2-4a22-858b-e365a163b05e)

And I just noticed that Cairo smears the bottom and right edges of xpm pixel art:

![image](https://github.com/fltk/fltk/assets/5231310/be772536-47c5-49aa-9e28-39b7966ffd17)
![image](https://github.com/fltk/fltk/assets/5231310/47a5cb6e-d331-41b0-b690-a788dc1c6f57)

**Comment by ManoloFLTK** [comment] 2024-04-30 15:28
The problems reported here about the quality of text drawn with Pango + Cairo are unexpected. Pango + Cairo is used by all gnome apps. Some fonts may be missing on the used system. It might be useful to add the gnome-core package. Here is what I get here with Cairo+Pango (left) and X11+Xft (right) :
<img width="685" alt="image" src="https://github.com/fltk/fltk/assets/41016272/78b2bd77-f710-4b55-9315-536a3b08820a">

**Comment by ManoloFLTK** [comment] 2024-04-30 15:36
and what I get with pixmaps:
<img width="774" alt="image" src="https://github.com/fltk/fltk/assets/41016272/5bbf7965-f60b-4005-976a-20837ebeb59f">

**Comment by dannye** [comment] 2024-05-03 17:31
Hm, I installed gnome-core and tinkered for a while, but never saw any changes. Thanks for the tips though.
