### ISSUE TITLE
Bug in callbacks generated by fluid on macOS using system menu bar inside C++ Classes

### ISSUE THREAD

**Issue by robbwheel** [fltk/fltk#977] opened 2024-05-19 06:14 UTC
Bug in callbacks generated by fluid on macOS using system menu bar inside C++ Classes

I apologize if I already posted in fltk.general, this seems the more appropriate place

I found a possible bug in the resulting menu callbacks generated by Fluid on macOS using the System Menu Bar Fl_Sys_Menu_Bar and _only_ when inside a C++ Class. 
The problem it is present ONLY on MacOS
The problem is not present if compiled on Linux or MS Windows where all works fine
The problems is not present even on Mac if the generation is made outside a C++ Class (as example inside the main as in the small example projects)

It seems the problem is in the static callback _before calling the inline callback_ , on the code: 'o->parent()->user_data()' only if calling from a C++ Class using a Fluid generated menu
It always fails with an EXEC_BAD_ACCESS
I created a simple project with Fluid to show the problem

In my example code, it  always fails at:

((FluidPPMacMenu*)(o->parent()->user_data()))->cb_item_i(o,v);

Failing to resolve 'o->parent()->user_data()' and causing a crash
With an EXEC_BAD_ACCESS

So the problem seems being retrieving the user data from the menu item parent only when using a menu item on macOS and using the System Menu Bar and inside a C++ Class

I have this problem in more then one project
All works perfectly under Windows compiling with Visual Studio or in Linux or also on macOS if using the menubar outside a C++ class

Maybe I'm doing something wrong, ..not sure

FLTK rel:
FLTK 1.4.x-20240510
FLTK 1.4.x-20240517

Platform: macOS 14.5
Xcode 15.4
With all macOS SDK from 10.13 to 14.5

The following code is for "FluidPPMacMenu.h":

---------------------------------------------

#ifndef FluidPPMacMenu_h
#define FluidPPMacMenu_h
#include <FL/Fl.H>
#include <FL/Fl_Sys_Menu_Bar.H>
#include <FL/Fl_Menu.H>
#include <FL/Fl_Double_Window.H>

class FluidPPMacMenu {
public:
  void testOne();
  FluidPPMacMenu();
  static Fl_Menu_Item menu_MenuBar[];
private:
  inline void cb_item_i(Fl_Menu_*, void*);
  static void cb_item(Fl_Menu_*, void*);
};
#endif

---------------------------------------------

and for FluidPPMacMenu.cxx:
---------------------------------------------

// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "FluidPPMacMenu.h"
typedef struct FLMESSAGE{
    int msgType;
    void *data;
    
} FLMESSAGE;

void FluidPPMacMenu::cb_item_i(Fl_Menu_*, void*) {
  testOne();
}
void FluidPPMacMenu::cb_item(Fl_Menu_* o, void* v) {
  ((FluidPPMacMenu*)(o->parent()->user_data()))->cb_item_i(o,v);
}

Fl_Menu_Item FluidPPMacMenu::menu_MenuBar[] = {
 {"Menu One", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"item One", 0,  (Fl_Callback*)FluidPPMacMenu::cb_item, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

void FluidPPMacMenu::testOne() {
  printf("Hello World\n");
}

FluidPPMacMenu::FluidPPMacMenu() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(480, 320);
    w = o; (void)w;
    o->user_data((void*)(this));
    { Fl_Sys_Menu_Bar* o = new Fl_Sys_Menu_Bar(0, 0, 480, 18, "MenuBar");
      o->box(FL_UP_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_SELECTION_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(Fl_Align(FL_ALIGN_CENTER));
      o->when(FL_WHEN_RELEASE_ALWAYS);
      o->menu(menu_MenuBar);
    } // Fl_Sys_Menu_Bar* o
    o->end();
  } // Fl_Double_Window* o
  w->show();
}

int main(int argc, char **argv) {
  new FluidPPMacMenu();

  return Fl::run();
}

---------------------------------------------

Included also the Fluid file to generate both files
[FluidPPMacMenu.fl.txt](https://github.com/fltk/fltk/files/15368225/FluidPPMacMenu.fl.txt)

**Comment by robbwheel** [comment] 2024-05-19 09:03
It seems the right fix to be adopted
I replaced it manually (also in  a bit complex project) with the code suggested by Manolo and it seems working fine on macOS.
So probably a solution to be adopted in Fluid autogeneration and also when using the function by hand.

**Comment by Albrecht-S** [comment] 2024-05-19 09:11
@robbwheel Thank you for the report and for the confirmation that @ManoloFLTK's proposed change works. I assigned this issue to @MatthiasWM, our FLTK specialist, for review and a possible solution in fluid.

@MatthiasWM I hope you don't mind. To other devs, e.g. @ManoloFLTK: feel free to assign yourself if you feel that you can fix it. Thanks.

**Comment by robbwheel** [comment] 2024-05-19 09:53
Not sure if on Windows 11 the code: '(o->parent()?o->parent():Fl::first_window())' works well
I had some problems in a. recompiled app
I will inspect it better in the next hours.

**Comment by ManoloFLTK** [comment] 2024-05-19 09:56
That's an issue that requires for sure our fluid specialist.

**Comment by robbwheel** [comment] 2024-05-19 12:34
Ok for me works fine an all platforms. Tested on  macOS, Linux, Windows11

**Comment by Albrecht-S** [comment] 2024-05-19 13:07
@ManoloFLTK wrote:
> The crash occurs when the menu item's callback computes o->parent()->user_data() where *o is the Fl_Sys_Menu_Bar object.

@MatthiasWM IMHO neither that nor the replacement `(o->parent()?o->parent():Fl::first_window())` are **technically correct**.

The Bad Idea (TM) is IMHO that the pointer to the (sys_)menubar object is stored in a window's `user_data()` location. This is definitely abusing a field that is intended to be used by user code and that can easily be overwritten by setting a window callback with a `user_data` field, like `window->callback(close_cb, (void *)777);`. The value given here will later be used as user_data() and as a pointer to a Fl_Sys_Menubar or Fl_Menubar object.

Although this doesn't crash on platforms other than macOS it's definitely illegal C++ code. Therefore I removed the "Platform: macOS" label now.

I'll post an example fluid file in a follow-up comment.

**Comment by Albrecht-S** [comment] 2024-05-19 14:58
OK, here it is: [sys_menu_bar.zip](https://github.com/fltk/fltk/files/15369762/sys_menu_bar.zip) includes `sys_menu_bar.fl` and `sys_menu_bar_debug.cxx` . The fluid file is a modified version of @robbwheel's example.

To compile and build, use `fluid -c sys_menu_bar.fl` and build the program, e.g. with `fltk-config --compile sys_menu_bar.cxx`. This will crash on macOS and "work" by accident e.g. on Linux (not tested on Windows).

The modified `sys_menu_bar_debug.cxx` includes Manolo's patch suggestion and calls `test_cb(o, v);` to output some debug statements. Commented diff to the original `sys_menu_bar.cxx` as created by `fluid`:
```
$ diff -u sys_menu_bar.cxx sys_menu_bar_debug.cxx
--- sys_menu_bar.cxx	2024-05-19 16:26:04.246803856 +0200
+++ sys_menu_bar_debug.cxx	2024-05-19 16:30:49.545718378 +0200
@@ -30,7 +30,14 @@
   testOne();
 }
 void FluidPPMacMenu::cb_item(Fl_Menu_* o, void* v) {
-  ((FluidPPMacMenu*)(o->parent()->user_data()))->cb_item_i(o,v); // ** patched, see below
+  test_cb(o, v);                                // ** added debug output
+  if (o->parent()) {                            // ** begin of patch suggested by Manolo (modified)
+    Fl_Group *p = o->parent();
+    ((FluidPPMacMenu*)(p->user_data()))->cb_item_i(o,v);
+  } else {
+    Fl_Window *win = Fl::first_window();
+    ((FluidPPMacMenu*)(win->user_data()))->cb_item_i(o,v);
+  }
 }
 
 Fl_Menu_Item FluidPPMacMenu::menu_MenuBar[] = {
```
Running this program on Linux, using the menu, and then closing the window, outputs:
```
$ ./sys_menu_bar_debug 
main_window = 0x560737d5f7d0, user_data = 0x560737d5f7b0   << before setting the callback
main_window = 0x560737d5f7d0, user_data = (nil)            << after setting the callback
--- parent = 0x560737d5f7d0, user_data() = (nil)
will call ((FluidPPMacMenu*)((nil)))->cb_item_i(0x560737d48bf0, (nil));   <<< this is illegal but "works"
Hello World
close_cb: win = 0x560737d5f7d0, user_data = (nil), val = 0
```

Since we set the callback's `user_data()` to zero in the modified test program, the code above uses it as a pointer which is cast to `(FluidPPMacMenu*)`, even **_with the applied patch_**.

That's bad and independent of the platform. The original code would crash because it accesses the `user_data()` location of a `null` pointer (`parent()`) on macOS, the modified code is still illegal because it casts an arbitrary value contained in `user_data()` to `(FluidPPMacMenu*)`. That user_data() value was overwritten by a standard user program. q.e.d.

IMHO the real bug is that the menu pointer is stored in the `user_data` field of the window in the first place. I don't have a suggestion how to fix this but I hope that @MatthiasWM will find a good solution. TIA.

**Comment by Albrecht-S** [comment] 2024-05-19 15:00
I should have mentioned: the output of the modified demo `sys_menu_bar_debug.cxx` is slightly different on macOS but illegal as on other platforms.

**Comment by robbwheel** [comment] 2024-05-19 16:37
I'm the less expert here on FLTK but I would suggest a pragmatical approach:
1) A temporary fix as @ManoloFLTK  suggested, in that way it would be possible to have working apps on macOS, otherwise it is impossible now to use Fluid for macOS compilation using C++ classes for managing the menu (strange that I was the only one having this issue ... or maybe others just give up at the problem)
2) A final fix using a clean way to store the menuPointer somewhere when a better way is found

**Comment by Albrecht-S** [comment] 2024-05-20 01:44
@robbwheel wrote:
> I would suggest a pragmatical approach: ...

Yes, we can do that, but please understand that @MatthiasWM may need some time to take a look at the issue before we decide what to do. If he can't find a better/correct solution (quickly), then we can apply Manolo's quick fix, although it would only work around symptoms and not fix the root cause.

**Comment by robbwheel** [comment] 2024-05-20 07:12
Till a Fluid specialist has the time to solve the problem in a good clean way I tried this change inside Fluid code 
and for now it is working well for me from the first tests I made
It has to be tested in an extended mode because Fluid is a complex app and implications of this change can be various
Consider it is just a first fast attempt from someone that never worked with Fluid source code.
So ... just a first fast proposal

// Original code starts at line 293 in fltk-1.4.x-20240510
// in fluid-lib code 
// File: Fl_Menu_Type.cxx

if (k) {
      f.write_c("void %s::%s(Fl_Menu_* o, %s v) {\n", k, cn, ut);
      f.write_c("%s((%s*)(o", f.indent(1), k);
      Fl_Type* t = parent; while (t->is_a(ID_Menu_Item)) t = t->parent;
      Fl_Type *q = 0;
      // Go up one more level for Fl_Input_Choice, as these are groups themselves
      if (t && t->is_a(ID_Input_Choice))
        f.write_c("->parent()");
      for (t = t->parent; t && t->is_widget() && !is_class(); q = t, t = t->parent)
        f.write_c("->parent()");
      if (!q || !q->is_a(ID_Widget_Class))
        f.write_c("->user_data()");
      f.write_c("))->%s_i(o,v);\n}\n", cn);
    }
    
 
 
 
 
//to be substituted with: 
    
 //@robbwheel Fluid hack for code change proposed by @manoloFLTK
      //Start of robbwheel  Fluid hack
      if (k) {
        f.write_c("void %s::%s(Fl_Menu_* o, %s v) {\n", k, cn, ut);
        f.write_c("%s((%s*)((o", f.indent(1), k);
        Fl_Type* t = parent; while (t->is_a(ID_Menu_Item)) t = t->parent;
        Fl_Type *q = 0;
        // Go up one more level for Fl_Input_Choice, as these are groups themselves
        int pCount=0;
        if (t && t->is_a(ID_Input_Choice))
          {f.write_c("->parent()");pCount++;}
        for (t = t->parent; t && t->is_widget() && !is_class(); q = t, t = t->parent)
          {f.write_c("->parent()");pCount++;}
        f.write_c("?o");
        int pt=0;
        for (pt=0;pt<pCount;pt++)
            {f.write_c("->parent()");}
      f.write_c(":Fl::first_window())");
          
        if (!q || !q->is_a(ID_Widget_Class))
          f.write_c("->user_data()");
        f.write_c("))->%s_i(o,v);\n}\n", cn);
      }
       //End of robbwheel  Fluid hack

**Comment by Albrecht-S** [comment] 2024-05-20 10:45
Thanks, @robbwheel

FWIW: I "translated" the code above to a diff/patch with correct formatting. I changed a tiny bit, but other than that the resulting code would be as posted above: [fluid_issue-977.diff.txt](https://github.com/fltk/fltk/files/15376026/fluid_issue-977.diff.txt)

Test: it works as expected in my example fluid file posted above, i.e. it generates the expected code. Not tested "in action" on macOS though.

Generated code:
```C++
void FluidPPMacMenu::cb_item(Fl_Menu_* o, void* v) {
  ((FluidPPMacMenu*)((o->parent()?o->parent():Fl::first_window())->user_data()))->cb_item_i(o,v);
}
```

Leaving the decision - or a better patch - to @MatthiasWM.

**Comment by MatthiasWM** [comment] 2024-05-26 16:01
Sorry for showing up so late ;-) . I will try to find the time to go in depth tonight or tomorrow. Otherwise there is no other chance until early June.

Generally, using the first window is not a good idea. Maybe creating a widget that holds the reference to the menu, but is not used anywhere els, is the best way. Diving into it... .

**Comment by MatthiasWM** [comment] 2024-05-26 18:10
As for issue 1: Fl_Sys_Menubar must always be seen as application-global. It should never be created as a child of anything. If it's not within a class, FLUID will not create faulty code. I can add code that will warn if the class name is "Fl_Sys_Menubar It's not entirely safe, but it will warn in most cases.

As for error 2. Basically FLUID is abusing the user_data entry in the first window of the class. This can go wrong in multiple ways, not only for the system menu bar. FLUID uses this `parent()->parent()->parent()` dance for other widgets as well. In effect, FLUID needs a second "user_data" field here to not only store the original user data, but also the pointer to the owning class (btw: this would not happen if a Widget Class was used here). One solution that is completely transparent would be to add a second user_data field to `Fl_Window`. Would that be ok?

**Comment by ManoloFLTK** [comment] 2024-05-26 20:50
> As for issue 1: Fl_Sys_Menubar must always be seen as application-global. It should never be created as a child of anything. If it's not within a class, FLUID will not create faulty code. I can add code that will warn if the class name is "Fl_Sys_Menubar It's not entirely safe, but it will warn in most cases.

A problem would arise for cross-platform apps. On non-macOS platforms, an Fl_Sys_Menu_Bar must be the child of an Fl_Window to appear in the GUI.
I'm not sure of the exact meaning of "If it's not within a class". Is it different from being a child of a group widget?

**Comment by ManoloFLTK** [comment] 2024-05-26 20:52
> Basically FLUID is abusing the user_data entry in the first window of the class. 

Has this been always the case with fluid? Or is this new in 1.4 ?

**Comment by ManoloFLTK** [comment] 2024-05-26 20:59
> One solution that is completely transparent would be to add a second user_data field to Fl_Window. Would that be ok?

If a 2nd user_data field is added to Fl_Window and FLUID uses it, then client apps won't be free to use that field for their own needs. Thus that 2nd field should be hidden from public use by FLTK clients. It would possibly be better located as a member of class Fl_Window_Driver.

**Comment by Albrecht-S** [comment] 2024-05-27 12:01
I may be completely wrong, but what I thought was that the menu (widget) itself or even each menu item would have to hold all the information that's needed (for whatever it needs). I didn't follow the entire discussion but using the parent()... (iteration) seems to be wrong. If we needed a window to store some information (which I wouldn't like anyway) then using window() or top_window() might be a better way to find what's needed.

OTOH if (as Matthias mentioned) the Fl_Sys_Menubar was a "global" instance, which window's new userdata(2) field would point to the menu widget? Something doesn't seem right here...

**Comment by MatthiasWM** [comment] 2024-05-27 13:00
Fl_Sys_Menubar, if not created as a child of a window of a class, never needs to access a parent. FLUID only does the parent() dance when an automatic callback of a widget inside a window inside a class is generated, because it needs the pointer to the class in addition to the user_data field. It does that so that callbacks inside a class can be non-static members of that class. I know, it *is* confusing, and the generated code even more so.

But the code is what it is, and existing apps may rely on this feature. The easiest thing is to simply write in the docs that a: Fl_Sys_Menubar must not have a parent, and b: that the user_data field of the topmost window in a Class node is reserved by FLUID. Perfect back compatibility.

On top of that, I can generate warning dialogs or discourage an and b in other ways. This will help for users who don't read the docs (like me), but will probably create new warnings in existing apps.

Maybe that's the best way. I really don't want to adapt FLTK to FLUID. If anything, it should be the other way around. C++11 will eventually eliminate the need for these tricks.

**Comment by Albrecht-S** [comment] 2024-05-27 13:23
> I really don't want to adapt FLTK to FLUID. If anything, it should be the other way around.

Absolutely true.

> C++11 will eventually eliminate the need for these tricks.

Yeah, FLTK 1.5 is calling... ;-)

**Comment by robbwheel** [comment] 2024-05-28 06:53
I'm not sure I understood how it would work in a cross platform environment developed in C++.
If I create a Fl_Sys_menubar not as a child of a window of a class, do I need to not manage the windows using c++ classes?
That would be a nightmare for the one that invested on FLTK creating a C++ object layer on it to manage apps documents and other mundane things

It doesn't seems a clean solution and still we are using and abusing the 'user_data' solution
So the problem it's not solved from an 'ideal' point of view in any case

I know i't a 'dirty' solution but at least the patch I made on Fluid to solve the problem in the way ManoloFLTK suggested,  works perfectly. I'm testing it continuously in these days

It doesn't adapt FLTK to Fluid but it adapts Fluid to FLTK

I tested it in different situations and Fluid generates working code for all the platform and using menubar inside windows inside C++ classes.


Works well and I think the patch add the number of  o->parent()->parent()->parent()?o->parent()->parent()->parent():Fl::first_window()
correctly as required 

If it is ok to have o->parent() and for now there is not any other good solution (as I guessed :) even if I'm not so FLTK expert)
Why not o->parent()?o->parent():Fl::first_window() as manoloFLTK suggested?

Maybe we could add a switch inside Fluid to have the custom generation ONLY if we want to use C++ classes ?

I think it's better then saying to people 'Do not create the menubar as a child of a window inside  a C++ class'

I use C++ classes to manage windows with menus and the patch works well generating for both macOs and win and linux

I think before finding a clean and elegant solution it would be ok because :
1) It doesn't change things so much
2) It works in any situation, C, C++, with classes or not, macOS, Linux, Windows also using a C++ class managing a window with a menubar inside and works perfectly using the global menubar on macOS 
3) It is back compatible with all made so far with Fluid (to be verified but I think it is)
4) It doesn't make things worst then they already are
5) It is an acceptable solution waiting for a more rationale solution that requires more deep work probably in FLTK 1.5 and maybe transitioning to use C++ a bit more then now

**Comment by MatthiasWM** [comment] 2024-07-26 21:22
> I'm not sure I understood how it would work in a cross platform environment developed in C++. If I create a Fl_Sys_menubar not as a child of a window of a class, do I need to not manage the windows using c++ classes? That would be a nightmare for the one that invested on FLTK creating a C++ object layer on it to manage apps documents and other mundane things

Sorry again for more delay. @ManoloFLTK , in line 40 of Fl_Sys_Menu_bar.cxx, https://github.com/fltk/fltk/blob/b740c48ee8505f93662065384d84b449d5e33438/src/Fl_Sys_Menu_Bar.cxx#L40 , the Sys_menu_Bar is removed from the parent widget. Do you happen to know why this is done? Removing this line would fix all issues, unless there is a specifig reason to do this!?

The comment states: _Remove macOS menubar from its parent Fl_Group so it's activated by system menu shortcuts_. What does that mean? Can this be acheived in a different way?

Would that be an ok change?

Of course the sys_menu_bar would be deleted when the parent window is deleted, but I think that's to be expected.

> If it is ok to have o->parent() and for now there is not any other good solution (as I guessed :) even if I'm not so FLTK expert) Why not o->parent()?o->parent():Fl::first_window() as manoloFLTK suggested?

If a callback is generated inside a class, FLUID allows the user to call a regular method of that class (regular as opposed to `static`). To do that, FLUID must have the function pointer, the user_data, plus the address of the enclosing class. But we have only tow fields in a callback. FLUID solves this by storing a pointer to the class in the topmost Fl_Window user_data field of that class.

Now if Fl::first_window() happens to be the window of the class, you are fine. But if another window is the top window, your code will cast the user_data of _that_ window instead, and that could be anything including NULL.

My alternative (if we can't remove line 40) would be to store the class pointer in `Fl_Sys_Menu_Bar::user_data_`.

Positive:
 - this is not used in FLUID if the user stays with menu item callbacks
 - everything else should continue the way it did since we do this only with `Fl_Sys_Menu_Bar`

Negative:
 - it will be overridden and cause a crash if the user manually changes the `Fl_Sys_Menu_Bar::user_data_` field (but the same is true if the user overrides the top window user_data field)
 - this may fail if the user derives a new class from `Fl_Sys_Menu_Bar` and we missread the **Class:** field

I am leaning toward the second solution because it does not change FLTK, only FLUID.

**Comment by ManoloFLTK** [comment] 2024-07-27 14:23
The meaning of this comment
```
// Remove macOS menubar from its parent Fl_Group so it's activated
// by system menu shortcuts 
```
is that if a menubar is the child of (ultimately) an Fl_Window, shortcut events that trigger menu items are processed by FLTK's normal event processing which finds the targetted menu item and calls its callback function. In contrast, if the menubar is not the child of any window, this processing doesn't find the menu item; FLTK then sends the shortcut event to the handlers installed by `Fl::add_handler();` under macOS `int process_sys_menu_shortcuts(int event)` is installed this way; that handler calls
`    [[NSApp mainMenu] performKeyEquivalent:[NSApp currentEvent]];`
which sends the event for processing by macOS system menu handling; ultimately, the menu item's callback runs, and the menubar at the screen top flashes as expected from a menu shortcut under macOS. FLTK event processing wouldn't flash the menubar.

But the main reason why the system menubar should not be the child of any Fl_Window under macOS appears if one considers an app with 2 or more mapped toplevel windows. The menubar should equally cater each of these windows, so it should not be the child of one and unrelated to others.

More generally, and that was pointed out by Albrecht above, FLUID's use of the Fl_Window's `user_data` member is not correct in FLTK: that member should be left for the application to be able to use (or ignore) freely. Thus, FLUID should be changed so it doesn't _steal_ these member data from application users. Would your new stuff in `fl_callback_macros.H` be of good use here?

**Comment by ManoloFLTK** [comment] 2024-07-27 15:48
I see that the new macro FL_METHOD_CALLBACK_x() allows to declare a callback for a non-static class method with custom parameters. Wouldn't that be the way to stop FLUID from "using the user_data field of the topmost window of a class to store a reference to that class, which is needed to call non-static members of that class" ?

**Comment by MatthiasWM** [comment] 2024-07-27 16:20
> if a menubar is the child of (ultimately) an Fl_Window, shortcut events that trigger menu items are processed by FLTK's normal event processing which finds the targetted menu item and calls its callback function. In contrast, if the menubar is not the child of any window, this processing doesn't find the menu item

Understood. Thanks.

> But the main reason why the system menubar should not be the child of any Fl_Window under macOS appears if one considers an app with 2 or more mapped toplevel windows. The menubar should equally cater each of these windows, so it should not be the child of one and unrelated to others.

Yes, true. There can only be one System Menu. So using Fl_Sys_Menu_Bar inside a Window or Widget Class is then a general problem if multiple windows can be open.

> More generally, and that was pointed out by Albrecht above, FLUID's use of the Fl_Window's `user_data` member is not correct in FLTK

That is true, but it's legacy code, and I don't really want to change it. I originally wante to integrate `fl_callback_macros.H` code generation into FLUID, but it is (currently) limited to widgets and can't handle menu item callbacks.

I have been trying things out for a few hours, but nothing works perfect so far. (Ab)using the `Fl_Sys_Menu_Bar` `user_data` field so far seems to be the least invasive and least painful.

**Comment by MatthiasWM** [comment] 2024-07-27 16:26
> I see that the new macro FL_METHOD_CALLBACK_x() allows to declare a callback for a non-static class method with custom parameters. Wouldn't that be the way to stop FLUID from "using the user_data field of the topmost window of a class to store a reference to that class, which is needed to call non-static members of that class" ?

Thanks for looking this up. The macros of course still use the user_data field, which is fine in the context of the macro. But it would still be a doubel use.

I am pondering to change the `Fl_Widget::user_data()` call. Hmm, I hope that I am onto something here ;-)

**Comment by MatthiasWM** [comment] 2024-07-27 18:29
If this solution works well, I could implement this for Class and Widget Class as well and no longer abouse the user_data field. But first let's see if this solution works ok.

**Comment by ManoloFLTK** [comment] 2024-07-28 06:25
I tried d265009 for [FluidPPMacMenu.fl.txt](https://github.com/fltk/fltk/files/15368225/FluidPPMacMenu.fl.txt) as posted above  both under macOS and X11 and see that running OK. I also added a second window and see the menubar to be active on both windows under macOS. Very good.

**Comment by MatthiasWM** [comment] 2024-07-28 10:49
@ManoloFLTK Thanks very much for testing the new code! 

@robbwheel Could you blease try the new code on your original app and see if that fixes your issue, so I can close the report. Thank you.

**Closed** 2024-08-04 12:37 UTC
Labels: bug, fluid, Prio 4 - High

**Comment by MatthiasWM** [comment] 2024-08-04 14:36
@ManoloFLTK please note that even our own test program Sudoku relies on Fl_Sys_Menu_Bar->parent(). I am worried that the change to disconnect the sys menu bar will cause other apps to fail.

**Comment by ManoloFLTK** [comment] 2024-08-05 06:40
> I am worried that the change to disconnect the sys menu bar will cause other apps to fail.

I will check all these apps.

**Comment by ManoloFLTK** [comment] 2024-08-05 06:52
Besides, test/sudoku, two other test apps use class Fl_Sys_Menu_Bar: cube and menubar. I've checked that none attempt to use the parent widget of the Fl_Sys_Menu_Bar object.
