### ISSUE TITLE
Fl_Menu_ implemented widgets have border as FL_FLAT_BOX type.

### ISSUE THREAD

**Issue by rageworx** [fltk/fltk#748] opened 2023-07-12 08:05 UTC
## Appearance issue 
I am not sure when it started in, but I found it since a few days ago when I had merged fltk/fltk to my fltk-custom version.

Ref. issue  = https://github.com/rageworx/fltk-custom/issues/56

## Guess
I think all implemented widgets has default FL_UP_BOX for their drop-down widget, but actually it doesn't appear any box type.
I'm not sure if it is a purposed feature or a bug. But as my remember, all drop-down widgets were always has FL_UP_BOX type as default.

## Some screenshots
fltk/fltk capture of unittest, selecting scheme widget:
![image](https://github.com/fltk/fltk/assets/6948225/7f49e580-b33b-47b3-a438-5b2a6fe8b84b)
- appears no border 

test modified to set box( FL_UP_BOX ) on constructor of Fl_Scheme_Choice(),
![image](https://github.com/fltk/fltk/assets/6948225/8d696ef3-6552-44a0-8b0c-b002bf702584)
![image](https://github.com/fltk/fltk/assets/6948225/82874671-b58b-4821-8fca-8684d321c97a)
- now it has border back.

## Idea
Fl_Menu_ default box type set to `box(FL_UP_BOX)` in constructor, but seems to not implemented.

Test as like this, included some experimental printf() on Fl_Scheme_Choice constructor.
![image](https://github.com/fltk/fltk/assets/6948225/9a27f830-089d-46ef-af30-32ae5c2dc4f3)

And actual prints :
![image](https://github.com/fltk/fltk/assets/6948225/bbd541a9-837a-45d4-b270-214deeb38efe)

Is it was purposed expression ?
Regards, Raph.K.

**Comment by MatthiasWM** [comment] 2023-07-12 10:56
Originally, popup windows uses the box type of the parent window. This seems to be a regression. I will look at that now.

**Comment by MatthiasWM** [comment] 2023-07-12 11:16
Ok, great 🫤. So this was changed in 72f8604 due to #675 complaint of not being able to change the pulldown menu frame.

Fl_Choice sets the boxtype to FL_FLAT_BOX, but overrides that in `draw()` to use FL_DOWN_BOX if no scheme is selected or FL_UP_BOX if any but the Windows98 scheme is selected. 

As the easiest and hopefully good-for-everyone solution, I simply set the default box type for Fl_Choice to FL_UP_BOX. It's ignored in the draw routine anyway, so we might just use it as the box type for the popup menu. Granted, that's not ideal, but unless we get the popup code completely rewritten, I see no chance here.

**Comment by MatthiasWM** [comment] 2023-07-12 11:19
Fixed in [9826b34](https://github.com/fltk/fltk/commit/9826b345ac3f6dd138d94b71cacd332c3a3ce2af)

**Comment by MatthiasWM** [comment] 2023-07-12 11:21
PS: It wasn't so obvious on my Mac because there popup windows are translucent and have a shadow anyway.

**Comment by rageworx** [comment] 2023-07-13 01:17
> PS: It wasn't so obvious on my Mac because there popup windows are translucent and have a shadow anyway.

I know that, because I have the same experience on my MacBooks, I found it on MSYS2+MinGW-W64 in a few days ago.
Thank you for fix!

**Comment by rageworx** [comment] 2023-07-13 05:19
Fixed.

**Comment by wcout** [comment] 2023-10-12 07:27
Note: `test/menubar` now does show the popup without border. Perhaps setting `mb.box(FL_NO_BOX)` in line 254 there should be removed.

**Comment by erco77** [comment] 2023-10-12 08:05
> Note: `test/menubar` now does show the popup without border. Perhaps setting `mb.box(FL_NO_BOX)` in line 254 there should be removed.

Similarly, I noticed my old Fl_Menu_Bar oriented app had a problem after updating to a recent fltk 1.4.x build, where the menubar's menus were posting without a border.

Found it was because I had the menubar's  box type set to FL_NO_BOX, which I'd set many many years ago to solve a layout issue, where the menubar's borders looked wrong when abutting other widgets, and that solved the problem.

I wasn't sure what to make of that, I just removed it and now live with the ugly layout issue, but it's better than weird menu windows.

Sounds like you all are running into this too. This might be a new problem that's cropped up in a recent 1.4.x that needs addressing.

**Comment by Albrecht-S** [comment] 2023-10-12 15:54
I'm reopening this issue so it isn't forgotten.

@MatthiasWM Can you please look into it and maybe assign to yourself?

**Comment by MatthiasWM** [comment] 2023-10-13 10:52
@wcout 1.3 also had the popup menus set to `FL_NO_BOX` in `test/menubar` , but I will happily remove that. We should show the default rendering which is `FL_UP_BOX`. Just changed that in master.

@erco77 the change that you are seeing was in response to #675 and is based on the limitation that popup menus inherit the box type from the menu button that controls them. I added `Fl_Menu_::menu_box()` which, if it is set, overrides the default behavior. So you can now set a menubar in FL_FLAT_BOX that pops up menus with FL_UP_BOX decoration.

Hoping that this solution satisfies all issues.

**Closed** 2023-10-22 22:57 UTC
Labels: waiting for confirmation
