### ISSUE TITLE
Wayland: scale/resize issue seen with 'demo' program 

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#419] opened 2022-03-22 04:25 UTC
How to reproduce:
- start test/demo
- change scale with `Ctrl+` key
- try to resize the program with the mouse or click on any other window on your desktop

Now the window size of the demo program is wrong (smaller than it should be) and will not recover.

The reason why the demo program is resizable at all is line 173 in demo.cxx:
```cxx
form->size_range(FORM_W,FORM_H,FORM_W+1,FORM_H+1); // XXX: +1 needed or window can't be made resizable later
```
When removing this statement the error does not happen. So it seems to confuse the Wayland driver.
(BTW: this line seems to be not required any longer anyway)

**Comment by Albrecht-S** [comment] 2022-03-22 21:05
I agree that the mentioned line should not be in the code in this form. It is weird anyway, I'll take a look at it later and see how this should be resolved. I know off the top of my head that the window size may be changed by user interaction if the console output (Fl_Simple_Terminal widget) gets enabled. This is very likely the reason for this statement and the associated comment.

However I hesitate to remove it to "solve" this issue. Maybe Manolo would like to use this as test code to check the Wayland behavior in this case. It could help to find another bug.

@Manolo: OTOH, since I changed the driver + resizable interaction it may be that this has to do with my changes. Please let me know if you find something that might be caused by my changes or if you want me to try to debug this.

**Comment by Albrecht-S** [comment] 2022-03-22 21:50
@wcout PS: I forgot to mention: thanks for all your testing, bug reports and other proposals. This is very much appreciated.

**Comment by ManoloFLTK** [comment] 2022-03-23 06:58
@wcout: please close issue if you agree.

**Comment by Albrecht-S** [comment] 2022-03-23 18:04
@wcout I'm looking into it but we can close this issue.

**Closed by Albrecht-S** 2022-03-23 18:04 UTC
Labels: bug, Platform: Wayland, Prio 3 - Moderate
