### ISSUE TITLE
add_subdirectory( fltk ) produces wrong CMake variables

### ISSUE THREAD

**Issue by Xunie** [fltk/fltk#177] opened 2020-12-30 01:00 UTC
[This tutorial](https://foonathan.net/2016/07/cmake-dependency-handling/) says I can just `add_subdirectory( someproject )` and start using its targets.
As do the people [here](https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html).

[This FLTK tutorial](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/ForFLTK) tells me to `TARGET_LINK_LIBRARIES(foo ${FLTK_LIBRARIES})`

So I did. Here's the example project that reproduces the following bug: https://github.com/Xunie/fltk-issue

---

When doing this, FLTK_LIBRARIES doesn't exist and the FLTK_* variables that *are* set have wrong values:
```
FLTK_BINDIR:PATH=bin
FLTK_BUILD_EXAMPLES:BOOL=OFF
FLTK_BUILD_TEST:BOOL=ON
FLTK_DATADIR:PATH=share
FLTK_DOCDIR:PATH=share/doc
FLTK_INCLUDEDIR:PATH=include
FLTK_LIBDIR:PATH=lib
FLTK_MANDIR:PATH=share/man
```

Go clone that example project of mine and configure a build. The build configures fine but the variables are unset.

Adding a `FIND_PACKAGE( FLTK ... )` or `FIND_LIBRARY( FLTK ... )` results in even more variables complaining about not being able to find FLTK, because clearly those functions are meant to search for a fully built package/library.

Is foonathan.net wrong and am I using CMake wrong? Or is this a bug in the fltk build?

**Comment by Xunie** [comment] 2020-12-30 01:54
I have to add that `target_link_libraries( main fltk )` does **NOT** fix the include directories. As per `README.CMake.txt` I have to specify `target_include_directories(hello PUBLIC ${FLTK_INCLUDE_DIRS})` but this variable is undefined as well.

**Comment by engelsman** [comment] 2020-12-30 10:22
First of all, you should really post this in the fltk.general discussion group where there are more people who can help

> [This tutorial](https://foonathan.net/2016/07/cmake-dependency-handling/) says I can just `add_subdirectory( someproject )` and start using its targets.
> As do the people [here](https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html).
>
> [This FLTK tutorial](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/ForFLTK) tells me to `TARGET_LINK_LIBRARIES(foo ${FLTK_LIBRARIES})`

Secondly, I wrote the original version of the [ForFLTK](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/ForFLTK) article (and the [Article 824](https://www.fltk.org/articles.php?L834+I0+Q) link) because I could not find a tutorial to help me. I was not a CMake expert, as stated in the article, so I posted it on the CMake site with the hope that the CMake community would be able to improve it, but that never happened. Since then, things have changed as described below.

> Adding a `FIND_PACKAGE( FLTK ... )` or `FIND_LIBRARY( FLTK ... )` results in even more variables complaining about not being able to find FLTK, because clearly those functions are meant to search for a fully built package/library.

Experimental work on CMake started in FLTK-1.3.5, but as far as I understood it, the FLTK support within CMake itself had been developed for earlier versions of both CMake and FLTK and had never been updated.

> Is foonathan.net wrong and am I using CMake wrong? Or is this a bug in the fltk build?

Not really, to all three. The problem is that the FLTK support in CMake is out of date.

FLTK-1.4.x has improved CMake support, as described in README.CMake.txt, but it's still a work in progress. There's an example CMakeLists.txt file with the two important lines and a subsequent explanation:

```
    set(FLTK_DIR /path/to/fltk)
    find_package(FLTK REQUIRED NO_MODULE)

    The set(FLTK_DIR ...) command is a superhint to the find_package command.
    This is very useful if you don't install or have a non-standard install.
    The find_package command tells CMake to find the package FLTK, REQUIRED
    means that it is an error if it's not found.  NO_MODULE tells it to search
    only for the FLTKConfig file, not using the FindFLTK.cmake supplied with
    CMake, which doesn't work with this version of FLTK.
```

This should get you past the basics, but ask in fltk.general if you need help with additional libraries.

D.

**Comment by Xunie** [comment] 2020-12-30 13:48
I wrote this issue last night while being extremely tired. I think the problem is that I wasn't pedantic enough. The title was also a big fat red herring.

A few points of clarification:
* I'm integrating the master branch (FLTK v1.4.0)
* FLTK is setting CMake variables that shouldn't be set with the wrong values (see above)
* The values that projects are told to rely on in that same README.CMake.txt file are not set!

If `add_subdirectory( some/git/submodule )` is standard CMake practice, then this has to be a bug.

**Comment by engelsman** [comment] 2021-01-07 12:39
OK, I'm afraid that I misunderstood what you were saying in your original post. I'm no CMake expert, but I think there are three separate issues here:

* corrections to the FLTK-1.4.x support for CMake so that the FLTKConfig.cmake file that is generated during the build/install process will return the correct variables for use by a calling project
* corrections to the CMake support for FLTK so that the FindFLTK.cmake and other files used by find_package() are up to date instead of the old version that my ForFLTK/Article824 was based on back in 2008
* understanding the internals of the modern-cmake add_subdirectory() for git submodules works and create a HOW-TO  for FLTK users

The FLTK team only have control over the first, which should probably be discussed on the [fltk.coredev](https://groups.google.com/g/fltkcoredev) mailing list, where more people will see it. The second probably requires the improvements of the first before approaching the CMake devs, and the third probably requires both.

As usual, user contributions and pull requests are always welcome :-)

**Comment by Albrecht-S** [comment] 2024-02-08 16:41
@Xunie You wrote:
> (1) [This tutorial](https://foonathan.net/2016/07/cmake-dependency-handling/) says I can just add_subdirectory( someproject ) and start using its targets.
(2) [This FLTK tutorial](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/ForFLTK) tells me to TARGET_LINK_LIBRARIES(foo ${FLTK_LIBRARIES})
(3) Is foonathan.net wrong and am I using CMake wrong? Or is this a bug in the fltk build?

I apologize for the late reply and I'm trying to answer all questions. I'll also provide a working solution below (tested).

1. This tutorial is correct but requires that the project you're trying to use is prepared for "Modern CMake". At the time of your original post FLTK was not yet ready for this usage (today it is).
2. The mentioned tutorial is really old and outdated, as @engelsman said. However, using the given statement would have worked if you configured FLTK as documented (at that time) and not by using it as a Git submodule and add_subdirectory(). These two approaches are not not compatible. The (main) reason for this incompatibility is that building FLTK in a subdirectory does not define the variables that would be defined by using an already-built project with CMake's CONFIG mode. Even if any FLTK_ variables were set in the subdirectory, CMake would not propagate them to the caller's (your main project's) scope.
3. foonathan.net is correct but you were mixing two different approaches to build and include another project and FLTK was not yet ready for Modern CMake which the tutorial required.

That said, here is my modified CMakeLists.txt from your project:
```CMake
cmake_minimum_required( VERSION 3.0 )

project( fltkproject
         LANGUAGES CXX )

add_subdirectory( git-submodules/fltk )

# At this point, many FLTK_* variables are set in the CMake cache but
# you can't expect any useful values here as normal CMake variables
# because FLTK is built in a subdirectory.

# However, you can use FLTK *targets* as needed.

message( "libraries: " ${FLTK_LIBRARIES} )   # EMPTY!
add_executable( main
    src/main.cpp
)

target_link_libraries( main
    PRIVATE
        fltk::fltk
)
```

If you update your git submodule to current FLTK git (branch master) you should be able to build your project. You need at least commit fd5cd809356dc73d2ede5bb2f0db25098771cb8e ('_Introduce "Modern CMake" in FLTK_', Feb 7, 2024) but you should always pull current master.

Note that `FLTK_LIBRARIES` is still empty but it's not needed to build the project. Everything you need to build (include directories, link libraries) is provided by the FLTK library (`fltk::fltk`).

**Comment by Albrecht-S** [comment] 2024-02-08 16:43
@Xunie Please confirm that this works for you and close this issue. Otherwise it will be closed in a few days.

**Comment by Albrecht-S** [comment] 2024-02-12 15:11
No reply for four days. Closing the issue.

**Closed by Albrecht-S** 2024-02-12 15:11 UTC
Labels: fixed, CMake, waiting for confirmation
