### ISSUE TITLE
[Bug] X11: Left Shift isn't recognized correctly while Alt is held

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1045] opened 2024-08-21 01:44 UTC
**Describe the bug**

While Alt is held, Left Shift correctly updates `Fl::event_key()` but does not correctly update `Fl::event_text()` or `Fl::event_state()`.
Right Shift continues to work as normal.

**To Reproduce**

1. Run test/keyboard
2. See that both Left Shift and Right Shift correctly update `Fl::event_state()`
3. Hold Alt
4. With Alt held, see that only Right Shift correctly updates `Fl::event_state()` but that Left Shift does not

Also:
1. Run test/keyboard
2. See that both Left Shift and Right Shift correctly update `Fl::event_text()` when used in combination with an ASCII key (I used the `` `/~ `` key in the example video below)
3. Hold Alt
4. With Alt held, see that only Right Shift correctly updates `Fl::event_text()` to display `~` but that Left Shift incorrectly displays `` ` ``

**Expected behavior**

Left Shift should continue to work in the same way as Right Shift whether Alt is held or not.

**Video**

https://github.com/user-attachments/assets/a992146e-2fca-4ef7-8eab-cba7c6079c2b

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: f151ecb

**FLTK Configure / Build Options**
 - cmake -D CMAKE_BUILD_TYPE=Release

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Peppermint OS 10
 - Processor if relevant: Intel

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

I noticed this in my own application by trying to use the shortcut ``FL_ALT + FL_SHIFT + '`'`` and noticing that the shortcut is only activated on Linux with Right Shift, and not recognized with Left Shift.

**Comment by ManoloFLTK** [comment] 2024-08-21 13:19
I can't reproduce what you report here under Ubuntu 24.04: left and right shift keys have the same effects when the alt key is pressed. Are you sure you didn't assign some compose or shortcut command to your left-shift+alt combination?

**Comment by Albrecht-S** [comment] 2024-08-21 15:41
> I can't reproduce what you report here under Ubuntu 24.04 ...

Neither can I on Debian Bookworm (running X11 with XWayland under the Gnome/Wayland desktop), using `test/handle_keys.cxx` (independent key sequences separated by blank lines):

```
[nnn] Event           Key     Name,  Flags: C A S M N L  Text  Unicode   UTF-8/hex
[  7] FL_KEYDOWN      0xffe1  FL_Shift_L    . . . . . .  ''
[  8] FL_KEYUP        0xffe1  FL_Shift_L    . . S . . .  ''

[  9] FL_KEYDOWN      0xffe9  FL_Alt_L      . . . . . .  ''
[ 10] FL_KEYDOWN      0xffe1  FL_Shift_L    . A . . . .  ''
[ 11] FL_KEYUP        0xffe1  FL_Shift_L    . A S . . .  ''
[ 12] FL_KEYUP        0xffe9  FL_Alt_L      . A . . . .  ''

[ 13] FL_KEYDOWN      0xffe2  FL_Shift_R    . . . . . .  ''
[ 14] FL_KEYUP        0xffe2  FL_Shift_R    . . S . . .  ''

[ 15] FL_KEYDOWN      0xffe9  FL_Alt_L      . . . . . .  ''
[ 16] FL_KEYDOWN      0xffe2  FL_Shift_R    . A . . . .  ''
[ 17] FL_KEYUP        0xffe2  FL_Shift_R    . A S . . .  ''
[ 18] FL_KEYUP        0xffe9  FL_Alt_L      . A . . . .  ''
```

I admit that I noticed some unexpected behavior in the above mentioned `test/keyboard.cxx` program, but this may be caused by that demo program. Note that the Shift Flag is reported in `Fl::event_state()` (`C A S M N L`) only **after** the keypress event has been sent (this is documented).

@dannye : Please test again with `test/handle_keys.cxx` (enable `FL_KEYDOWN` and `FL_KEYUP` by checking these buttons) and report here what you get if it differs substantially from my output above. Note that the headline can be written to the text buffer by button "Clear" and the full contents of the buffer can be copied to the clipboard with the "Copy" button.

Also, please note that Peppermint 10 seems to be pretty old, based on "18.04 LTS" (sounds like Ubuntu?), which may have some old OS/X11 related bugs that have been fixed in newer versions. From https://peppermintos.com/2019/05/peppermint-10-released/ :
> "Team Peppermint are pleased to announce Peppermint 10 (20190514), the latest iteration of our operating system. Based on the 18.04 LTS (long term support) code base, ..."

Although they also write:
> "We do use the common process of [continuous delivery](https://peppermintos.com/about/), and we are based on the Debian/Devuan repositories."

Whatever this means ...

**Comment by Albrecht-S** [comment] 2024-08-21 15:43
PS: please let us know what keyboard layout (US, UK, anything else) you are using, and what type of keyboard (laptop or PC with 101/102 keyboard etc.)

**Comment by Albrecht-S** [comment] 2024-08-22 01:29
FTR: Tested successfully with `test/handle_keys.cxx` on PeppermintOS (current, no version: based on Debian Bookworm) installed today in a VM and running Xfce (X11 only): no issues, works as documented above.

**Comment by dannye** [comment] 2024-08-22 03:25
Here is my output from handle_keys:

```
[nnn] Event           Key     Name,  Flags: C A S M N L  Text  Unicode   UTF-8/hex
[  1] FL_KEYDOWN      0xffe1  FL_Shift_L    . . . . . .  ''
[  2] FL_KEYUP        0xffe1  FL_Shift_L    . . S . . .  ''

[  3] FL_KEYDOWN      0xffe9  FL_Alt_L      . . . . . .  ''
[  4] FL_KEYDOWN      0xffe1  FL_Shift_L    . A . . . .  ''
[  5] FL_KEYUP        0xffe1  FL_Shift_L    . A . . . .  ''
[  6] FL_KEYUP        0xffe9  FL_Alt_L      . A . . . .  ''

[  7] FL_KEYDOWN      0xffe2  FL_Shift_R    . . . . . .  ''
[  8] FL_KEYUP        0xffe2  FL_Shift_R    . . S . . .  ''

[  9] FL_KEYDOWN      0xffe9  FL_Alt_L      . . . . . .  ''
[ 10] FL_KEYDOWN      0xffe2  FL_Shift_R    . A . . . .  ''
[ 11] FL_KEYUP        0xffe2  FL_Shift_R    . A S . . .  ''
[ 12] FL_KEYUP        0xffe9  FL_Alt_L      . A . . . .  ''
```

Event [5] is just missing the shift state for some reason..

> Are you sure you didn't assign some compose or shortcut command to your left-shift+alt combination?

I definitely didn't configure anything like that myself personally.

> PS: please let us know what keyboard layout (US, UK, anything else) you are using, and what type of keyboard (laptop or PC with 101/102 keyboard etc.)

I'm running this on a Dell XPS 13 laptop, with a US keyboard layout. The result is the same with the built-in laptop keyboard or with a full sized external USB keyboard.

It's true that the OS is a few years old. I'm running the last version of Peppermint that was based on Ubuntu, before they switched to Debian.

It's very possible this is an OS bug, in which case I don't want to waste any more of your time than you've already spent on this.

**Comment by Albrecht-S** [comment] 2024-08-22 09:47
@ManoloFLTK wrote:
> I suggest to close this issue and label it as an old Peppermint error which has been corrected later.

... or better: Ubuntu 18.04 error ...

@dannye wrote:
> It's very possible this is an OS bug, in which case I don't want to waste any more of your time ...

OK, since we rely on the state bit sent by X11 (we don't assemble the bits in FLTK, we just copy them) I don't see that we could create a workaround for this.

**Conclusion:** I'm closing this issue with label "wontfix" because it seems to be an OS (X11) bug caused by the old version of Peppermint 10 (based on Ubuntu 18.04 LTS). Newer OS versions (Ubuntu, Debian, and Peppermint "current") don't show this effect.

**Closed** 2024-08-22 09:48 UTC
Labels: wontfix, Platform: X11
