### ISSUE TITLE
Problem building documentation with Doxygen version ≥ 1.9.4

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#505] opened 2022-09-23 06:09 UTC
A problem appears in the HTML documentation as built with Doxygen version 1.9.4 (today's most recent version of Doxygen is 1.9.5). The problem is in the table of contents appearing in the left panel of the HTML doc. These images show the situation with the problem (top: "FLTK programming manual" contains no sub-items) and with the proposed fix (bottom: sub-items appear) :
![bug-with-1 9 4](https://user-images.githubusercontent.com/41016272/191899476-8411bdb1-d335-4aee-85fe-dae9769e2cb5.jpg)
![fixed-for-1 9 4](https://user-images.githubusercontent.com/41016272/191899486-ef15cf4e-8228-406b-89ae-90db2058bfa1.jpg)

The proposed fix is to change line 3 of `documentation/src/index.dox` from
`\mainpage FLTK Programming Manual`
to
`\page mainpage FLTK Programming Manual`

I've checked the modified `index.dox` is OK with older versions of Doxygen (specifically 1.8.14 dated Jan 2018). I didn't consider pdf documentation.

Comments ?

**Comment by Albrecht-S** [comment] 2022-09-23 08:51
That's weird: `\mainpage` is a valid doxygen command, see [doxygen documentation](https://www.doxygen.nl/manual/commands.html#cmdmainpage). The docs say:
> If the \mainpage command is placed in a comment block the block is used to customize the index page (in HTML) or the first chapter (in LaTeX).

You could argue that index.dox is not "a comment block" but I believe that this is a probably doxygen bug and will hopefully be fixed in a later version. I don't have the time to test right now but I can certainly build 1.9.4 and 1.9.5 to see what is happening with these version. Later.

The problem I can imagine with the proposed fix is that there won't be any hint to what should be the main (index) page in HTML and in PDF.

It's hard to say if we should change it or leave it as is and warn users not to build the docs with 1.9.4. Perhaps the bug is either fixed or known to the doxygen folks?

@manolo Did you also test with 1.9.5?

That said, our GitLab mirror builds the doxygen docs (currently) with 1.9.1 which is good. IMHO versions 1.9.2 and 1.9.4 (likely also 1.9.3) are broken because the HTML class index has a new format (Manolo, can you please test and verify this?) that doesn't fit on the HTML page w/o horizontal scrolling to select any class beyond the first few classes. The old format until 1.9.1 (see [docs at fltk.org](https://www.fltk.org/doc-1.4/classes.html) and at our GitLab mirror) seems to be much better IMHO. I don't know why they changed this. :-(

**Comment by ManoloFLTK** [comment] 2022-09-23 13:13
1.9.4 and 1.9.5 do the same thing. Thus, the change appeared with 1.9.4 was not reverted by 1.9.5. I'm not sure it's a Doxygen bug, and it seems it would be dangerous to bet it will be reverted.

My view now is that the proposed fix is useful because with it, resulting HTML pages are OK all the way from 1.8.14 to 1.9.5.

I've seen the new indices and don't like them at all. I'll search if there's an option to keep indices the old way.

**Comment by erco77** [comment] 2022-09-23 19:38
Doxygen is on github, so you can open an issue if you can create "a, small, self contained example" demonstrating the problem:
https://github.com/doxygen/doxygen/issues

**Comment by erco77** [comment] 2022-09-23 20:06
I can confirm this issue is still present with the latest build of doxygen from git 1.9.6 (01b73df835), so if it's an actual bug in doxygen, it should probably be reported using [doxygen's issue page](https://github.com/doxygen/doxygen/issues).

**Comment by Albrecht-S** [comment] 2022-09-24 12:29
@ManoloFLTK wrote:
> … the proposed fix is useful because with it, resulting HTML pages are OK all the way from 1.8.14 to 1.9.5.

I disagree. The resulting `index.html` is not correct if you change `'\mainpage ...'` to `'\page mainpage ...'`. The menus are available (that's correct) but if you open `index.html` the view is different, it doesn't show the main page with all the chapters in the right panel.

Old view with `\mainpage` (as [currently on GitLab](https://fltk.gitlab.io/fltk/index.html), Doxygen 1.9.1):
![doxygen_mainpage](https://user-images.githubusercontent.com/26235500/192096741-10e90523-20a2-4dfe-a831-76c9fc16f55c.png)

Changed view with `\page` (Doxygen 1.8.17):
![doxygen_page](https://user-images.githubusercontent.com/26235500/192096811-a52c8e8f-5cd0-471d-99fc-516be3d891cf.png)

It is obviously essential to have a `\mainpage` command to populate `index.html` and/or (as the docs say) the first page of the PDF docs.

I'm trying to create a small example that shows the effect as a reproducer to file a bug report (GitHub issue) for Doxygen.

**Comment by Albrecht-S** [comment] 2022-09-24 12:35
BTW: the PDF docs would be different as well. Please check yourself.

**Comment by ManoloFLTK** [comment] 2022-09-26 14:21
@Albrecht-S  OK. I agree \mainpage remains necessary.
Let's hope you can find a convincing reproducer and Doxygen will fix that.

**Comment by Albrecht-S** [comment] 2022-09-27 10:29
FYI: I created GitHub issue https://github.com/doxygen/doxygen/issues/9616 for Doxygen.

**Comment by Albrecht-S** [comment] 2022-09-27 12:56
@ManoloFLTK wrote:
> Let's hope you can find a convincing reproducer and Doxygen will fix that.

The author of the problematic commit replied quickly and classified it as "bug" which makes me hope that it can be fixed soon.

**Comment by ManoloFLTK** [comment] 2022-09-27 14:15
🤞

**Comment by Albrecht-S** [comment] 2022-10-09 12:42
This issue has been fixed upstream in https://github.com/doxygen/doxygen/commit/c84ec66d1255f8802b35e64c804c57fd67844bdc (branch master) and will be in the next official release (supposedly 1.9.6).

I tested it and it worked well, although there's another regression (some bogus warnings) which I will report in another doxygen issue.

The consequence is that we should keep in mind that Doxygen `1.9.4` and `1.9.5` should not be used to generate the official FLTK documentation.

Closing this issue now as fixed.

**Closed by Albrecht-S** 2022-10-09 12:42 UTC
Labels: fixed, documentation, Prio 2 - Low
