### ISSUE TITLE
FLTK 1.4.x has inconsistent line width in high DPI mode

### ISSUE THREAD

**Issue by felixxing** [fltk/fltk#741] opened 2023-07-03 02:29 UTC
**Describe the bug**
As said in the title, the drawing seems to be inconsistent.

**To Reproduce**
Just simply create a window that can be resize and add any random widget to it.
Note i am running on window 10 22H2, build by Msys2.
resize the window at any direction, and you can see it.

**Expected behavior**
On windows, it rounds donw the thickness

**Screenshots**
<img width="542" alt="Screenshot 2023-07-02 222739" src="https://github.com/fltk/fltk/assets/101950667/1b91e1fa-834b-4f7e-a1a4-2a6c5e35a57f">

window 10 22H2
DPI scale at 1.5.

**Comment by ManoloFLTK** [comment] 2023-07-04 09:18
FLTK 1.4 supports variable DPI scale values multiplying user coordinates by the scale factor (a.k.a. DPI scale) and drawing with these modified coordinates. Now, because the drawing system used under Windows and X11 is intrinsically based on integer coordinates, a rounding problem arises when the scale factor is fractional, as when DPI is set at 1.5. The problem is especially important for line widths. What FLTK 1.4 does is to adjust line widths so that lines drawn at adjacent user coordinates are also adjacent with modified coordinates. This property is necessary for the grey and black lines  of the screen shot above to remain adjacent. The outcome is what you report here: lines with the same user thickness are drawn slightly thiner or slightly thicker depending on their location on the display. That is what FLTK 1.4 does, and it's very unlikely another solution can be found. If you can set the DPI factor to the integral value of 2, none of what you report here will occur.

**Comment by ManoloFLTK** [comment] 2023-07-06 13:50
@felixxing  If you are satisfied with the information given above, please close this issue. If you are not, please explain why.

**Closed** 2023-07-06 13:51 UTC
