### ISSUE TITLE
website: links need to show publish date/last edit

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#470] opened 2022-07-21 19:58 UTC
Browsing/Reading articles, it should show the date the article was first published and/or last edited by the author. Currently it does not:
![image](https://user-images.githubusercontent.com/6484779/180304047-20ca0ef9-945b-41c5-b93d-97fe5657ee05.png)

Example URL: https://www.fltk.org/links.php?V14+Q

The posting date is essential info. For example, it helps when trying to locate stale projects on archive.org by snapshot date.
(With stale links, there's often a small window between when the author first posted the project, and when their site went stale. So it helps to look for snapshot dates as close to the publish date as possible)

**Comment by Albrecht-S** [comment] 2022-07-23 11:10
Note: the original title referred to 'articles' but this issue is about 'links'. I changed the title and uploaded a fix.

**Comment by Albrecht-S** [comment] 2022-07-23 12:34
Note: there are about 100 links that don't have a valid creation date or modification date. Such invalid dates are now listed as "unknown" rather than "Jan 1, 1970" or, even worse "Dec 31, 1969" (caused by time zone differences).

BTW, the oldest valid creation date is "Oct 27, 2001".

@erco77 Greg, is this fix sufficient for you? If yes, please close the issue. Thanks.

**Comment by Albrecht-S** [comment] 2022-07-23 12:46
Here's a potential option: if "unknown" is not enough we could "guess" and change this to something like "before Oct 27, 2001" or maybe "< Oct 27, 2001" if this helps. Note that the example link above shows now "unknown" as creation date.

This would not be much better but it's at least a hint, meaning: _"at some time between 1998 and Oct 27, 2001"_.

**Closed** 2022-08-01 10:31 UTC
Labels: enhancement, fixed
