### ISSUE TITLE
Support for old compilers (gcc 2.x)

### ISSUE THREAD

**Issue by michaelbaeuerle** [fltk/fltk#939] opened 2024-03-20 10:19 UTC
As discussed in fltk.general, here is the test with an old egcs compiler (GCC 2.91).
Tested with git revision 8b094e8af3215bed1c3c3c662e4b93163dac6bbc and my HP-UX patches from #937 applied:
[FLTK-1.4_egcs_error_log.txt](https://github.com/fltk/fltk/files/14664330/FLTK-1.4_egcs_error_log.txt)

Header not included:
[patch_src_drivers_Unix_Fl_Unix_Screen_Driver.cxx.txt](https://github.com/fltk/fltk/files/14664593/patch_src_drivers_Unix_Fl_Unix_Screen_Driver.cxx.txt)

Comparison between const and non-const pointer:
[patch_src_Fl_Terminal.cxx.txt](https://github.com/fltk/fltk/files/14664644/patch_src_Fl_Terminal.cxx.txt)

C++ visibility problems:
[patch_FL_Fl_Terminal.H.txt](https://github.com/fltk/fltk/files/14664664/patch_FL_Fl_Terminal.H.txt)
[patch_src_Fl_GIF_Image.H.txt](https://github.com/fltk/fltk/files/14664665/patch_src_Fl_GIF_Image.H.txt)

The ugly part: Cast to void does not work:
[patch_src_xutf8_lcUniConv_iso8859_10.h.txt](https://github.com/fltk/fltk/files/14664677/patch_src_xutf8_lcUniConv_iso8859_10.h.txt)
(the same problem exist in some other header headers in this directory)
FLTK 1.3 does not do this and it seems that the casts were explicitly added for modern compilers.

I disabled OpenGL support and enabled the bundled zlib and image libraries.
Now it can be compiled again.

**Comment by Albrecht-S** [comment] 2024-03-20 13:28
@michaelbaeuerle Thanks for your patches again.

Please note that we made a deliberate decision to remove support of gcc 2.x (and thus egcs) back in 2010 (3cf2305b5c326ef7d15e7eaf37302a6853bddabc) which applied to FLTK 1.3.0 (!) and we didn't get any reports for such old compilers since then.

Therefore we can't accept any changes that introduce GCC version specific checks in the code.

I'll investigate your patches anyway to see if something is useful for newer compilers as well. I'll report my findings later.

**Comment by michaelbaeuerle** [comment] 2024-03-20 14:31
GCC 2 does not support C99, but later versions are good enough to build FLTK 1.3.
This was just a test what would be required to build FLTK 1.4 with it.

At least the missing include looks like a bug, regardless of the compiler.

**Comment by Albrecht-S** [comment] 2024-03-20 16:43
> At least the missing include looks like a bug, regardless of the compiler.

Yep. Done in commit b3b051240ecf3ab562e73d3d5674d05aff261fc4.

Looking for more...

**Comment by Albrecht-S** [comment] 2024-03-20 17:02
> Comparison between const and non-const pointer:
[patch_src_Fl_Terminal.cxx.txt](https://github.com/fltk/fltk/files/14664644/patch_src_Fl_Terminal.cxx.txt)

Although the warning is "correct" (technically) I'm not sure if the patch is really useful or if it is only due to an incorrect implementation of (later?) standards.

IMHO you should be able to compare pointers types Fl_Widget* with Fl_Terminal* because Fl_Terminal `is a` Fl_Widget.

The remaining question is: why would it need a cast to compare a `const` pointer to a non-`const` pointer?

I tend to not apply this specific patch because it adds an ugly cast for no real reason (except this old, no longer supported compiler from the FLTK POV). Michael, comments?

**Comment by Albrecht-S** [comment] 2024-03-20 17:04
All the other patches seem to be caused by the same visibility issue. Although "something" is protected it is not visible by a class **_included_** in a subclass. I'm not a C++ "guru" but I'd guess that this is either valid in a later C++ spec. or the old compiler is incorrect. Hence I wouldn't want to change anything in these patches.

@michaelbaeuerle If you agree I will close this issue with only one of your patches applied. I'm waiting for your comment on https://github.com/fltk/fltk/issues/939#issuecomment-2010073663 though.

**Comment by Albrecht-S** [comment] 2024-03-22 19:21
OK, thanks, I'm closing this now with label "wontfix" because not all reported warnings/errors could be fixed.

I also changed the title by appending "(gcc 2.x)" to make clear that these issues can't be fixed because they are caused by `gcc 2.x` and/or `egcs` whose FLTK support has been dropped in the year 2010.

**Closed by Albrecht-S** 2024-03-22 19:21 UTC
Labels: wontfix
