### ISSUE TITLE
Compile error src/scandir_posix.c extra bracket

### ISSUE THREAD

**Issue by markjolesen** [fltk/fltk#162] opened 2020-11-23 00:28 UTC
fl_scandir(const char *dir, struct dirent ***namelist,
           int (*sel)(struct dirent *),
           int (*compar)(struct dirent **, struct dirent **),
           char *errmsg, int errmsg_sz) { // <--- ERROR BRACKET HERE
{ <-- AND HERE

produces compiler error

**Comment by Albrecht-S** [comment] 2020-11-23 00:58
@erco77 @markjolesen Bug confirmed and fixed. Will commit shortly ...

**Comment by erco77** [comment] 2020-11-23 01:01
@Albrecht-S be sure to test build; I think I see other problems; Line 485 in `src/drivers/X11/Fl_X11_System_Driver.cxx` calls fl_scandir() with only 4 arguments when HAVE_SCANDIR is unset, but ours expects 6..

**Comment by Albrecht-S** [comment] 2020-11-23 01:11
@erco77 Thanks, Greg, I did only a quick hack to compile this source file and found that I also had to `#include "flstring.h"`, see this patch: [issue-162.diff.txt](https://github.com/fltk/fltk/files/5580748/issue-162.diff.txt). I'm **NOT** going to commit this now because...

I can't do a full build with undefined `HAVE_SCANDIR` (too late, need some sleep). Please feel free to take over and go ahead, or drop me a note so I can continue tomorrow.

**Comment by Albrecht-S** [comment] 2020-11-23 01:11
@markjolesen On which system / platform does this happen to you? Please be as precise as possible since this issue has long been unnoticed. Thanks for your help.

**Comment by erco77** [comment] 2020-11-23 01:19
OK, I'll give it a shot. I'm basically unsetting HAVE_SCANDIR by hand-hacking the config.h.
Not sure what the OP's platform is.. would like to know what that is as well.

**Comment by Albrecht-S** [comment] 2020-11-23 01:25
> I'm basically unsetting HAVE_SCANDIR by hand-hacking the config.h.

:+1: 

That's what I would have done too.

**Comment by markjolesen** [comment] 2020-11-23 01:59
The Operating System I was using is FreeDOS 1.2 (I am getting fltkal
project up to date with recent FLTK)

**Comment by erco77** [comment] 2020-11-23 02:03
FreeDOS? As in non-windows?
Wow, well you might be in for an uphill battle, not sure.
We don't test for FreeDOS and I don't think we "officially" support it, but hey, if we can, we'll try.
Anyway, I'm close to a commit.. will follow up with something to try shortly..

**Comment by erco77** [comment] 2020-11-23 02:21
OK, try a41d8c0e6.

**Comment by markjolesen** [comment] 2020-11-23 16:48
Over the years, I have just reported things that I think need fixing.
Sometimes they do other times it's just noise.

By the way, FLTK code is very portable.

**Comment by Albrecht-S** [comment] 2020-11-23 21:08
@erco77 I'm glad you took over. I think you know that `errmsg` stuff best.

I added the label "fixed" (again) and I believe we can close this issue. @erco77 , @markjolesen ?

**Comment by Albrecht-S** [comment] 2021-01-09 12:42
No further comments since more than a month - closing this issue now.

**Closed by Albrecht-S** 2021-01-09 12:42 UTC
Labels: bug, fixed
