### ISSUE TITLE
FL_OPENGL3 incompatible with FL_DOUBLE

### ISSUE THREAD

**Issue by al-popa** [fltk/fltk#1005] opened 2024-07-03 07:50 UTC
**Describe the bug**
Cannot set `Fl_Gl_Window::mode(FL_DOUBLE | FL_OPENGL3)`.

**To Reproduce**
Existing FLTK program **examples/OpenGL3test.cxx** without any modification shows the problem. Compiled with downloaded [(GLEW-2.2.0)](https://sourceforge.net/projects/glew/files/glew/2.2.0/glew-2.2.0.zip/download) and linked statically as:
`g++ -I.. -I../../glew-2.2.0/include -I../png -I../zlib -I../jpeg -I/usr/include/freetype2 -I/usr/include/libpng16 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -o OpenGL3test OpenGL3test.cxx ../../glew-2.2.0/lib/libGLEW.a ../lib/libfltk.a ../lib/libfltk_gl.a -lGLU -lGL -lXrender -lXcursor -lXfixes -lXft -lfontconfig -lXinerama -pthread -lpthread -lm -lX11`
Possible workaround:
Change line 48:
`mode(FL_RGB8 | FL_DOUBLE | FL_OPENGL3);`
into:
```
#ifdef __APPLE__
  mode(FL_RGB8 | FL_DOUBLE | FL_OPENGL3);
#else
  mode(FL_RGB8 | FL_DOUBLE);
#endif
```

1. Run **OpenGL3test**.
2. OpenGL canvas remains blank, but right-hand output shows some activity on mouse input.
3. Switch off `Double-Buffered`
4. OpenGL canvas shows graphics and refreshes on mouse input.

**Expected behavior**
OpenGL canvas switches buffers and shows the model.

**Screenshots**
![Wrong](https://github.com/fltk/fltk/assets/48083723/aba5f59c-50b2-4dc2-89a1-7d29f1a06801)
![Expected](https://github.com/fltk/fltk/assets/48083723/3b5afa77-c376-41cc-b9cb-7b02279b92e7)

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Snapshot fltk-1.4.x-20231027-0b408792

**FLTK Configure / Build Options**
 - ./configure
 - make

**Operating System / Platform:**
 - Linux: Debian 12
 - Intel x86_64

**Linux/Unix Runtime, if applicable:**
 - Cinnamon DE: Wayland capable but not enabled, using X11.

**Additional note**
The problem seems to be missing / invalid buffer switch. Blank OpenGL canvas shows full geometry for a moment just before application closing.

**Comment by al-popa** [comment] 2024-07-03 08:51
Retested with **fltk-1.4.x-20240628-bdd658ee** using the compilation command:
```
g++ -I../../glew-2.2.0/include `../fltk-config --use-gl --cxxflags` -o OpenGL3test OpenGL3test.cxx ../../glew-2.2.0/lib/libGLEW.a `../fltk-config --use-gl --ldstaticflags`
```
Same result.

```
g++ --version
g++ (Debian 12.2.0-14) 12.2.0
```

**Comment by Albrecht-S** [comment] 2024-07-03 13:39
@al-popa Thanks for the report and the workaround. I can confirm it on my Debian 12 (Bookworm) system (same as the OP but built using CMake).

Further info:
- X11 (XWayland) running on Gnome/Wayland desktop: same symptoms as reported by @al-popa
- Wayland: (same executable) works as expected.

I'm leaving this to other devs to find the proper solution.

**Comment by ManoloFLTK** [comment] 2024-07-03 16:15
No problem here (Ubuntu 24.04 in VM) neither under X11 nor under Wayland.

**Comment by ggarra13** [comment] 2024-07-04 17:36
Works for me too with NVidia drivers on native Ubuntu 24.04.4 LTS.

**Comment by al-popa** [comment] 2024-07-04 20:52
My graphics device is AMD Whistler Radeon HD 6730M/6770M/7690 XT. But this information seems irrelevant, the same graphics card worked flawlessly with FLTK 1.3 with X11 only.

**Comment by ManoloFLTK** [comment] 2024-07-12 16:22
@al-popa Isn't the workaround you meant to replace
`mode(FL_RGB8 | FL_DOUBLE | FL_OPENGL3);`
by
`mode(FL_RGB8  | FL_OPENGL3);`
that is, remove the FL_DOUBLE flag?

@Albrecht-S It's very strange that you see an issue whereas @ggarra13 and I don't. Could you report here what do you see when you remove from the OpenGL3test.cxx program the child widgets of the Fl_Gl_Window ? That is, comment out line #258 of file `examples/OpenGL3test.cxx` to obtain
  `//add_widgets(win);`

**Comment by al-popa** [comment] 2024-07-13 05:48
@ManoloFLTK  Yes, the work-around is just removing FL_OPENGL3 flag except on MacOS, where it is essential. On all other platforms, including Linux, the OpenGL context anyway is initialized with highest possible value. Another change which does the trick is changing:
`mode(RGB8 | FL_DOUBLE | FL_OPENGL3)`
by
`mode(RGB8 | FL_SINGLE | FL_OPENGL3)`
but it effective changes the double-buffered GL window with single-buffered. The important part is not putting `FL_DOUBLE` together with `FL_OPENGL3` in `mode(...)`.

The problem may be really Debian specific. In this case it is Debian's issue.

**Comment by al-popa** [comment] 2024-07-13 05:59
@ManoloFLTK , the child widgets removal (commenting out line 258 of `examples/OpenGL3test.cxx`) does not fix the problem. And initially I observed the problem in my project, where `Fl_Gl-Window` does not have any children.

**Comment by Albrecht-S** [comment] 2024-07-13 14:08
> @Albrecht-S It's very strange that you see an issue whereas @ggarra13 and I don't.

@ManoloFLTK Please note that I see these issues **_if and only if_** I run the demo `OpenGL3test` with `FLTK_BACKEND=x11`, using the "hybrid" FLTK build. I ran the same executable in my Debian Testing VM using either the `Gnome/Wayland` or the `Gnome/X11` desktop environment. In the former I could run both Wayland and X11 backends, whereas I only used the x11 backend on the latter (pure X11 desktop). The `XWayland` application (x11 on Wayland, screenshot 1) works IMHO even "better" than the x11 backend under the X11 desktop (screenshot 2) where it doesn't show any background and the desktop image shows through. See screenshots below.

I did **not** comment out the widgets as suggested by @ManoloFLTK because @al-popa wrote that this doesn't affect the program.

**_Screenshot 1 (Gnome/Wayland):_**
![OpenGL3test_Debian_Testing_Gnome_Wayland](https://github.com/user-attachments/assets/71312255-d567-4109-bd02-a0d9aeed2821)

**_Screenshot 2 (Gnome/Xorg):_**
![OpenGL3test_Debian_Testing_Gnome_Xorg](https://github.com/user-attachments/assets/03452482-84ed-42c0-a096-99029044bad8)

In all cases I also noticed that the OpenGL scene gets drawn shortly when the window is closed, it "flashes" quickly and disappears when the window is unmapped. Uncheking the "`Double-Buffered`" button also fixes the issue on all tested (Linux) platforms.

I also see identical effects when running the (similar) 1.3 `examples/OpenGL3test.cxx` (using the FLTK 1.3 lib).

Note: I'm trying to help by testing on my platforms but I can't contribute to a solution regarding OpenGL etc.. HTH anyway.

**Comment by ManoloFLTK** [comment] 2024-07-13 15:25
@Albrecht-S All this is very strange. We both use the gnome-wayland desktop in a debian or ubuntu VM and you see the issue when running the program as an X11 client, whereas I and Gonzalo (who uses a true Linux box) don't. What version of Debian or Ubuntu do you run? I use Ubuntu 24.04.

<img width="807" alt="image" src="https://github.com/user-attachments/assets/1f9feee3-ad02-47f3-a648-531871665fcb">

**Comment by ManoloFLTK** [comment] 2024-07-13 16:41
@al-popa Could you, please, try to comment out line # 140 of file `examples/OpenGL3test.cxx` to obtain
`    //Fl_Gl_Window::draw(); // Draw FLTK child widgets.`
and report what you get? TIA.

**Comment by Albrecht-S** [comment] 2024-07-13 18:02
@ManoloFLTK As I wrote before I'm using an up-to-date Debian 12 (Bookworm) with Gnome/Wayland session (`GNOME Shell 43.9`) on real hardware.

I powered my Ubuntu VM up (`22.04.4 LTS`), checked out FLTK 1.4 from master and I'm seeing the same issues.
Screenshot from `Gnome/Xorg`, running `GNOME Shell 42.9`:
![OpenGL3test_Ubuntu-22 04_Gnome_Xorg](https://github.com/user-attachments/assets/a33ad83c-392e-4393-8e88-6e55e1b96851)

This screenshot shows the status after:
- launching the program (OpenGL is all black)
- switching Double Buffer OFF and ON again
- resizing the window.

I don't have a newer (24.04) Ubuntu system at present.

My previous tests were also executed on Debian 13 (Testing aka Trixie) with no difference.

**Comment by al-popa** [comment] 2024-07-13 18:17
@ManoloFLTK , commenting out line 140 `Fl_Gl_Window::draw();` does not improve the situation.

Here is a short movie recorded from my screen showing the final flickering of OpenGL buffer on double-buffered context.

https://github.com/user-attachments/assets/cf533201-eadc-4836-bd3a-f0d84e426429

**Comment by ManoloFLTK** [comment] 2024-07-14 07:57
OK. I have found what is, I believe, the only difference between how a GL3 context is created in FLTK 1.4 vs 1.3:
- FLTK 1.3 creates a "Core Profile", that is, something able to draw with GL3 and above only;
- FLTK 1.4 creates a "Compatibility Profile", that is,  something able to draw with GL3 and also with GL1 or GL2.
That is visible running OpenGL3test under FLTK 1.3:
<img width="409" alt="image" src="https://github.com/user-attachments/assets/a635e4eb-df3e-41c3-b07e-043b915465b2">

which says "Core Profile" contrarily to what all screen captures above, using 1.4, say.
FLTK 1.4 chose to create "Compatibility Profiles" to allow to place child FLTK widgets in Fl_Gl_Window's, a new in 1.4 feature that draws these widgets using GL1.

In my hands here, FLTK 1.4 works OK and I still don't understand why @al-popa and @Albrecht-S get bad results with the same FLTK 1.4 code.

@al-popa : Please, keep line 140 of file `examples/OpenGL3test.cxx` (`//  Fl_Gl_Window::draw(); `) commented out
as before and try to also comment out line # 288 of file `src/drivers/X11/Fl_X11_Gl_Window_Driver.cxx` to obtain
`//      GLX_CONTEXT_PROFILE_MASK_ARB, GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB,`
and report here what you get with program OpenGL3test.
This should make 1.4-using user code run the same GL code as 1.3-using one.

**Comment by al-popa** [comment] 2024-07-14 14:39
@ManoloFLTK , recompiled FLTK with your changes. Some improvements, but not working yet.

Now, OpenGL canvas in double-buffered mode is shown, but is not updated.

When the application starts in double-buffered mode, GL window is blank, switching to single-buffered mode works as expected. All these is the same as before. But when after single-buffered mode switch back to double-buffered mode, the last content of GL graphics is shown (previously it was all black), however graphics does not update with mouse input as in single-buffered mode.
![Double-buffered](https://github.com/user-attachments/assets/930c4f54-d016-46ee-803b-d1323e094a5f)

**Comment by ManoloFLTK** [comment] 2024-07-14 16:30
I see in the doc of how to use double-buffered OpenGL windows  in FLTK a recommendation to bracket the draw member function of Fl_Gl_Window's with two `glDrawBuffer()` calls. See 
﻿﻿[Making a Subclass of Fl_Gl_Window](https://www.fltk.org/doc-1.3/opengl.html#opengl_subclass)

It might make sense to apply this recommendation to program `OpenGL3test.cxx`. That means modifying the end of its `SimpleGL3Window::draw()` member function to obtain this :
```
#ifndef MESA
    glDrawBuffer(GL_FRONT_AND_BACK);   // <-- new stuff
#endif // !MESA
    glClearColor(0.08f, 0.8f, 0.8f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    if (shaderProgram) {
      GLfloat p[]={0,0};
      glUniform2fv(positionUniform, 1, (const GLfloat *)&p);
      glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
    }
    Fl_Gl_Window::draw(); // Draw FLTK child widgets.
#ifndef MESA
    glDrawBuffer(GL_BACK);  // <-- new stuff
#endif // !MESA
  }    // <--- closing brace of the SimpleGL3Window::draw() member function
```

When I do that here, I get a correct program (I get it also without any change).

**Comment by al-popa** [comment] 2024-07-14 16:56
Added the code with `glDrawBuffer(...)` as you recommended, with and without call `Fl_Gl_Window::draw();`, no changes.

**Comment by Albrecht-S** [comment] 2024-07-14 17:19
@al-popa wrote:
> Added the code with glDrawBuffer(...) as you recommended [...], no changes.

I can confirm this statement **_for both FLTK 1.3 (!) and 1.4_**. Note that I wrote above that I see the same malfunction when I build and run the 1.3 version of `examples/OpenGL3test.cxx` with the FLTK 1.3 library. Since there's no working Makefile I used `CMake` to build the example program. FWIW, the output of `fltk-config --use-gl --compile` with added `-lGLEW` works as well.

Switching to core profile as suggested above doesn't help either - which isn't surprising since I get the failure in branch-1.3 (top of git) as well.

The 1.3 version says in the text output widget:
```
Using GLEW 2.2.0
GL_VERSION=4.6 (Core Profile) Mesa 22.3.6
Shading Language Version=4.60
```
and when I add the suggested code `#ifndef MESA ... #endif // !MESA` together with print statements I get this output:
```
$ bin/examples/OpenGL3test 
MESA undefined: calling 'glDrawBuffer(GL_FRONT_AND_BACK);' # <- output as expected
MESA undefined: calling 'glDrawBuffer(GL_BACK);'           # <- output as expected
```

I wonder why I get **both**
- `(Core Profile) Mesa 22.3.6` ... **and**
- `MESA undefined`

I would expect `MESA` to be defined if it says `Mesa 22.3.6` ? I mean, the additional `glDrawBuffer()` calls shouldn't do any harm, but what if MESA is not defined elsewhere, where it **should** be? ...

But again, I know almost nothing about `OpenGL` and `Mesa`, I'm just trying to help testing.

**Comment by Albrecht-S** [comment] 2024-07-14 17:23
FWIW: Here's the diff I used in `branch-1.3`:
```diff
diff --git a/examples/OpenGL3test.cxx b/examples/OpenGL3test.cxx
index a1545505f..db014acb8 100644
--- a/examples/OpenGL3test.cxx
+++ b/examples/OpenGL3test.cxx
@@ -133,12 +133,20 @@ public:
     else if ((!valid())) {
       glViewport(0, 0, pixel_w(), pixel_h());
     }
+#ifndef MESA
+    printf("MESA undefined: calling '%s'\n", "glDrawBuffer(GL_FRONT_AND_BACK);");
+    glDrawBuffer(GL_FRONT_AND_BACK);   // <-- new stuff
+#endif // !MESA
     glClearColor(0.08, 0.8, 0.8, 1.0);
     glClear(GL_COLOR_BUFFER_BIT);
     glUseProgram(shaderProgram);
     GLfloat p[]={0,0};
     glUniform2fv(positionUniform, 1, (const GLfloat *)&p);
     glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
+#ifndef MESA
+    printf("MESA undefined: calling '%s'\n", "glDrawBuffer(GL_BACK);");
+    glDrawBuffer(GL_BACK);  // <-- new stuff
+#endif // !MESA
   }
   virtual int handle(int event) {
     static int first = 1;
```

**Comment by al-popa** [comment] 2024-07-14 18:06
Just to be clear: When I said FLTK 1.3 worked on the same graphics card, I used previous version of Debian, not the current one. That version was pure X11 with no Wayland at all. The current version is XWayland.

**Comment by ManoloFLTK** [comment] 2024-07-14 19:01
> Just to be clear:

I'm lost. @Albrecht-S sees the same malfunction with 1.3. What do you @al-popa see with 1.3 ?

**Comment by al-popa** [comment] 2024-07-15 05:23
I can confirm testing of @Albrecht-S with FLTK 1.3 in Debian 12 with XWayland. It does not work like 1.4, but except black OpenGL canvas it shows background color. Single-buffered mode works as expected.
![fltk-1 3](https://github.com/user-attachments/assets/22ab5812-85a5-4b19-bb53-e52c108aac98)

I will test FLTK-1.3 and 1.4 also in Debian 11 (previous version) with X11 only and report back.

**Comment by ManoloFLTK** [comment] 2024-07-15 06:43
OK. I had been searching for differences between 1.4 and 1.3 that could explain the issue. I understand now that's not where to search.

The question now is "Did OpenGL3test ever work in your setups?".

Support of OpenGL3 and above was introduced in FLTK on Oct 27, 2015. Program OpenGL3test.cxx was introduced in the same commit. No significant change to its source code in branch 1.3 occurred since. That code was released in FLTK 1.3.4.

Does OpenGL3test work for you with FLTK 1.3.4 ? It does for me.

**Comment by al-popa** [comment] 2024-07-15 09:52
Under Debian 11 (previous release) with X11 only both versions of FLTK (1.3.9 and 1.4-current) work flawlessly:
![Debian11-FLTK-1 3](https://github.com/user-attachments/assets/c5e0efa6-9ae3-448b-a660-d2d5409da502)
![Debian11-FLTK-1,4](https://github.com/user-attachments/assets/715792fe-bf94-4534-a52d-cbc242803340)

Graphics card: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]

**Comment by al-popa** [comment] 2024-07-15 10:11
Same system, same graphics card, Debian 12 (current) with XWayland no version (FLTK-1.3.9 or FLTK-1.4.current) works:
![Debian12-FLTK-1 3](https://github.com/user-attachments/assets/c8865e09-b53f-42cf-af71-62951c075f6c)
![Debian12-FLTK-1 4](https://github.com/user-attachments/assets/310945eb-8786-4ecb-b365-2cbede4f9e91)

**Comment by Albrecht-S** [comment] 2024-07-15 11:48
Oh, yes, same here on my old (Mint 20, based on Ubuntu 20.04) system:
![OpenGL3test_Mint-20_Gnome_Xorg](https://github.com/user-attachments/assets/147872d7-10e4-4de0-a8a2-eacd0935f68b)

It's a different GLEW version (2.1.0 vs 2.2.0) and a different Mesa version (21.2.6 vs 22.3.6) but **_it works as expected_**:
- on Gnome/Xorg (X11)
- on Gnome/Wayland (X11 + Wayland)
- same as above for the 1.3.9+ (git branch-1.3 current), obviously X11 only
- with 1.4 also with "Compatibility Profile") and FLTK widgets (no patch required)

> The question now is "Did OpenGL3test ever work in your setups?".

@ManoloFLTK Supposedly no, i.e. not on Debian Bookworm with current GLEW and Mesa. I see that you used among others a working system with:
- Ubuntu 24.04
- GL_VERSION=4.5 (Compatibility Profile)
- Mesa 24.0.5-1ubuntu1

Thus I believe this issue can be closed. It looks like a regression in one of the system libraries on Debian 12 and maybe related other systems (Ubuntu is known to be based on Debian too).

**_The remaining question is:_** Do we want to remove one of the `(FL_DOUBLE | FL_OPENGL3)` flags which the OP (@al-popa) mentioned (wherever that might be to do)?

However, since this is a demo program and there's no fault in FLTK I believe we should leave it as-is so users can see **if** this combination works on their systems.

**_Hence my proposal is:_** close this issue with a comment that this is a system issue and leave the FLTK code in `examples/OpenGL3test.cxx` as-is. We could also document this in the example program and hope that it will be fixed in a later OS release.

**Comment by al-popa** [comment] 2024-07-15 12:01
I also tend to think this is rather Debian XWayland issue than FLTK fault.

For my project I implemented the work-around from issue description, and it works for me.

**Comment by ManoloFLTK** [comment] 2024-07-15 14:48
> It looks like a regression in one of the system libraries on Debian 12 and maybe related other systems (Ubuntu is known to be based on Debian too).

All this still remains obscure because in my setup (Debian 11 or 12 or 13 or Ubuntu 22.04 or 24.04 in a VM on macOS arm64 architecture), OpenGL3test always runs OK both with 1.3.9 and 1.4.

@ggarra13 's report above gives hope the problem disappears on native Linux boxes running Ubuntu 24.04.

**Comment by ManoloFLTK** [comment] 2024-07-15 14:58
Summary of findings about this issue:
- the issue is not present in Debian 11
- the issue is not related to FLTK 1.4 because the same malfunctions are found with 1.3.9
- the issue appears with some setups using Debian 12, noticeably native Linux boxes with an AMD graphics card
- but not all setups because it's absent when Debian 12 is run inside a VM on Apple arm64 hardware
- the issue is reported to be absent with Ubuntu 24.04 with NVidia graphics
- the issue does not occur when the FLTK app is run as a Wayland client which provides a way out of the issue on setups where it occurs
- the issue does not occur if the FL_OPENGL3 flag is removed, which then prevents from drawing child FLTK widgets above the GL scene, a new feature of FLTK 1.4.

Closing the issue with this notice.

**Closed** 2024-07-15 14:59 UTC
Labels: bug, Platform: X11, Prio 3 - Moderate

**Comment by ManoloFLTK** [comment] 2024-07-17 15:43
@al-popa I expect commit 325004f to FLTK master should fix this issue.

**Comment by al-popa** [comment] 2024-07-18 05:48
Thank you @ManoloFLTK , with this fix, OpenGL3test works as expected.
![Working](https://github.com/user-attachments/assets/4c57d993-22dd-4597-9042-50365a457667)

The issue can be closed.

**Comment by Albrecht-S** [comment] 2024-07-18 13:35
Update, FTR: I just checked running OpenGL3test remotely on my Linux Mint 20 system, i.e. I'm running the executable **_on my old Mint system (`swift`)_** and using the **_Display on my current Debian Bookworm_** system.

- The old version before the patch worked well locally (display on `swift`)
- it displayed the GL scene on the remote display, however w/o the FLTK widgets (buttons)
- The new version after the patch (current: 3e9c77b62ab4748e2b4689c89a81561f69d0b1ba) worked perfectly well on the remote display, including the buttons.

![image](https://github.com/user-attachments/assets/a55816d5-a664-4908-bdb3-855e17ccafe4)

@ManoloFLTK Great job, thank you.

**Comment by Albrecht-S** [comment] 2024-07-18 13:37
@ManoloFLTK Minor remaining issue (compiler warning):
```
[2/7] Building CXX object src/CMakeFiles/fltk_gl.dir/drivers/X11/Fl_X11_Gl_Window_Driver.cxx.o
../../src/drivers/X11/Fl_X11_Gl_Window_Driver.cxx:197:12: warning: ‘int ctxErrorHandler(Display*, XErrorEvent*)’ defined but not used [-Wunused-function]
  197 | static int ctxErrorHandler( Display *, XErrorEvent * )
      |            ^~~~~~~~~~~~~~~
```

The `static` function `ctxErrorHandler()` appears to be obsolete now. Should it be removed?
