### ISSUE TITLE
Dynamic scaling broken in current revision?

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#239] opened 2021-06-18 08:36 UTC
Scaling with keys CTRL+/- behaves very strange (Ubuntu 20.04):
+ shows 90% but size of window increases. - shows 110% but size decreases.

**Comment by Albrecht-S** [comment] 2021-06-18 14:56
Yes, indeed. Thanks for the report. This is a regression introduced by the latest commit f94ed7116. I'm looking into it...

**Comment by Albrecht-S** [comment] 2021-06-18 16:53
OK, this should be fixed now. Hopefully. All feedback would be appreciated.

**Comment by bodomartin** [comment] 2021-06-18 17:03
the latest commit fixes the issue for me. Many thanks for the almost instant reply & fix

**Comment by Albrecht-S** [comment] 2021-06-18 17:10
Thanks for the quick feedback as well. 

My reaction was so quick because I was already working on it, and regressions are always taken seriously.

I'm closing this issue now again.

**Closed by Albrecht-S** 2021-06-18 17:10 UTC
Labels: bug
