### ISSUE TITLE
Wayland menus on Fullscreen now fail completely

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1070] opened 2024-09-12 19:30 UTC
**Describe the bug**
Wayland menus on Mutter used to display below their title.  A fix seems to have been put in place by @ManoloFLTK in commit 9b777cc01170a41ed33bb5f98223b8d7bbf5f2b8.  However it is that commit that makes it fail.

Now, I don't get any menus when going full screen on Ubuntu 24.04 LTS in my application and after selecting several menus I got (seemingly randomly):

`Fatal error no 3 in Wayland protocol: xdg_wm_base`

**To Reproduce**
[menubar.cxx.txt](https://github.com/user-attachments/files/16984916/menubar.cxx.txt)

**Expected behavior**
Menus should work properly.

**Screenshots**
Attached a movie with the problem:

[Grabación de pantalla desde 2024-09-12 16-32-25.webm](https://github.com/user-attachments/assets/ffbc815d-e9d1-42e5-b10a-d82fd733be67)

**FLTK Version**
1.4.0 master

**Operating System / Platform:**
Ubuntu 24.04 LTS

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Additional context**

**Comment by ggarra13** [comment] 2024-09-12 20:17
Also, git tag 2a87244ae3450496120917af1d95d8e833fa270a made it crash on start up (got fixed by the other late17cebc851bc55994c0e38dd3516e7f5f56f54808r menu commit).

To summarize:

Stable - 17cebc851bc55994c0e38dd3516e7f5f56f54808  (menus offset below title)
Crashing on start up - 2a87244ae3450496120917af1d95d8e833fa270a
Menus disappeared and can crash - 9b777cc01170a41ed33bb5f98223b8d7bbf5f2b8

**Comment by ManoloFLTK** [comment] 2024-09-13 05:51
Do you get the problem reported also with program  menubar.cxx.txt  as posted above? Here, I get no error with it.

Your report that 2a87244 creates a crash (presumably in your program) fixed by 9b777cc suggests the problem is somewhere else, because a change in the positionning of popup windows has nothing to do with the addition of a call to GL function glClearColor(). Please, post here the traceback at the reported crash point. Also, can you reproduce this crash with simple code, e.g., program shape with added Fl_Menu_Bar widget?

**Comment by ManoloFLTK** [comment] 2024-09-13 06:24
Please, also try applying this patch and report what effect you see on menubar + fullscreen window.
[menubar.patch.txt](https://github.com/user-attachments/files/16989421/menubar.patch.txt)

**Comment by ggarra13** [comment] 2024-09-13 07:03
menubar.cxx with and without patch does not show menus for me.

**Comment by ggarra13** [comment] 2024-09-13 07:03
Regarding the crash, I'll open two new issues, as I have two different crashes (one on start up and one on exit).

**Comment by ggarra13** [comment] 2024-09-13 07:24
Regarding the menus, the menus don't show up on the screen.  However, they are selected properly.

[Grabación de pantalla desde 2024-09-13 04-23-54.webm](https://github.com/user-attachments/assets/ad85022d-9d66-4c70-b26a-d4bc2cb441d1)

**Comment by ggarra13** [comment] 2024-09-13 07:35
Also, I forgot to mention, regarding the menus...

Fatal error no 3 in Wayland protocol: xdg_wm_base

does not give me a stack trace.  I get that only on my application.  I cannot reproduce it with menubar.cxx.

**Comment by ManoloFLTK** [comment] 2024-09-13 09:43
I have removed at 6aa5b70 my attempt to fix the Mutter issue with a menubar in a fullscreen window because it creates problems in your setup (NVidia driver again?).

**Comment by ManoloFLTK** [comment] 2024-09-13 10:17
I expect the problem is removed and you can close the issue.

**Comment by ggarra13** [comment] 2024-09-14 10:02
@ManoloFLTK So, what do you think is the real cause of the problem?  You suspected it was a Mutter issue, now an NVidia driver issue.  Your fix (that did not work on my setup) was indeed fixing the position of the menus (even if they were not displayed).  Without the fix, the menus show one "row" below and selection of them is also "offset" and I understand you can reproduce the issue even without an NVidia card.
Is Mutter, FLTK, NVidia or Wayland doing something wrong?

**Comment by ManoloFLTK** [comment] 2024-09-14 10:37
My fix at 9b777cc works well when I use Wayland in a VM. When I use Wayland in my MacBook booted to Ubuntu, I see the same bug as you if the menubar keeps its height of 30 when the window is fullscreen. So it's not a bug in FLTK, not a bug in Wayland in general because KWin and Weston don't have it. It's in Mutter, and somehow related with the graphics driver Mutter uses. There's another change I want to try.

**Comment by ManoloFLTK** [comment] 2024-09-14 13:12
> There's another change I want to try.

I've committed this change at 382d6b2 that works well here under native Ubuntu. Can you confirm it fixes the issue for you too?

**Comment by ggarra13** [comment] 2024-09-14 16:56
> Can you confirm it fixes the issue for you too?

Confirmed.  If you don't have any other comments, feel free to close the issue.

**Closed** 2024-09-14 18:48 UTC
Labels: fixed, Platform: Wayland
