### ISSUE TITLE
unexpected behavior when using Fl::use_high_res_GL(false)

### ISSUE THREAD

**Issue by andwj** [fltk/fltk#57] opened 2020-02-13 12:36 UTC
My application contains an Fl_Gl_Window with custom drawing code in the draw() method.  I have left Fl::use_high_res_GL() as disabled since updating the code to use pixel_w() and pixel_h() everywhere would be a big burden, especially because I cannot test it myself on MacOS -- the binary is compiled by a 3rd party.

So what is happening is that on a retina display, the Fl_Gl_Window is being drawn in only the bottom left quarter of the full size.  I suspect the reason is that glViewport() needs to be called with the "true" window size and not the w() and h() size.

Can somebody confirm if that is what the problem is, or could it be something else?

**Comment by ManoloFLTK** [comment] 2020-02-17 20:00
That is unexpected. An FLTK app is expected to run correctly on a retina display
if it does not use the pixel_w() and pixel_h() functions provided it does not call
Fl::use_high_res_GL(1).
You can, if you have access to a mac, verify that with FLTK demo apps such as 
cube or glpuzzle after commenting out their Fl::use_high_res_GL(1) statements and replacing
pixel_w() and pixel_h() by w() and h().

**Comment by ManoloFLTK** [comment] 2020-02-17 20:05
Sorry, I didn't mean to close this issue.

**Comment by mtolly** [comment] 2020-04-10 02:59
I have run into this on my own app -- it's a break in behavior when compiling on Catalina. A program compiled on prior macOS versions uses correct sizing, even when run on Catalina. Specifically the problem is in setting NSHighResolutionCapable to true (which is now also the default) but leaving use_high_res_GL disabled. If you explicitly set NSHighResolutionCapable to false the GL part draws okay, but the whole UI is not high-dpi.

SDL had the same problem, this is their fix: https://hg.libsdl.org/SDL/rev/46b094f7d20e

I am not a Cocoa/ObjC expert but I can see if I can try to put together a patch and test it soon. Otherwise if someone else wants to take a crack at it, I assume the right place to add the fix is here: https://github.com/fltk/fltk/blob/8a7d4c9/src/Fl_cocoa.mm#L2850-L2865

**Comment by ManoloFLTK** [comment] 2020-04-10 06:36
@mtolly: the FLTK equivalent of what you show from SDL has been committed
to branch 1.4 on 26 october 2019 (d1e346a).
Thus, and for several other reasons, it's necessary to use FLTK 1.4 to build on
macOS Catalina 10.15.

**Comment by mtolly** [comment] 2020-04-10 07:04
Ooh, thank you, I will give that a try. I was already using 1.4 but not quite the latest builds. Does that mean this issue can be closed, then?

**Comment by ManoloFLTK** [comment] 2020-04-15 07:27
If @mtolly could confirm it's OK with the current 1.4 branch, I'll close this issue.

**Comment by ManoloFLTK** [comment] 2020-05-12 09:23
Already solved.

**Closed by ManoloFLTK** 2020-05-12 09:23 UTC
