### ISSUE TITLE
OSX: cmake not creating wrapper scripts for test programs

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#115] opened 2020-07-21 21:05 UTC
When using cmake + make to build on OSX, only the xxx.app version of the test programs are created.
The wrapper scripts are needed too, vis a vis `fltk-config --post xxx`

(See also: pull request #111 )

**Comment by Albrecht-S** [comment] 2020-07-21 22:17
As Greg (@erco77) [mentioned here](https://github.com/fltk/fltk/pull/111#issuecomment-661561781) we need one small script per created app (bundle) like this one:
> This works:
```
#!/bin/sh
dir="`dirname \"$0\"`"
exec "$dir/utf8.app/Contents/MacOS/utf8" "$@"
```
where `utf8` was the test app I had created a script for.

Possible solution: use `configure_file` with a template like this and replace `utf8` (in the above example) with the app name. Should be easy to do.

Will look into it.

**Comment by Albrecht-S** [comment] 2020-07-21 22:20
One question though: you wrote "When using cmake + make", but I believe this should also be done when using CMake + Xcode. Is this true?

**Comment by erco77** [comment] 2020-07-21 22:57
`CMake + Xcode. Is this true?`

I can't answer to Xcode -- I never use it and know almost nothing about it.

> And do we also need a script for fluid?

I think so -- I don't currently see a wrapper in the bin directory for fluid, just the bin/fluid.app.
The build process must be running the binary in the MacOS subdir directly in order to build the test programs that use a .fl file.

**Comment by engelsman** [comment] 2020-07-21 23:20
Just a random observation, but...

During the development of the resize examples, when I used my original standalone "non-FLTK" makefile, I could run `./resize-example1` directly on my Mac without obvious problem, but once they were accepted and built using the full FLTK make system [not CMake] I was obliged to use `open resize-example1` which popped up a terminal window as well.

Obviously this was before Albrecht's update of the CMake system, and I haven't rebuilt with CMake yet anyway.

**Comment by Albrecht-S** [comment] 2020-07-22 09:43
> I don't currently see a wrapper in the bin directory for fluid, just the bin/fluid.app.
The build process must be running the binary in the MacOS subdir directly in order to build the test programs that use a .fl file.

@erco77 Assuming you build with CMake generator "Unix Makefiles" (is this the default under MacOS?)

Can you please do a test for me (in your **CMake build root**) and post the resultant part that deals with fluid, like this (on my Linux system with CMake + make):
```
build/make> make tabs               # make sure everything is up-to-date
build/make> rm test/tabs.cxx        # force fluid to rebuild
build/make> make VERBOSE=ON tabs    # rebuild with log
### intermediate output elided ###
[ 98%] Generating tabs.cxx, tabs.h
cd /git/fltk/master/build/make/test && ../bin/fluid -c /git/fltk/master/test/tabs.fl
```

I'm interested in the exact `fluid` command with all arguments to answer these questions:
- do they use `open` ?
- do they use the full path of the input file (as above) ?

I assume this will all be true but I'd appreciate to see the exact log. TIA.

**Comment by Albrecht-S** [comment] 2020-07-22 10:00
@engelsman Thanks, that's interesting.

> During the development of the resize examples, when I used my original standalone "non-FLTK" makefile, I could run ./resize-example1 directly on my Mac without obvious problem

Do you remember if you used `fltk-config --post` in your `Makefile`?

> but once they were accepted and built using the full FLTK make system [not CMake] I was obliged to use open resize-example1 which popped up a terminal window as well.

That's strange because we use `fltk-config --post` in `test/Makefile` for the resize examples.
- Is there a `resize-example1` shell script?
- If yes, what does `file resize-example1` tell us?
- What is its contents?
- Is there (also) a bundle (presumably `resize-example1.app`) ?

WRT console popup:
- Is it possible that you did a `Debug` build (maybe the default)
- What happens if you specify `-DCMAKE_BUILD_TYPE=Release` explicitly (or use the CMake GUI to edit this variable) ?

**Comment by ManoloFLTK** [comment] 2020-07-22 11:16
When using, under macOS, the fltk-config created by configure, a bundled app
can be obtained with fltk-config --compile.
fltk-config --post can be used to transform a straight executable into a macOS bundle.
Thus, what is the purpose of wrapper scripts of test programs?

**Comment by ManoloFLTK** [comment] 2020-07-22 11:50
With the current git source code, building under macOS runs well both with CMake + make and 
with CMake + Xcode:
Fluid and all test apps are correctly created as bundles, with their icon when one is defined, and with their
auxiliary files (e.g., the html file for help_dialog, the color list for colbrowser, the menu file for demo).
No wrapping scripts are created.

**Comment by Albrecht-S** [comment] 2020-07-22 12:02
> what is the purpose of wrapper scripts of test programs?

As a non-Mac-user (at least not yet) I can only say that **I was told** in #111 that it is more convenient in some cases to run the program with the wrapper script (as opposed to `open` the bundle) because

1. it's less typing (I'm not sure if that was one of the reasons)
2. the program can write to stdout and stderr
3. the current working directory (cwd) is well defined (is it?)
4. the user can use relative filenames in arguments to open files because of (3)

**Comment by Albrecht-S** [comment] 2020-07-22 12:11
[OT] @ManoloFLTK 

> all test apps are correctly created as bundles, with their icon when one is defined, and with their
auxiliary files (e.g., the html file for help_dialog, the color list for colbrowser, the menu file for demo).

The current code of `test/demo.cxx` as changed by me in a recent commit does no longer access the auxiliary (test and demo) files from the bundle but uses these files as on all other platforms in the new `/data` folder in the build root (under macOS with full path names).

I did this to unify the code and the user (developer, tester) experience and for some other reasons. As a consequence we could IMHO remove the extra files from the bundles (less size and less CMake code). Note that `help_dialog` (built by CMake) does not (yet) show the images, but this is a known issue I would like to address separately. This **should** also be **the same on all platforms**.

BTW, can you please take a look at the macOS specific code (and comments) in `main()` of `test/demo.cxx`? If you have questions about all the changes, please refer to the long comment at the beginning of the file. If there's anything to discuss we should probably go to fltk.coredev or a separate issue. Your help would be greatly appreciated! Thanks.

**Comment by Albrecht-S** [comment] 2020-07-22 12:45
Here's another thought for the wrapper script to simplify it and its creation. Basically the script would be free from the application name so a user could easily copy the wrapper script for any bundle. Can someone with a Mac please test the following script?
```
#!/bin/sh
prog="`basename \"$0\"`"
dir="`dirname \"$0\"`"
exec "$dir/$prog.app/Contents/MacOS/$prog" "$@"
```
Please copy it "besides" any of the created bundles with the correct app name, make it executable, and run it, e.g.
```
cat > hello
(copy / paste above script, terminate with ctrl/d or whatever under macOS)
chmod 755 hello
./hello
```
Note: I created a "fake bundle" with a slightly modified `fltk-config --post hello` on my Linux system and the script above works for me on Linux:
```
bin>
bin>ls -d hello*
hello  hello.app
bin>file hello
hello: POSIX shell script, ASCII text executable
bin>cat hello
#!/bin/sh
prog="`basename \"$0\"`"
dir="`dirname \"$0\"`"
exec "$dir/$prog.app/Contents/MacOS/$prog" "$@"
bin>tree hello.app/
hello.app/
└── Contents
    ├── Info.plist
    └── MacOS
        └── hello

2 directories, 2 files
bin>file hello.app/Contents/MacOS/hello 
hello.app/Contents/MacOS/hello: ELF 64-bit LSB shared object, ...
bin> ./hello
```
Please report if the wrapper script above works. This would simplify the CMake generation and we could also simplify `fltk-config` a little bit. An additional effect would be that users can just copy an existing script under another name for another app (bundle).

**Comment by ManoloFLTK** [comment] 2020-07-22 15:55
> > what is the purpose of wrapper scripts of test programs?
> 
> As a non-Mac-user (at least not yet) I can only say that **I was told** in #111 that it is more convenient in some cases to run the program with the wrapper script (as opposed to `open` the bundle) because
> 
>     1. it's less typing (I'm not sure if that was one of the reasons)
> 
>     2. the program can write to stdout and stderr
> 
>     3. the current working directory (cwd) is well defined (is it?)
> 
>     4. the user can use relative filenames in arguments to open files because of (3)

Properties 2, 3 and 4 above are also obtained if the executable program inside the bundle
is run as a program is run under Unix.

**Comment by ManoloFLTK** [comment] 2020-07-22 16:00
The simplified wrapper script proposed by Albrecht works well
under macOS.

**Comment by ManoloFLTK** [comment] 2020-07-22 16:23
> The current code of `test/demo.cxx` as changed by me in a recent commit does no longer access the auxiliary (test and demo) files from the bundle but uses these files as on all other platforms in the new `/data` folder in the build root (under macOS with full path names).
> 
OK. I discover this. As you wrote, it's necessary to remove auxiliary files from the bundles, then.

> 
> BTW, can you please take a look at the macOS specific code (and comments) in `main()` of `test/demo.cxx`? If you have questions about all the changes, please refer to the long comment at the beginning of the file. If there's anything to discuss we should probably go to fltk.coredev or a separate issue. Your help would be greatly appreciated! Thanks.

The macOS-specific code is correct. But I'm not aware the
"the actual location of the app has a randomized path".
[I believe memory addresses of executables and their symbols are
randomized across runs to enhance security].
Running the demo program, for example, both in debug
and release CMake builds, argv[0] has this value
......../build/bin/Release/demo.app/Contents/MacOS/demo
(the variable path to the build directory is not shown).

**Comment by Albrecht-S** [comment] 2020-07-22 16:24
> The simplified wrapper script proposed by Albrecht works well under macOS.

@ManoloFLTK Thanks for confirmation!

> Properties 2, 3 and 4 above are also obtained if the executable program inside the bundle
is run as a program is run under Unix.

Honestly, that's IMHO the whole purpose of the wrapper script. It does nothing but run the executable inside the bundle directly w/o having to know the bundle structure and typing the long command line to execute the program inside the bundle.

**Comment by Albrecht-S** [comment] 2020-07-22 16:50
@ManoloFLTK Thanks again for your info.

> ... it's necessary to remove auxiliary files from the bundles

What exactly do you mean? I don't think it's **necessary** to "remove" them (the bundles work despite they are there), but it's **useless to add them** to the bundles in the first place and we could remove that step from `test/CMakeLists.txt`. Did you mean that?

> The macOS-specific code is correct. But I'm not aware the "the actual location of the app has a randomized path". ... Running the demo program, for example, both in debug and release CMake builds, argv[0] has this value ......../build/bin/Release/demo.app/Contents/MacOS/demo (the variable path to the build directory is not shown).

So, as long as the path is a valid path in the file system (i.e. the not shown part is not randomized) the demo program should work entirely without this macOS specific code in `main()` which does, as far as I understand it, nothing but finding the bundle file name which would IMHO be the part of the path shown by you up to `/demo.app`.

The new code looks only for the `/bin/` directory and cuts the path off at that point. Hence the macOS version of demo **should** IMHO also work without this special code in main.

Can you please test if this is correct and we can **remove that code** entirely?

*Side note: there's one known issue with the new code: I was too lazy to check for the **last** occurrence of `/bin/` in the path which would be correct. The code would fail if someone had the build directory in a path that contains `/bin/`. At the time of writing the code I was not aware of a function like `strrchr()` for strings (`strrstr()` ?) which would be the better choice. If necessary we could fix this with some more lines of code.*

PS: I just moved that code and the comment about the randomized path from one place (in function `dobut()`) to another place (in `main()`), I didn't actually change it. Maybe the author meant the entire part "/Release/demo.app/Contents/MacOS/demo" to be "randomized" (in the sense that we don't know it) because that's what the user who creates the build and Xcode do (yes, I know a part of it is due to the bundle structure).

**Comment by Albrecht-S** [comment] 2020-07-22 16:53
Addendum: I wrote:
> Can you please test if this is correct and we can remove that code entirely?

Can you also assure that this is true for all supported macOS versions? Is there a possibility that this statement in the comment (a randomized path in `argv[]`) was true for some earlier macOS versions?

**Comment by erco77** [comment] 2020-07-22 17:00
> @ManoloFLTK wrote:
> As a non-Mac-user (at least not yet) I can only say that I was told in #111 that it is more convenient in some
> cases to run the program with the wrapper script (as opposed to open the bundle) because
> 
> 1. it's less typing (I'm not sure if that was one of the reasons)
> 2. the program can write to stdout and stderr
> 3. the current working directory (cwd) is well defined (is it?)
> 4. the user can use relative filenames in arguments to open files because of (3)

Another useful feature with the wrapper is the program blocks while running so it can return an exit code to the caller.
This makes it useful for running the fltk program from a script that waits for completion and a success/fail indication.
I believe we make use of this sort of thing when running fluid from the Makefile in the test directory to convert .fl -> .cxx/.H

**Comment by Albrecht-S** [comment] 2020-07-22 17:01
@ManoloFLTK Thanks for your help so far.

I think it's safe to add the working wrapper script (as you confirmed) to the CMake build under macOS and I'm going to do that. Looking into the **CMake files** now...

While I'm at it I will also remove the addition of the auxiliary files to the bundles.

I'd appreciate though if you could confirm that the macOS specific code in test/demo.cxx:main() is not necessary (because I can't do it) and remove it. TIA.

**Comment by engelsman** [comment] 2020-07-22 17:39
> @engelsman Thanks, that's interesting.
> 
> > During the development of the resize examples, when I used my original standalone "non-FLTK" makefile, I could run ./resize-example1 directly on my Mac without obvious problem
> 
> Do you remember if you used `fltk-config --post` in your `Makefile`?

@Albrecht-S 
Here's a snippet of the basics of my "non-FLTK" makefile:

```
FLTKCONFIG = ../../fltk-config

CXX        = $(shell $(FLTKCONFIG) --cxx)
DEBUG      = -g
CXXFLAGS   = $(shell $(FLTKCONFIG) --cxxflags) -I.
LDFLAGS    = $(shell $(FLTKCONFIG) --ldflags)
LDSTATIC   = $(shell $(FLTKCONFIG) --ldstaticflags)
LINK       = $(CXX)

ifeq '$(OS)' "Windos_NT"
EXEEXT = .exe
endif

TARGETS = resize-example1$(EXEEXT) ...

OBJS_example1 = resize-example1.o resize-arrows.o

all:    $(TARGETS)

.SUFFIXES:      .o .cxx
%.o:    %.cxx
        $(CXX) $(CXXFLAGS) $(DEBUG) -c $<

resize-example1$(EXEXT):        $(OBJS_example1)
        $(LINK) -o resize-example1 $(OBJS_example1) $(LDSTATIC)
```


> > but once they were accepted and built using the full FLTK make system [not CMake] I was obliged to use open resize-example1 which popped up a terminal window as well.
> 
> That's strange because we use `fltk-config --post` in `test/Makefile` for the resize examples.
> 
>     * Is there a `resize-example1` shell script?
>     * If yes, what does `file resize-example1` tell us?
>     * What is its contents?
>     * Is there (also) a bundle (presumably `resize-example1.app`) ?

There's no shell script, or related .app bundle, just a resize-example1 executable.
```
duncan$ file resize-example1
resize-example1: Mach-O 64-bit executable x86_64
```

> WRT console popup:
>     * Is it possible that you did a `Debug` build (maybe the default)
>     * What happens if you specify `-DCMAKE_BUILD_TYPE=Release` explicitly (or use the CMake GUI to edit this variable) ?

As I said, I rebuilt the test/resize-examples simply using 'make' in the top level directory after the PR was merged and pushed to master. Does that default to a Debug build?

I still have to test rebuilding using CMake, but that's not going to happen before the weekend at the earliest

Hope this helps.

**Comment by Albrecht-S** [comment] 2020-07-22 18:21
@engelsman Thanks for your info.
> I rebuilt the test/resize-examples simply using 'make' in the top level directory after the PR was merged and pushed to master. Does that default to a Debug build?

That depends on what build type you configured before. Note: It's only a wild guess that macOS would also open a console as FLTK programs do under Windows, I don't know.

It is at least a FLTK-style make which runs (AFAICT) `fltk-config --post` on the resize example progs. Therefore you should now have the wrapper script and a bundle for all resize examples. That's what I can tell you. Is this the case?

What macOS or our FLTK programs (under macOS) do (WRT console window) I can't tell, don't ask me. @ManoloFLTK or @erco77 certainly know that better.

**Summary of current status under macOS:**

- configure/make: bundle + wrapper script (both created using `fltk-config --post` in Makefile)
- CMake: bundle only, currently no wrapper -- until I get this done ;-)

After this the behavior of the build with configure/make vs. CMake should be the same -- that's what I want to achieve and obviously Greg's intention with this GitHub Issue (#115).

PS: all CMake builds should be the same, no matter what build system they use (Xcode, Ninja, Make, Eclipse, whatever). If not, then that's a bug, please report it (unless impossible to do with the build system). If the latter it should be documented. Period.

**Comment by erco77** [comment] 2020-07-22 18:31
> ifeq '$(OS)' "Windos_NT"

Is that a typo? Windos -&gt; Windows?

**Comment by Albrecht-S** [comment] 2020-07-22 19:24
I always thought it's "WinDOS", is that wrong? ;-)

**Comment by engelsman** [comment] 2020-07-22 21:07
> > ifeq '$(OS)' "Windos_NT"
> 
> Is that a typo? Windos -> Windows?

Well, now you've got me! To be perfectly honest, I don't remember where this line came from. I'm typically doing this hacking late at night when I should really be in bed.

At home I'm on a Mac and at work I'm on Linux, so I can only imagine that I copied this from somewhere else in the hope that it would help other people to test on Windows, e.g. somewhere like https://stackoverflow.com/questions/714100/os-detecting-makefile, but I have absolutely no recollection of doing so now.

In any case, it does look like a typo :-(

**Comment by Albrecht-S** [comment] 2020-07-23 00:21
The macOS bundle wrapper scripts are now created during the CMake configure pass (332003cd136f39c1f42d344efecebaf976c5955b).

I also fixed the missing images in `test/help_dialog` when built with CMake (f357f4311c6faedcb87f40144b83e2219538386c) and "removed" the no longer used auxiliary (test) files from the test program bundles as discussed recently (0015e64671a3c96a3600c23fa62935f981f78a1e).

I'd appreciate tests and feedback particularly (but not only) on macOS. Thanks.

PS: in case anybody wonders: the wrapper scripts are only created under macOS.

**Comment by Albrecht-S** [comment] 2020-07-23 00:24
Oh, I see: we talked about a wrapper script for fluid - this is **not yet done**. Will look into this tomorrow.

**Comment by ManoloFLTK** [comment] 2020-07-23 07:35
I have simplified the macOS-specific code in main() of demo.cxx and committed it.

I have tested CMake building under macOS after the last committed changes.
It's OK with the Makefile generator.
There's a small inconsistency with the Xcode generator:
test application bundles are put in <build-directory>/bin/Debug/ or in
<build-directory>/bin/Release/ whereas wrappers are put in 
<build-directory>/bin/. Wrappers therefore don't work with the Xcode
generator.

A yet simpler way to create the wrappers is to create a link
to the executable file inside the bundle:
demo.app/
   Contents/
      MacOS/
          demo

ln -s demo.app/Contents/MacOS/demo  .

**Comment by Albrecht-S** [comment] 2020-07-23 09:20
@ManoloFLTK Thank you very much for testing and for your quick feedback.

> There's a small inconsistency with the Xcode generator: test application bundles are put in /bin/Debug/ or in
/bin/Release/ whereas wrappers are put in /bin/.

Oh, yes, basically I should've known that but I didn't think of it when I wrote the code. I believe we can find the real dir in `CMake` but I need to investigate that.

> A yet simpler way to create the wrappers is to create a link to the executable file inside the bundle:

I'll consider this as well, but currently the scripts are written (copied) during the configure phase. Although it is possible *I wouldn't like*  to create symlinks to not (yet) existent files.
```
build> ln -s demo.app/Contents/MacOS/demo .
build> ls -l demo
lrwxrwxrwx 1 xxx xxx 28 Jul 23 10:54 demo -> demo.app/Contents/MacOS/demo
build> file demo
demo: broken symbolic link to demo.app/Contents/MacOS/demo
```

A more complicated alternative would be to do it after the build, which should also be possible.

Another point I didn't take care of (yet) is to **install** the scripts. I'm not sure what `make install` in a classic (`autoconf/make`) build would do. Would the classic `make install` install the wrappers?

I also did not yet think of `make clean`, `ninja clean`, Xcode's (or any other build system's) "clean" function if that exists.

It turns out it's more complicated than anticipated.

What do other Mac users think about
- creating links instead of wrapper scripts as such?
- the "broken symbolic link" problem?

The latter would last only during the build or if a build does not complete because all links would be created during the configure phase before the first program is built.

After all the fact that there are two different objects, the bundle + the wrapper or link, isn't this contrary to the "macOS bundle idea" that everything related to an app is only one "object" that's treated as a whole in finder?

Comments welcome.

**Comment by ManoloFLTK** [comment] 2020-07-25 10:48
Yes, the bundle + the wrapper or link is contrary to the bundle principle where everything is inside.
But it does no harm.

**Comment by Albrecht-S** [comment] 2020-07-25 14:11
FTR: please don't expect progress during the next days (maybe two weeks), I'll be pretty busy and I don't have a directly applicable idea about how to proceed with this. Maybe I need to activate my old Mac (or buy a new one) first before I can proceed. So please don't hold your breath.

Other contributions welcome, of course.

**Comment by Albrecht-S** [comment] 2020-08-18 14:42
I committed a fix (fcd5239adc468b58a130356be79e6e741689e6b0) so the bundle wrappers should now be created where the app bundles are, e.g.
```
# Makefiles:
bin/hello.app
bin/hello # wrapper
# Xcode:
bin/Debug/hello.app
bin/Debug/hello # wrapper
# etc. (Release, ...)
```
Notes:
- this commit is in current master where the test programs are directly in `bin/`
- it will automatically "move" to `bin/test` if this change gets committed (WIP)
- it will also apply to the example programs in `bin/examples` (WIP)
- it **does** also apply to `fluid`
- the scripts are copied "post build" (not during the configuration phase as before)
- still to do: wrapper "installation" with `make install` or equivalent

@ManoloFLTK, @erco77, @imaclmaca, @engelsman :
Test reports and confirmations appreciated ...

**Comment by engelsman** [comment] 2020-08-19 18:33
Sorry Albrecht, but I haven't really been following the ins and outs of this issue.

However, I've just pulled your latest commit, created a new build directory, and rebuilt using CMake / make on MacOSX 10.15.6 Catalina. The only thing I reconfigured in ccmake was the install path.

What I can see in build:
```
Duncans-MBP:build duncan$ ls
CMakeCache.txt			UseFLTK.cmake			fluid
CMakeDoxyfile.in		bin				install_manifest.txt
CMakeDoxygenDefaults.cmake	cmake_install.cmake		jpeg
CMakeFiles			cmake_uninstall.cmake		lib
FL				config.h			png
FLTK-Functions.cmake		data				src
FLTK-Targets.cmake		documentation			test
FLTKConfig.cmake		etc
Makefile			fltk-config
```

I was a bit confused when I looked into build/test:
```
Duncans-MBP:build duncan$ ls test
CMakeFiles		fast_slow.cxx		mandelbrot_ui.h		tabs.cxx
CubeViewUI.cxx		fast_slow.h		preferences.cxx		tabs.h
CubeViewUI.h		inactive.cxx		preferences.h		tree.cxx
Makefile		inactive.h		radio.cxx		tree.h
checkers_pieces.cxx	keyboard_ui.cxx		radio.h			valuators.cxx
checkers_pieces.h	keyboard_ui.h		resize.cxx		valuators.h
cmake_install.cmake	mandelbrot_ui.cxx	resize.h
```
but then I found all of the test executables and wrappers in build/bin:
```
Duncans-MBP:build duncan$ ls bin
CubeView		doublebuffer.app	label.app		resize-example3c.app
CubeView.app		editor			line_style		resize-example4a
adjuster		editor.app		line_style.app		resize-example4a.app
adjuster.app		fast_slow		list_visuals		resize-example4b
animated		fast_slow.app		list_visuals.app	resize-example4b.app
animated.app		file_chooser		mandelbrot		resize.app
arc			file_chooser.app	mandelbrot.app		resizebox
arc.app			fltk-config		menubar			resizebox.app
ask			fltk-versions		menubar.app		rotated_text
ask.app			fltk-versions.app	message			rotated_text.app
. . .
```

Just running bin/CubeView or bin/image from the Terminal command line seems to work without creating an additional background window, and bin/demo allows me to click on the others, such as the resize-examples :-)
I haven't noticed any missing resources or icons, but then I've only run a few of the tests.
Note that I haven't tried to click on anything via the Finder...

How that helps?

**Comment by imaclmaca** [comment] 2020-08-19 21:01
On 18 Aug 2020, at 15:42, Albrecht Schlosser wrote:
> 
> 
> I committed a fix (fcd5239) so the bundle wrappers should now be created where the app bundles are, e.g.
> 
> # Makefiles:
> bin/hello.app
> bin/hello # wrapper
> # Xcode:
> bin/Debug/hello.app
> bin/Debug/hello # wrapper
> # etc. (Release, ...)
> 
> Notes:
> 
> 	• this commit is in current master where the test programs are directly in bin/
> 	• it will automatically "move" to bin/test if this change gets committed (WIP)
> 	• it will also apply to the example programs in bin/examples (WIP)
> 	• it does also apply to fluid
> 	• the scripts are copied "post build" (not during the configuration phase as before)
> 	• still to do: wrapper "installation" with make install or equivalent
> @ManoloFLTK, @erco77, @imaclmaca, @engelsman :
> Test reports and confirmations appreciated ...


OK - gave that a spin (on my increasingly ancient 10.13.6 system) and it seemed to go fine - the executables I expected to find were all present in the <blah>/build/bin folder (including fluid) and all appear to have working wrapper scripts.

So I think that’s all good.

FWIW, I’ve also been mulling over the whole test/examples folder question, and I think I’m now persuaded that we should go for the .../build/bin/test and .../build/bin/examples option (presumably with fluid in .../build/bin perhaps? Or in .../build/bin/fluid/ ?)

I wasn’t sure what was best in that regard, but on balance I think that way perhaps is...


Also: in an almost entirely unrelated matter: I was using the fltk-config that cmake generates this evening, and I find that it doesn’t return anything for the "fltk-config --optim” case, it is just blank.

The autoconf version says:

ian$ ./fltk-config --optim
-Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k -fno-exceptions -fno-strict-aliasing
ian$ ./fltk-config --cxx
g++


The cmake one says:

ian$ ./fltk-config --optim

ian$ ./fltk-config --cxx
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++


I do not know if this is just that the fltk-config is not set, or if the build really is running without any optimisations enabled!

**Comment by Albrecht-S** [comment] 2020-08-20 13:26
> I was a bit confused when I looked into build/test:
> ...
> but then I found all of the test executables and wrappers in build/bin:

@engelsman Thanks, this all looks good. As you may have noticed the folders `test`, `fluid`, and in the future `examples` as well, contain build files created by CMake. In `test` you can see, for instance, all the source and header files generated by `fluid` from their respective `.fl` files.

Thanks also for all the other test results. And yes, it helps.

**Comment by Albrecht-S** [comment] 2020-08-20 15:13
> FWIW, I’ve also been mulling over the whole test/examples folder question, and I think I’m now persuaded that we should go for the .../build/bin/test and .../build/bin/examples option (presumably with fluid in .../build/bin perhaps? Or in .../build/bin/fluid/ ?)

@imaclmaca Thanks for your test results as well, and also for your feedback regarding the build folder structure. I believe the following found consensus:
```
bin/fltk-config
bin/fluid
bin/test (all test programs)
bin/examples (all example programs)
```

I'm still working on some details but I believe that I can commit the final result soon.

Note that for multi configuration setups (Visual Studio, Xcode, maybe more) the executables and the wrappers on macOS will be in a subdirectory `Debug` or `Release` etc. (the build type as selected by the user). This way such multi config setups can build more than one configuration in one build folder.

**Comment by ManoloFLTK** [comment] 2020-08-24 10:10
I ran under macOS CMake + Xcode and CMake + makefile from the current 1.4 master and all builds
are OK: examples are built, wrappers are where they should, program icons are OK, support files
are found when the test programs are run via demo. That's excellent.

I also tried the fltk-config output by CMake and notice it expects libraries in /usr/local/lib.
I wonder if that's convenient. Don't we aim to allow to have multiple versions of FLTK
in different locations on disk? Shouldn't BUILD-DIR/bin/fltk-config rather use the libraries from BUILD-DIR/lib/ ?

**Comment by Albrecht-S** [comment] 2020-08-24 12:49
@ManoloFLTK Thanks for your test results, this is very much appreciated.

> I also tried the fltk-config output by CMake and notice it expects libraries in /usr/local/lib. ... Shouldn't BUILD-DIR/bin/fltk-config rather use the libraries from BUILD-DIR/lib/ ?

There are two different `fltk-config` files in the build folder:
- build/bin/fltk-config
- build/fltk-config

The former is prepared to be installed in the target directory, obviously `/usr/local` in your case.

The latter is the one you should use if you want to build and link programs with the build directory. This works fine with standard (single config) builds like `Makefiles` but I'm pretty sure it won't work with multi config builds like `Xcode` and `Visual Studio` because the libs would presumably be in `lib/Debug` folders (or `lib/Release`, resp.).

@imaclmaca, @ManoloFLTK : I opened another issue (#129) for `fltk-config` improvements. Please add further comments and observations regarding `fltk-config` there. TIA.

**Comment by Albrecht-S** [comment] 2020-08-24 13:10
Thanks to all who contributed comments and test results. This issue is now fixed and I'm going to close it.

**Closed by Albrecht-S** 2020-08-24 13:10 UTC
Labels: CMake, enhancement, fixed
