### ISSUE TITLE
Writing on the file chooser dialog prepends the current directory path

### ISSUE THREAD

**Issue by rodarima** [fltk/fltk#1004] opened 2024-07-02 19:18 UTC
**Describe the bug**

Typing in the file chooser dialog causes the current directory to be appended to every key.

**To Reproduce**

Compile the following program, execute it, click on "Select file" and imediately after that type "hello". Notice that to reproduce it the current directory is changed to an empty temporary directory, so the first keystroke never matches a potential file, which won't reproduce it.

```c++
/* Build with: fltk-config --compile test.cpp */
#include <cstdlib>
#include <unistd.h>

#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Chooser.H>

void cb_file_select(Fl_Widget *o, void *v)
{
    fl_file_chooser("Choose a file", NULL, NULL);
}

int main (int argc, char ** argv)
{
    char buf[] = "/tmp/tmpdir.XXXXXX";
    char *tmpdir = mkdtemp(buf);
    if (tmpdir == NULL) {
        perror("mkdtemp failed");
        return 1;
    }

    if (chdir(tmpdir) != 0) {
        perror("chdir failed");
        return 1;
    }

    Fl_Window *window = new Fl_Window(300, 300, 200, 200, "Foo");

    Fl_Button *button = new Fl_Button(60, 40, 80, 40, "Select file");
    button->callback(cb_file_select);
    window->end();

    window->show(argc, argv);

    return(Fl::run());
}
```

EDIT: Fix outdated version of the reproducer program that was using /tmp instead of creating a new temporary directory.

**Expected behavior**
The current directory should only be appended once.

**Screenshots**
![path](https://github.com/fltk/fltk/assets/3866127/be75e492-22c9-4a1b-94ca-d5f66f1d741e)

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.3.9
 - Installed as package from: Arch Linux (fltk 1.3.9-1 x86_64)

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**
This was reported to the [Dillo browser mailing list](https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/thread/JZGTIK6FQIIOXVENV63N6SWJQU7BO25Z/#UTV3I55HGTZ656R6D2BDUPD4RZV2WKJZ)

**Comment by Albrecht-S** [comment] 2024-07-02 21:17
Thanks for the report. Issue confirmed with FLTK 1.4.0 (Git master).

**Comment by Albrecht-S** [comment] 2024-07-02 21:36
The issue can also be observed with FLTK's test/filechooser.cxx

**Comment by Albrecht-S** [comment] 2024-07-02 22:58
Quick investigation shows that the culprit is somewhere near https://github.com/fltk/fltk/blob/b5516449a687f8493e5fd9682511e9611a5b4fb7/src/Fl_File_Chooser2.cxx#L795 or more precisely some lines above this statement.

These are intermediate results only:

Whenever the filename is considered to be "relative" the current directory is prepended to ...
`// Make sure we have an absolute path...` (line 791).

When that's done the `insert_position()` is moved to the beginning of the filename/path. The next keyboard entry that's not a '/' is put at the first byte of the string, the filename is again considered relative, ... and so on.
The following minimal patch for FLTK 1.4.0 mitigates the issue by moving the `insert_position()` to the end of the string:
```diff
diff --git a/src/Fl_File_Chooser2.cxx b/src/Fl_File_Chooser2.cxx
index 56cce9950..e82e0c450 100644
--- a/src/Fl_File_Chooser2.cxx
+++ b/src/Fl_File_Chooser2.cxx
@@ -794,6 +794,7 @@ Fl_File_Chooser::fileNameCB()
   if (dirIsRelative) {
     fl_filename_absolute(pathname, sizeof(pathname), filename);
     value(pathname);
+    fileName->insert_position((int)strlen(pathname));
     fileName->mark(fileName->insert_position()); // no selection after expansion
   } else if (filename != pathname) {
     // Finally, make sure that we have a writable copy...
```

Note: in FLTK 1.3 (branch-1.3) the related code is about at line 841 of the same file (`src/Fl_File_Chooser2.cxx`).

This is probably not a full solution of the issue but it avoids parts of the unwanted behavior. The given test program works fine with this patch.

**_Remaining issue:_** whenever the user moves the cursor (insert_position) to the start of the filename and enters a non-'/' character the current directory is still prepended - but this is more obvious to the user, although it's still somewhat unexpected.

Some other dev who's more familiar with this file chooser stuff or willing to dig deeper may find a better solution. I'm leaving this open for now, I just wanted to help with my results.

@rodarima Can you please test with this patch in FLTK 1.4 or a similar one in 1.3 (`s/insert_position()/position()/` IIRC) and confirm that this works for you (and your use case in Dillo)? Thanks in advance.

**Comment by Albrecht-S** [comment] 2024-07-04 14:36
I committed a slightly modified fix for this issue in `master` (ecb3c9c6fca1af050b80f6ea94e03852bd51765b) and backported this fix to `branch-1.3` as well (f34719851ef6d9632d120c1f9e96b497694701ec). The latter will be in the next release 1.3.10 (no release date yet).

The new behavior puts the insert point (insert_position()) at the end of the string as the user would usually expect. This avoids the erroneous behavior.

@rodarima Please confirm that this fixes the issue and close it. I'm leaving this issue open for about one week and will close it if it is not confirmed.

**Comment by rodarima** [comment] 2024-07-04 19:58
Thank you!

It seems to be working fine for me with the above test using the 1.3 branch:

![ok](https://github.com/fltk/fltk/assets/3866127/af5002d5-6102-4f76-8d93-644802f67fed)

I also mailed the OP to test it with Dillo too.

In Dillo we are using the whole path, so it all gets selected. But when a new character is written, it is appended to the *current directory* instead of rewriting the whole path. Not sure it this is the desired effect, but here is another reproducer:

```c++
/* Build with: fltk-config --compile test.cpp */
#include <cstdlib>
#include <unistd.h>

#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Chooser.H>

void cb_file_select(Fl_Widget *o, void *v)
{
    fl_file_chooser("Choose a file", NULL, (char *) v);
}

int main (int argc, char ** argv)
{
    char buf[] = "/tmp/tmpdir.XXXXXX";
    char *tmpdir = mkdtemp(buf);
    if (tmpdir == NULL) {
        perror("mkdtemp failed");
        return 1;
    }

    if (chdir(tmpdir) != 0) {
        perror("chdir failed");
        return 1;
    }

    if (mkdir("foo", 0755) != 0) {
        perror("mkdir failed");
        return 1;
    }

    char foo[1024];
    sprintf(foo, "%s/foo/bar.txt", buf);

    Fl_Window *window = new Fl_Window(300, 300, 200, 200, "Foo");

    Fl_Button *button = new Fl_Button(60, 40, 80, 40, "Select file");
    button->callback(cb_file_select);
    button->user_data(foo);
    window->end();

    window->show(argc, argv);

    return(Fl::run());
}
```

I would expect the complete path to be changed, as it is all selected.

In any case, for Dillo it may make more sense to instead chdir() to the downloads directory, then open the file dialog so that only the filename is selected and then restore the current directory. This way typing a character will only replace the filename.

**Comment by rodarima** [comment] 2024-07-04 20:16
I tested changing the directory before and using the file name in Dillo, like this:
```c++
chdir("/tmp/empty");
fl_file_chooser("Choose file", NULL, "foo.txt", 1)
```

But still the whole path is selected. Typing a single character will replace the filename only (which is what I would want), but I would expect only the filename to be selected.

Typing / causes the whole path to be erased, including the newly inserted /.

**Comment by Albrecht-S** [comment] 2024-07-05 12:42
@rodarima I'm trying to explain what happens and why it is as it is...

1. This special FLTK file chooser has IIRC been introduced in FLTK 1.1 (about 2001 or even earlier) and didn't get (m)any behavioral changes since then. Its internal programming is pretty complicated due to the fact that it reacts on any key press and **_tries to guess what the user wants to achieve_**. This peculiar behavior is even more complicated since it uses both the directory and filename part in one input field as you noticed.
2. The current behavior when the (full) input field is selected is - at least mostly - consistent: if you type one character...
  - the entire string is removed (¹)
  - your input character is treated as a file name
  - if it is relative - i.e. not '/' on Unix-like systems  - the current directory is prepended to produce an absolute filename.

Whether this all is intuitive and well documented or not I can't tell.

You may be right that we could (try to) select only the filename part in some cases (particularly if the application presets it to an arbitrary directory on the system) but that would constitute a major behavior change WRT previous versions that some users might consider a regression. Users can always use the cursor keys or the mouse to deselect the selection and position the cursor elsewhere to preserve the preset contents.

Another point, you wrote:
> Typing / causes the whole path to be erased, including the newly inserted /.

I could not reproduce the second part of this statement: _"including the newly inserted /"_. In my tests the '/' was always preserved in the input field.

Therefore I don't consider the current behavior (after my commit) to be a bug and I wouldn't want to pursue this issue further.

Did you (or the Dillo team) consider using the more modern "native" file chooser (`Fl_Native_File_Chooser`)? We suggest to use it nowadays (its fallback is still to use the builtin file chooser though). It has many advantages and uses the system's look and feel - and the behavior the user may be used to (usually separate input fields for directory and filename, resp.).

-----
(¹) particularly consistent with normal text input fields that are selected e.g. when the field is entered by typing `TAB`

**Comment by rodarima** [comment] 2024-07-06 12:19
> @rodarima I'm trying to explain what happens and why it is as it is...
> 
>    1. This special FLTK file chooser has IIRC been introduced in FLTK 1.1 (about 2001 or even earlier) and didn't get (m)any behavioral changes since then. Its internal programming is pretty complicated due to the fact that it reacts on any key press and **_tries to guess what the user wants to achieve_**. This peculiar behavior is even more complicated since it uses both the directory and filename part in one input field as you noticed.
> 
>    2. The current behavior when the (full) input field is selected is - at least mostly - consistent: if you type one character...
> 
> 
>    * the entire string is removed (¹)
> 
>    * your input character is treated as a file name
> 
>    * if it is relative - i.e. not '/' on Unix-like systems  - the current directory is prepended to produce an absolute filename.
> 
> 
> Whether this all is intuitive and well documented or not I can't tell.

Thanks for your explanation, now I understand the issue better.

> You may be right that we could (try to) select only the filename part in some cases (particularly if the application presets it to an arbitrary directory on the system) but that would constitute a major behavior change WRT previous versions that some users might consider a regression. Users can always use the cursor keys or the mouse to deselect the selection and position the cursor elsewhere to preserve the preset contents.

I think this is fine, as we can mitigate the issue by chdir() to the downloads directory, so typing a non-/ character will only replace the file name, which is probably what users would expect.

> 
> Another point, you wrote:
> 
> > Typing / causes the whole path to be erased, including the newly inserted /.
> 
> I could not reproduce the second part of this statement: _"including the newly inserted /"_. In my tests the '/' was always preserved in the input field.

I'm using the `branch-1.3` branch, maybe it doesn't happen in master? I can take a look at the internals of FLTK and place a breakpoint in the function that clears the input text, but it would take me some time.

> Therefore I don't consider the current behavior (after my commit) to be a bug and I wouldn't want to pursue this issue further.

I also think the problem I initially reported is solved with your commit, so I think you can close this issue. I can open another issue with the missing / at the start when I have more details.

> Did you (or the Dillo team) consider using the more modern "native" file chooser (`Fl_Native_File_Chooser`)? We suggest to use it nowadays (its fallback is still to use the builtin file chooser though). It has many advantages and uses the system's look and feel - and the behavior the user may be used to (usually separate input fields for directory and filename, resp.).

[Yes](https://github.com/dillo-browser/dillo/issues/29), but I haven't tested it yet on non-Linux systems. I also think it would be a good idea to switch to the "system" chooser.

> (¹) particularly consistent with normal text input fields that are selected e.g. when the field is entered by typing `TAB`

**Comment by Albrecht-S** [comment] 2024-07-06 14:41
> ... we can mitigate the issue by chdir() to the downloads directory, so typing a non-/ character will only replace the file name, which is probably what users would expect.

Sounds good.

> I'm using the branch-1.3 branch, maybe it doesn't happen in master? I can take a look at the internals of FLTK and place a breakpoint in the function that clears the input text, but it would take me some time.

Please don't waste your time on `branch-1.3`, this branch is in maintenance mode and gets only fixes of serious bugs (per definition) and currently mostly macOS updates because Apple's macOS changes can make FLTK inoperable or fail (this would also constitute a serious bug, of course). There are exceptions though, and I did already make one for the previous commit for this issue - in the assumption that Dillo still uses FLTK 1.3. We're trying to release FLTK 1.4.0 soon and should really concentrate on the release rather than fixing minor bugs in 1.3.

> I also think the problem I initially reported is solved with your commit, so I think you can close this issue.

Thanks, will do.

> I can open another issue with the missing / at the start when I have more details.

As I wrote (or implied), please file only bugs against the master (1.4) branch - unless they are really serious, i.e. crashes or similar.

> > Did you (or the Dillo team) consider using the more modern "native" file chooser ... ?
> Yes, but I haven't tested it yet on non-Linux systems. I also think it would be a good idea to switch to the "system" chooser.

I definitely recommend to try this. In FLTK 1.4 we have even more options to select a specific "native" file chooser, including system dialogs `GTK` (as in 1.3), `kdialog` (KDE file chooser) and `zenity` which all have their pro's and con's. Check the new `fltk-options` tool to enable these dialogs if desired. Maybe Dillo should also include these options as user preferences because the new `kdialog` and `zenity` options are OFF by default. If you switch the "GTK file chooser" option off as well you get the builtin file chooser anyway. I'm not sure about Windows and macOS though...

**_Hint:_** build FLTK (`master` = 1.4.0) and use `test/native-filechooser.cxx` on different platforms to evaluate its look and feel before integrating it in Dillo. This should give you some clues about its usability for Dillo.

BTW, I read https://github.com/dillo-browser/dillo/issues/29 and the linked Debian bug report. My impression is that Dillo's problem is more related to the selection of the "correct" directory (and to save it as a prefererence) than to using the right file chooser.

OT, but somehow related: FYI, I'm mostly using Firefox and I often wonder why it opens a particular directory and I have to navigate manually to another one. Even in one session it seems for instance to differ whether I open an image ("in another tab") and save that image or if I right-click on the image and select "save". If Firefox doesn't get it "right" ...

**Closed** 2024-07-06 14:49 UTC
Labels: bug, fixed, Prio 2 - Low
