### ISSUE TITLE
Fl_Bitmap disappears randomly

### ISSUE THREAD

**Issue by bpstahlman** [fltk/fltk#29] opened 2019-06-03 12:58 UTC
On Ubuntu 16.04, the issue can be reproduced in both the checkers and bitmap test apps. Checkers is unplayable. Occasionally, fragments of a piece will appear if you drag the mouse around the board, but for the most part, the pieces are invisible. In the bitmap app, the sorceress is initially visible, but disappears as soon as one of the buttons is clicked. Occasionally, I can get it to reappear by resizing the window. The problem doesn't seem to affect (e.g.) Fl_PNG_Image: I replaced the checkers piece bitmap with a png and the display issue went away.

**Comment by erco77** [comment] 2019-06-03 23:32
Is this with a stock build of the current master head in git, no special flags?

**Comment by bpstahlman** [comment] 2019-06-04 02:08
> Is this with a stock build of the current master head in git, no special flags?

Yes.
```
make
make install
```
I tried make install-desktop after that, but got some sort of error, presumably because I didn't have one of the prerequisites, and I didn't pursue it because I didn't really need the extra desktop stuff...

**Comment by Albrecht-S** [comment] 2019-06-04 09:35
I remember similar issues with Ubuntu 16.04 and the default WM (was it Unity with Compiz enabled?). It appeared that the WM didn't send all expected expose events or similar. I wonder though why it seems to work for you with pixmaps replaced by PNG images.

Can you try another WM? IIRC I used Gnome-Flashback Metacity and everything worked as expected. To install and use it:
```
sudo apt-get install metacity
sudo apt-get install gnome-session-flashback
```
With these two packages you should be able to select ``flashback metacity`` at login time and you can always switch back to your old WM easily.

**Comment by bpstahlman** [comment] 2019-06-04 17:25
The problem was even worse with metacity gnome flashback: the sorceress bitmap never appeared at all. The checkers game was about the same: I could get fragments of pieces to display by dragging the mouse around the board...

**Comment by Albrecht-S** [comment] 2019-06-11 12:23
Well, if another (non-compositing) WM like Metacity doesn't help I can only guess. It is possible that the graphics driver has issues. Which type (vendor) of graphics card are you using? Which Linux driver?

**From my personal experience**: I just set up a new Linux Mint 19.1 system on a notebook with an Nvidia graphics adapter (`lspci` says: `NVIDIA Corporation GT216M [GeForce GT 320M] (rev a2)`). It worked well with the default open source (`"Noveau"`) graphics driver. Well, almost... The bitmap issue you described did not occur to me. However there was a very strange glitch in test/glpuzzle: one of the yellow square pieces was **missing from the display**. It was there (not deleted) because I couldn't move another piece at its place. I could even move it although it remained invisible. After some playing around it appeared and one of the other pieces (maybe the horizontal bar) disappeared. This was reproducible.

This effect went away as soon as I installed the **proprietary Nvidia driver**. Now everything looks well AFAICT. I'm now working continuously with this system and didn't see any other negative effect with FLTK applications.

**Comment by bpstahlman** [comment] 2019-06-11 18:05
I'm not using any proprietary video drivers. Ubuntu's software updater scan doesn't find any for my system.

Relevant `lspci -k` output:
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
        DeviceName: 32
        Subsystem: Hewlett-Packard Company ZBook 15u G2 Mobile Workstation
        Kernel driver in use: i915
        Kernel modules: i915

**Comment by Albrecht-S** [comment] 2019-06-21 10:25
I'm sorry, this looks really like a driver issue and can't be reproduced on all Linux systems I tested, hence I added the label **`wontfix`**.

Note that you need to **allow** Ubuntu to use the proprietary graphics drivers by editing the software sources or something like that. You may need to add or enable a package repository or something like that. Unfortunately I don't know the details.

You could also try to use a more modern Ubuntu or other Linux system by booting their standalone (CD/DVD/USB) test system w/o installing. You should be able to run the previously built executables from your hard drive to see if this changes anything.

If you can find and install a different (likely proprietary) driver for your hardware and/or if this or the newer test system fixes the issue we'd appreciate your feedback within the next 10 days or so, otherwise I'll close the issue. Sorry that we can't help you further.

**Comment by erco77** [comment] 2019-06-21 16:08
I have a suggestion: perhaps we should change the games to using pixmaps (which will look a little nicer) so that we don't exercise obscure rendering techniques such as single-bit bitmaps (which are kinda ugly and dated by today's standards anyway). We can keep the old bitmaps in the test tools (the "sorceress" et al), but update the game examples.

**Comment by erco77** [comment] 2019-06-21 16:09
BTW, I'm willing to open a new STR for this, and supply updated art for the checkers.

**Comment by bpstahlman** [comment] 2019-06-21 16:42
Sounds like a great idea to me. I suppose I understand Albrecht's rationale
behind the "wontfix" label, but honestly, if I'm considering adoption of a
graphics toolkit billed as "cross-platform", and something as simple as a
bitmap doesn't work without proprietary video drivers, I'm probably going
to suspect I've encountered only the first in a long series of
idiosyncrasies that will require workarounds if I stick with the library...

**Comment by erco77** [comment] 2019-06-21 17:18
The original bug is likely in the X11 video drivers; few tools use or even support the old 1-bit bitmaps; that's very old school X11 stuff. The only reason that stuff's in FLTK because it wanted to show it supported old Xforms applications, and in those days, X11 running on monochrome screens like Sun used were still a thing. I'm sure X11 drivers aren't well tested for dated features like single-bit-per-pixel support.

**Comment by Albrecht-S** [comment] 2019-06-21 17:22
@erco77 It would be great if you could do this (update the games as described) and I would second that. TIA.

But unfortunately this wouldn't solve the underlying problem, would it? :-(

@bpstahlman To clarify the rationale: the open source Linux graphics drivers are unfortunately still known to be not perfect. As you can see in my report above I encountered such an issue with the glpuzzle demo that was "fixed" by installing the proprietary Nvidia driver. This seems to prove (at least from my point of view) that the fault was not in FLTK but in the video driver. So what can we do if this is true? Sure, we can replace bitmaps with other image types, but this doesn't solve the problem for other programs using bitmaps. If someone could debug the issue and show that the fault is in FLTK we could fix it, but as long as this doesn't happen ... I don't know what else we could do.

I'm open for ideas and suggestions. Do you think you can do any of the tests with other Linux versions on the same hardware I suggested above? (And I mean: just as a test, not as a solution.)

**Comment by bpstahlman** [comment] 2019-06-21 17:31
Ah. That makes sense. Unfortunately, many potential users flipping through
the demos will be completely unaware of the historical context, and will be
much more likely to suspect problems with graphics generally than to be
impressed by the fact that monochrome bitmaps are still supported. Perhaps
the old school bitmap support could be advertised in a simple demo whose
name clearly indicates its legacy nature, with all other demos using more
modern bitmaps, which are likely to work on most systems out of the box...

**Comment by bpstahlman** [comment] 2019-06-21 17:41
@Albrecht-S Though changing to different bitmaps wouldn't solve the
underlying issue, I think that if the problem is limited to the monochrome
bitmaps, the issue could be considered *much* lower priority if it weren't
advertised so prominently in the demos. As things stand now, users who
might never even have used single-bit bitmaps may be hesitant to use FLTK
because their experience with what appear to be non-functioning demos has
(unfairly) lowered their confidence in the platform.

I may upgrade my Ubuntu to something more recent within the next week or
so, and at that point retest...

**Comment by erco77** [comment] 2019-06-21 18:07
Yes, that's my point; the "sorceress" demo, ugly as it is, can still be used to test for the bitmap bug.
But the games should really show the best features of the toolkit, and not leverage ancient, ugly, and apparently buggy tech.

**Comment by Albrecht-S** [comment] 2019-06-21 18:40
OK, we're making progress... I agree that replacing the old bitmap images with other images would be a step forward and should be done.

@erco77 Greg, if you are really going to do this, please feel free to remove the 'wontfix' label and go ahead, I'd appreciate this.

@bpstahlman Thanks for your comments, this is very much appreciated. Looking forward to your test results after upgrade (it would still be interesting if you could run the Ubuntu LiveCD w/o installing though).

I'm going to run some different Linux LiveCD's on an old HP notebook to see if this has similar issues. I'll let you know what I find out, but please don't hold your breath - it can take a while...

**Comment by bpstahlman** [comment] 2019-06-21 18:56
@Albrecht-S @erco77 - Sounds like a good plan. I appreciate your efforts.
I'll revisit the tests after I've finished upgrading my system...

**Comment by erco77** [comment] 2019-06-21 23:17
OK, I'll use this github issue to manage this change..

**Comment by erco77** [comment] 2019-06-22 07:10
Made new pieces and modified checkers; see attached image and tar.
Sorry, I don't know how to make a proper pull request for this, so here's a tar file that can be extracted relative to the fltk-1.4.x top level directory:

>      test/checkers.cxx -- has simple mods to replace the bit maps with pngs
>      test/Makefile     -- has small change for the checkers target to link with $(LINKFLTKIMG)
>      test/pixmaps/*.h  -- #include-able PNG images for the 4 checkers pieces (wht/blk + king versions)

Here's what the new board looks like with my new checkers pieces and attachment link below:
![checkers](https://user-images.githubusercontent.com/6484779/59960649-23de3280-9480-11e9-9d43-0e783668a90f.jpg)
[checkers-v1.0-erco-mods.tar.gz](https://github.com/fltk/fltk/files/3316592/checkers-v1.0-erco-mods.tar.gz)

If this looks good, I'll check it in, and will include the source png's and gimp .xcf.

**Comment by erco77** [comment] 2019-06-22 07:16
BTW, there may be a way to get the png's smaller, not sure. Has to be PNGs for the alpha channel, so the drop shadows work correctly. (The original checkers game went to great lengths to make a dithered drop shadow, so I figure this is an important feature to maintain)

The original game uses 16 xbm files totaling 40k.
My higher detailed pieces ends up using double that, around 100k.. but looks much better ;)

**Comment by Albrecht-S** [comment] 2019-06-22 11:16
Awesome, the pieces are kinda frugal but they are looking nice, altogether simpler but better than before. Thank you very much!

One note though, if I had a wish free ;-) : the drop shadow looks fine (light from top right side [1]), but the light and shadow on/inside the pieces are looking inconsistent:

- the lightest part of the pieces seems to be at the top, which means light comes from the top side
- the shadow (darkest part) inside the inner part of the pieces looks as if the light came from the top right side.

Could you "turn" this so the light and shadow is consistent, i.e. light source on the top left side [1] for all parts of the "light and shadow" mentioned above?

Or is my visual impression incorrect?

Another minor observation: when zooming the game with ctrl/+ I can see small artifacts at the bottom and right borders of the pieces. Is the size correct, are there maybe issues with color/transparency at the borders? Well, it's a minor issue, but if you could check it...

[1] ISTR that light from top left looks most natural to humans.

**Comment by Albrecht-S** [comment] 2019-06-22 11:23
Another question: how did you convert the .png to .h files? We should have a recipe to do that for later changes. I propose to use 'xxd -i' which is widely available (I used it on Windows and Linux). It has the advantage that it also generates a size variable like this:
```
unsigned char black_checker_png[] = {
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
  ...
  0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82
};
unsigned int black_checker_png_len = 3812;
```
Or can we utilize `fluid` somehow? Fluid can embed images...

Thoughts?

**Comment by Albrecht-S** [comment] 2019-06-22 11:32
One addition: update test/CMakeLists.txt, see attachment.

[checkers_cmake.diff.txt](https://github.com/fltk/fltk/files/3316779/checkers_cmake.diff.txt)

**Comment by erco77** [comment] 2019-06-22 15:48
OK, I see the artifacts; fixed by going back to the original .xcf file and re-rendering.

I think I'll do this as two separate commits; one for the minimum .h files and .cxx/Makefile/cmake changes.

Second, to add the source png and xcf files, and some Makefile rules to handle the .png -> .h conversion with xxd which should never run unless the png date stamps change, as we don't want an end user dependency on xxd. Making this change separate because we might want to tweak these changes a bit, as I'm not 100% on the rule changes.

I noticed our makedepend for the test directory is out of date; needed to recreate that with 'make depend' to change the checkers.o .xbm dependencies to the new .h files, and saw some big diffs after running. Not sure when we're supposed to update makedepend, but it seems like it's a manual process, and should be done e.g. when .H files are added or removed from the FL directory.

**Comment by Albrecht-S** [comment] 2019-06-22 16:20
@erco77 - regarding `make depend`: I just tried it and found no diffs in the original master branch. I assume I'm the only one who ever runs `make depend` and saves the new files. Note that you must run `make depend` on a Linux system with a default configuration. I tried to minimize diffs in the makedepend files by reducing the line width and sorting the files (see make rule), hence there should be only the necessary diffs (before that change we had lots of diffs because of duplicate entries and different line breaks).

FWIW, the `makedepend` version I'm using is from the Ubuntu package `xutils-dev`. I wonder what you're using and what diffs you're seeing.

There are only the expected diffs when I run `make depend` after the patch (and I did also `git rm` the obsolete .xbm and header files).

If you're not sure about the makedepend files, please don't commit them, and I'll update them after the new files are committed by you. Just drop a note when you're done with it. We can check the makedepend file diffs later...

**Comment by erco77** [comment] 2019-06-22 16:33
OK, as described:
    1) committed minimum changes as commit c9c51db
    2) committed source images/rule changes as commit 446c707
Oh, just saw your recent comments Albrecht. The makedepend mods are whatever 'make depend' came up with; the numerous diffs were all the .H file changes that have been made to FLTK over the last year or so; the new abi files, new .H files that some demos have been changed to use, etc.

My concern is with how the .png -> .h rules are formulated. There's probably a way to make my changes smaller, using a ".png.h" target, though we may need to add to the EXTENSIONS; wasn't sure how to do that properly without tweaking other files, so I went with explicit rules for now, separate xxd commands for each of the 4 pixmaps.
Feel free to tweak the commits as needed. I need to now pull and test on windows (yuck).

**Comment by erco77** [comment] 2019-06-22 16:38
Huh, looks like we have some kind of automated build check at github; it flagged commit c9c51db with an error. Just committed an extra change to solve that.

**Comment by Albrecht-S** [comment] 2019-06-22 17:30
@erco77 - make depend:

> The makedepend mods are whatever 'make depend' came up with; the numerous diffs were all the .H file changes that have been made to FLTK over the last year or so; the new abi files, new .H files that some demos have been changed to use, etc.

That's not entirely true, there's something else going on. I checked your commit and my `makedepend` results. The **only** diffs are the sort order of the `makedepend` file. This is strange but OT here, we should discuss this in fltk.coredev. I just opened a thread in fltk.coredev with subject "makedepend oddities":
https://groups.google.com/d/msg/fltkcoredev/sjyR_TcIza4/e1RFPWUZBwAJ

**Comment by erco77** [comment] 2019-06-22 19:25
Sounds like Evan might have figured out the makedepend issue being LC_COLLATE related.
I'm thinking the makedepend I committed is in the proper sort order ("ascii sort") as opposed to what it was, apparently a "case insensitive" sort.

**Comment by erco77** [comment] 2019-06-23 03:36
OP, just curious: if you pull the current FLTK from git, does checkers work for you now without display problems? If so we can probably close this.

**Comment by ManoloFLTK** [comment] 2019-06-23 16:42
@Greg: since you are modernizing test/chess, what about making it HighDPI friendly?
For example, on a macintosh with retina display, the chess pieces are currently drawn 
by blocks of 4 identically colored pixels.
If it was possible to construct twice larger images (that is, 124x124 instead of the present
62x62 for each piece image), that extra line in the source code would be enough
to get well-drawn pieces on HighDPI displays:
      for (int i = 0; i < which; i++) png[i]->scale(png[i]->data_w()/2, png[i]->data_h()/2);
after line #880 of file test/checkers.cxx .
That would show the use of the new
    Fl_Image::scale(int, int)
member function to improve support of HighDPI displays.

**Comment by bpstahlman** [comment] 2019-06-24 01:36
@erco77: Works like a charm and looks nice. I appreciate your work on
this...

Sincerely,
Brett S.

**Comment by erco77** [comment] 2019-06-24 01:49
Great.. closing.

**Comment by erco77** [comment] 2019-06-24 01:50
Oh, re: manolo's comment, let's make a new issue for that please.

**Closed by erco77** 2019-06-24 01:49 UTC

**Comment by erco77** [comment] 2019-06-24 01:54
On 6/23/19 9:42 AM, ManoloFLTK wrote:
> @greg <https://github.com/greg>: since you are modernizing test/chess, what about making it HighDPI friendly?
> For example, on a macintosh with retina display, the chess pieces are currently drawn
> by blocks of 4 identically colored pixels.
> If it was possible to construct twice larger images (that is, 124x124 instead of the present
> 62x62 for each piece image), that extra line in the source code would be enough
> to get well-drawn pieces on HighDPI displays:
> for (int i = 0; i < which; i++) png[i]->scale(png[i]->data_w()/2, png[i]->data_h()/2);
> after line #880 of file test/checkers.cxx .
> That would show the use of the new
> Fl_Image::scale(int, int)
> member function to improve support of HighDPI displays.

	Ah, sounds good I guess.

	Can you make a new issue for this, and I'll try to address it.
	I may have questions.

	Currently it is highdpi friendly in that you can hit CTRL(+) a number of times,
	and the board gets bigger :D

	I'd thought about going larger with the pieces, as 62x62 is not enough
	for the nice detail in most checkers pieces, esp. the king piece.

	But I went with sparse/spartian because it was easy to make the art
	myself, and no concern about copyright, "stealing" the art from an
	actual checker piece.


-- 
Greg Ercolano, erco@seriss.com
Seriss Corporation
Rush Render Queue, http://seriss.com/rush/

Skype: ercolano77
  Tel: +1 626-576-0010 ext.8
  Fax: +1 626-576-0020
  Cel: +1 310-266-8906

**Comment by ManoloFLTK** [comment] 2019-06-24 11:04
Good. I've opened the new issue #31:
"Make test/checkers HighDPI friendly"
