### ISSUE TITLE
Fl_Input text align functionality

### ISSUE THREAD

**Issue by HalanoSiblee** [fltk/fltk#1162] opened 2024-12-10 01:38 UTC
**Is your feature request related to a problem? Please describe.**
I can't align text to right or center in input box it's not implemented yet !?

**I am using FLTK**
 - Version [1.3.9]

**Describe the solution you'd like**
add the textalign function signed int
```cpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Input.H>
int main() {
  Fl_Window* window = new Fl_Window(150, 150, "letsgo");
  Fl_Input* input = new Fl_Input(0, 0, 150, 50, "letsfgo:");
  //textalign -1 left 0 center 1 right
  input->textalign(0);
  input->textfont(FL_HELVETICA_BOLD);
  input->textcolor(FL_BLACK);
  window->end();
  window->show();
  return Fl::run();
}
```
*Centering text in input*
```diff
+  input->textalign(0);
```

**Additional context**
Best of luck 💚

**Comment by MatthiasWM** [comment] 2024-12-10 10:05
There is no text alignment in input boxes yet. We may introduce right alignment for RtoL languages, which would introduce general text alignment. 1.5 planing will start after the 1.4 release is complete.

**Comment by ManoloFLTK** [comment] 2024-12-10 10:14
@HalanoSiblee Please, report here if your concern is handling right-to-left scripts. If yes, this issue would be a duplicate of #1063. Also, please explain what use you would see of center alignment in a text input widget, if any? Center and right alignment is possible in today's FLTK for widget labels.

**Comment by ManoloFLTK** [comment] 2024-12-10 11:03
> I just wanna center the input text for more polishing of my calculator app

Then you might want to make your text the label of an Fl_Box widget that is by default center-aligned and change it when necessary.

> arabic doesn't even appear in input box, fltk doesn't integrate with my system fonts !

Please, explain this in more detail. I don't see what you mean. Make also clear what platform  (Windows, Linux, macOS?) and what FLTK version (1.3.x, 1.4?) are you concerned with?

**Comment by ManoloFLTK** [comment] 2024-12-10 11:26
You are right an Fl_Input can't be converted into an Fl_Box. But if the text to handle is just a number and a % sign, a simpler widget than Fl_Input and with a centered label might be enough?

With FLTK 1.4.x and under Linux, text is by default handled by Pango whch should draw arabic text correctly. What is not done correctly is editing right-to-left text. That is the target of issue #1063. You can also get Pango with FLTK 1.3.x, but that's not the default configuration.

**Closed as completed** 2024-12-10 12:49 UTC
Labels: Prio 1 - RFE
