### ISSUE TITLE
in example "tree", button "Add 20,000", very slow

### ISSUE THREAD

**Issue by xuyun018** [fltk/fltk#1014] opened 2024-07-18 01:31 UTC
If select item "Bbb/child-01/333", press button "Add 20,000", very very slow.
scroll bar slow too.

**Comment by erco77** [comment] 2024-07-18 01:46
Hmm, not seeing this with fltk 1.4.x on linux; adding 20,000 and scrolling is instantaneous.

More details please on the the FLTK version and platform.

**Comment by erco77** [comment] 2024-07-18 02:01
OK, on a /slower machine/ I can perceive that when the 20k items parented to child-01, scrolling past those items seems slower than when added to higher level items.

Will investigate and follow up.

**Comment by erco77** [comment] 2024-07-18 02:33
Seems to go back to normal fast performance on my slow linux machine if I disable Cairo rendering, so that it falls back to using X11, via:

```
mkdir build-nocairo
cd build-nocairo
cmake -D FLTK_BACKEND_WAYLAND=OFF ..
make -j 4
bin/test/tree
```

Again, so I'm not wasting time chasing phantoms, requesting more info:

- fltk version
- platform (linux/windows/mac..)
- os version
- window manager details (X11? Wayland?)

**Comment by erco77** [comment] 2024-07-18 06:25
Possibly related: issue #1015

**Comment by xuyun018** [comment] 2024-07-18 08:06
win 7, win 10, the tree level more than 3, is very slow.

**Comment by Albrecht-S** [comment] 2024-07-18 09:52
@xuyun018 Thanks for your OS version, but we still need your FLTK version, please be as precise as possible:
- if version 1.4 from git: please specify Git revision
- if version 1.3.x, please specify exact version (x)
Thanks in advance.

**Comment by xuyun018** [comment] 2024-07-18 15:32
git https://github.com/fltk/fltk
这个版本.
我是初接触FLTK的程序员。

**Comment by erco77** [comment] 2024-07-20 18:09
OK, the conversation/investigation somehow ended up spilling over into issue #1015, so summing up:

- It seems the issue is when the Fl_Tree connector line drawing style is at the default ( "Line style: Dotted"), the tree draws the indented 20k items very slowly particularly on Windows.
- When the "Line style" is changed to solid lines, it draws normally/quickly.
- @ManoloFLTK and @erco77 confirmed this on Windows

This appears to be an issue with `fl_point()` apparently being quite a bit slower at drawing than it used to be. Probably something @ManoloFLTK needs to follow up with, as I'm not sure where to even start with that, as I think things changed quite a bit recently with how drawing is done across all platforms in 1.4.x.

**Comment by xuyun018** [comment] 2024-07-21 01:25
> OK, the conversation/investigation somehow ended up spilling over into issue #1015, so summing up:
> 
> * It seems the issue is when the Fl_Tree connector line drawing style is at the default ( "Line style: Dotted"), the tree draws the indented 20k items very slowly particularly on Windows.
> * When the "Line style" is changed to "Solid" lines, it draws normally/quickly.
> * @ManoloFLTK and @erco77 confirmed this on Windows
> 
> This appears to be an issue with `fl_point()` apparently being quite a bit slower at drawing than it used to be. Probably something @ManoloFLTK needs to follow up with, as I'm not sure where to even start with that, as I think things changed quite a bit recently with how drawing is done across all platforms in 1.4.x.
> 
> @xuyun018 please try changing the setting "Line style" to "Solid" in the test/tree program, and follow up with you results here (and not in the separate issue #1015). It should solve (or at least work around) the problem. The devs will investigate why the "Dotted" is slow.

Yes, it's resolved!

**Comment by xuyun018** [comment] 2024-07-21 01:33
I have another question, does FLTK have the TreeListView?

**Comment by erco77** [comment] 2024-07-21 07:02
@xuyun018 Regarding the question of TreeListView or any other general questions about fltk, please ask on either the [fltk.general google group](https://groups.google.com/g/fltkgeneral), or in [github "fltk discussions"](https://github.com/fltk/fltk/discussions/) to keep this particular bug report clear so the devs can follow through on correcting the problem.

**Comment by erco77** [comment] 2024-07-21 07:24
I'm probably the wrong person to look into the internals, but it would /seem/ `fl_point()` might end up calling `rectf()` in GDI:
```
void Fl_GDI_Graphics_Driver::point(int x, int y) {
  rectf(x, y, 1, 1);
}
```
I get why that would be when FLTK can scale things, and it seems there might be a special path for drawing rectangles when FLTK doesn't scale:
```
void Fl_GDI_Graphics_Driver::rectf_unscaled(int x, int y, int w, int h) {
  RECT rect;
  rect.left = x; rect.top = y;
  rect.right = (x + w); rect.bottom = (y + h);
  FillRect(gc_, &rect, fl_brush());
}
```
..but I'm thinking when there's no scaling, perhaps `fl_point()` should be calling `SetPixel()` instead of `FillRect()`?

**Comment by erco77** [comment] 2024-07-21 07:31
Would it maybe make sense to re-implement GDI `point(int,int)` to do something like this instead..?
```
void Fl_GDI_Graphics_Driver::point(int x, int y) {
  if (scale() == 1) { SetPixel(gc_, x, y, fl_RGB()); }
  else              { rectf(x, y, 1, 1); }
}

**Comment by ManoloFLTK** [comment] 2024-07-21 10:11
I also tried to replace the rectangle drawing by the SetPixel() call and see no efficiency difference. Furthermore, I see that the test/tree app is equally slow under 1.3 and 1.4 when using dotted lines. Thus, the problem arises from drawing thousands of dots.

My view on this is that the tree app should determine whether a potential dotted line is visible and refrain from drawing it if it's not.

**Comment by erco77** [comment] 2024-07-21 15:13
@ManoloFLTK glad you could replicate.

> My view on this is that the tree app should determine whether a potential dotted line is visible and refrain from drawing it if it's not.

The tree drawing code already avoids calling fltk drawing functions for items that are above or below the edges of the widget, so it's only calling fltk drawing functions for what's actually visible on screen. (If that's what you mean).

The draw() code /does/ consider all uncollapsed items in the entire tree (including things offscreen) to properly calculate the scrollers based on the widest text (to know the tree's visible max width) and the lowest visible portion of the tree of uncollapsed items (for the overall tree height), but those calculations do skip the fltk drawing functions for items not on screen.

The pixel plotting must be super terrible in performance, because fl_point() is only being called for what you see on screen. I'm not sure how many dots that is, but it sure seems like it isn't much.

**Comment by erco77** [comment] 2024-07-21 15:31
Hmm, I need to check though.. because when I add the indented 20k items, then remove all except maybe 200 items, the performance improves a lot, even though the dots on screen are the same.

So maybe I have a bug in calculating the onscreen/offscreen stuff when it comes to the connector lines; I'll double check!

**Comment by erco77** [comment] 2024-07-21 15:50
Oh, I think there is a weird bug in Fl_Tree's draw code where one of the Y values flips to negative because there's so many items, causing a really long line of dots to be drawn offscreen. That must be the cause.

**Comment by erco77** [comment] 2024-07-21 16:13
OK, yeah, I think I identified it.. an odd case for drawing the really long vertical lines when there's a lot of child items. Should be a simple fix (below).

```
diff --git a/src/Fl_Tree_Item.cxx b/src/Fl_Tree_Item.cxx
index c8f3d0e00..76b460afe 100644
--- a/src/Fl_Tree_Item.cxx
+++ b/src/Fl_Tree_Item.cxx
@@ -1147,8 +1147,12 @@ void Fl_Tree_Item::draw(int X, int &Y, int W, Fl_Tree_Item *itemfocus,
       // Special 'clipped' calculation. (intentional variable shadowing)
       int is_clipped = ((child_y_start < tree_top) && (Y < tree_top)) ||
                        ((child_y_start > tree_bot) && (Y > tree_bot));
-      if (render && !is_clipped )
-        draw_vertical_connector(hconn_x, child_y_start, Y, prefs);
+      if (render && !is_clipped ) {
+        // Clip the vert line to within screen area before drawing
+        int Y1 = (child_y_start < tree_top) ? tree_top : child_y_start;
+        int Y2 = (Y > tree_bot)             ? tree_bot : Y;
+        draw_vertical_connector(hconn_x, Y1, Y2, prefs);
+      }
     }
   }
 }
```

Will do a few more tests to make sure that works, then commit and close.

Thanks @ManoloFLTK , your comment about drawing only visible items put me on the trail to identifying a corner case where it was in fact drawing really long vertical dotted lines offscreen.

And thanks @xuyun018  for the bug report -- that was an interesting test case I'd never tried.

**Comment by ManoloFLTK** [comment] 2024-07-21 16:54
I tried the fix above. Beautiful. The 20,000 added nodes can now be scrolled easily with dotted connecting lines.

**Comment by erco77** [comment] 2024-07-21 17:21
OK, applied the effective patch as 0291b48 and closing.
Thanks everyone!

**Closed by erco77** 2024-07-21 17:21 UTC
