### ISSUE TITLE
Fl_Tile with two OpenGL subwindows (one in a group), creates refresh issues on Windows and macOS

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#737] opened 2023-06-25 14:09 UTC
**Describe the bug**
Using Fl_Tile with two OpenGL subwindows (one in a group) leads to refresh issues on Windows.  macOS and Linux refresh properly.

**To Reproduce**
Attached is a .zip file with .cpp files, a CMakeLists.txt file, instructions in the README to compile and a pre-compiled executable.
Drag the middle of the tile widget (near the stretched circle at the bottom). and you will see flickering and redraw artifacts specially if you drag fast.

**Expected behavior**
There should not be any redraw  issues (flickering and artifacts).

**Screenshots**
N/A

**FLTK Version**

FLTK v1.4.0 - git comit 6f77f40aadaaec8ab0e29d3ae5c9f6e5792c4a41

**FLTK Configure / Build Options**
See the included README in the .zip file.

**Operating System / Platform:**
Windows 11

**Linux/Unix Runtime, if applicable:**
N/A

[fltk_win_redraw.zip](https://github.com/fltk/fltk/files/11859903/fltk_win_redraw.zip)

**Comment by Albrecht-S** [comment] 2023-06-25 14:39
Hi Gonzalo, thanks for the report. Before we start analyzing this, please make sure that the issue persists if you replace the main UI window with Fl_Double_Window. Excerpt from your .fl file:
```
class ViewerUI {open
} {
  Function {make_window()} {open private
  } {
    Fl_Window uiMain {
      label mrv2
```

Fl_Window is known to cause flicker under certain circumstances and the documentation recommends to use Fl_Double_Window to avoid this. macOS uses double buffered windows internally, hence such flicker effects are not to be expected on macOS.

Note: I didn't test your code yet, but if the issue is caused by using Fl_Window and does not manifest when using Fl_Double_Window, please close this issue. However, if it still flickers, please report back here...

**Comment by ggarra13** [comment] 2023-06-25 15:08
It is a double window.  It has "type Double" and it shows as Fl_Double_Window on a recent copy of fluid.   In my real application, I am also subclassing Fl_Double_Window too.

**Comment by Albrecht-S** [comment] 2023-06-25 15:43
Yes, I see now that it's indeed an Fl_Double_Window. Looking into it...

**Comment by ggarra13** [comment] 2023-06-25 16:06
Ok.  I have a more simple case, without Fl_Flex  (which was unneeded).   I also have a case with just the two OpenGL windows (and no separator in between) that works fine, but of course, the idea is to get some separator or clue to the user that he can draw the windows (and no; I cannot draw in the GL Windows).

Without Fl_Flex:
[fltk_win_redraw2.zip](https://github.com/fltk/fltk/files/11860190/fltk_win_redraw2.zip)

[fltk_win_redraw3_works.zip](https://github.com/fltk/fltk/files/11860191/fltk_win_redraw3_works.zip)

**Comment by Albrecht-S** [comment] 2023-06-25 16:30
> and no; I cannot draw in the GL Windows

What do you want to say with this?

PS: please don't post such big files including your entire build folder (and the pre-built executable). I will **NEVER** execute binaries posted by someone and I don't think other devs will. We need an example we can build ourselves, which is of course possible, but posting the build folder is not helpful and blows up our storage space. Thanks.

**Comment by ggarra13** [comment] 2023-06-25 16:32
> > 
> 
> What do you want to say with this?

I mean I cannot draw the dotted lines in the GL window instead of using a Fl_Group or Fl_Box for them.

Sorry about the builds.

**Comment by Albrecht-S** [comment] 2023-06-25 16:34
Meanwhile I did some tests on Linux with your original files (slightly modified CMakeLists.txt). I got weird effects on Linux which are **very** different whether I use X11 or Wayland. I can't test further now and I hope that someone else may chime in here, particularly @ManoloFLTK for testing Linux/X11/Wayland aspects.

FYI: I did not yet have the time to test your 2nd and 3rd versions.

**Comment by ggarra13** [comment] 2023-06-25 16:47
> particularly @ManoloFLTK for testing Linux/X11/Wayland aspects.

I admit I did not test it under Wayland.  But under bare X11 (not emulated under Wayland) it works fine for me.

**Comment by Albrecht-S** [comment] 2023-06-25 16:54
> under bare X11 (not emulated under Wayland) it works fine for me.

I'm running a Wayland user session (Gnome) on a brand new Debian 12 (Bookworm) which means that X11 is handled by XWayland - which may make a difference (though hopefully not!).

**Comment by ggarra13** [comment] 2023-06-25 17:02
I get issues with Wayland, as I think it is still not ready for production.

I am on Ubuntu 22.04 LTS with Gnome.  I tried it with Wayland and indeed I got crazy redraws and a warning:

libEGL warning: egl: failed to create dri2 screen

**Comment by ggarra13** [comment] 2023-06-25 17:08
With Wayland (and the same binary that works fine under bare X11) I get *none* of my simple tests to work.  

Not even the one with two touching GL windows without the custom FL_Group separator.

**Comment by ggarra13** [comment] 2023-06-25 17:13
But my *actual* program under Wayland's X11 emulation works just fine.

**Comment by ManoloFLTK** [comment] 2023-06-25 20:23
Removing FL_ALPHA and FL_STENCIL makes things much better under Wayland.
A GL-savvy developer would be needed to look at the Wayland code for how to support
FL_ALPHA and FL_STENCIL. I cannot do that.

**Comment by ggarra13** [comment] 2023-06-25 21:14
@ManoloFLTK Thanks for taking a look.  Would you be the person to look at Windows (minor) redraw issues for the redraw issues?  I honestly don't care about Wayland, but I *do* care about Windows.

**Comment by ManoloFLTK** [comment] 2023-06-26 05:59
Gonzalo: can you clarify whether the FL_ALPHA and FL_STENCIL  are correctly used in your test app? The GL code is that of the test/shape FLTK toy app which uses none of these options. Does the GL code handle transparency as FL_ALPHA expects?

**Comment by ggarra13** [comment] 2023-06-26 09:05
You are correct.  That seems to be the issue with the bad redrawing under Wayland.  Find attached a new version of the code that clears the alpha and stencil channels.  With those changes, Wayland performs just like Windows, with redraw issues on dragging the bar (leaving some stray pixels).

[fltk_win_alpha.zip](https://github.com/fltk/fltk/files/11866440/fltk_win_alpha.zip)

**Comment by ggarra13** [comment] 2023-06-26 09:29
Actually, the behavior of Wayland and Windows is slightly different.  Under Wayland, if you drag the separator bar quickly to the top it will disappear.  Under Windows, if you drag it fast, but not extremely fast, it won't disappear but it will leave some stray pixels behind which will get redrawn when the mouse is released.

**Comment by Albrecht-S** [comment] 2023-06-26 10:05
@ggarra13 Since the OpenGL/Wayland issue seems to be resolved now (thanks, Manolo), one thing that comes to mind is box types. I noticed in your original code a lot of `box(FL_NO_BOX)` assignments. This could cause artifacts since the background wouldn't be redrawn. It's only a wild guess, but could you please try to replace the `FL_NO_BOX` types with `FL_FLAT_BOX` to see if this changes anything?

**Comment by ggarra13** [comment] 2023-06-26 10:30
I tried it.  It does not change anything.

**Comment by Albrecht-S** [comment] 2023-06-26 10:39
I looked at your group structure, and - honestly - I don't understand what you are doing. The way you use fluid to create the UI and its subgroups is confusing.

I noticed particularly that your Fl_Tile has overlapping subgroups (one group appears to be empty). Is this all intended?

Note that FLTK does not (officially) support overlapping subwidgets and this may contribute to the issues. But again, this is only a wild guess. Sorry.

**Comment by ManoloFLTK** [comment] 2023-06-26 10:41
@ggarra13 Please, consider the attached toy program that modifies test/tile.cxx putting 3 GL subwindows inside its Fl_Tile object. These GL windows have FL_STENCIL without this having any good or bad effect. The FL_ALPHA is removed because I suspect the GL code is not taking care of redrawing the background and this is visible under Wayland. I see this toy program work and redraw correctly and identically under Windows, X11 and Wayland. Please, double check your use of GL windows inside an Fl_Tile object. In my view, there's no issue in FLTK.

[tileGL.cxx.txt](https://github.com/fltk/fltk/files/11867502/tileGL.cxx.txt)

**Comment by ggarra13** [comment] 2023-06-26 11:02
@Albrecht-S The first overlaping empty group is per the FLTK Fl_Tile instructions which is an invisible group that controls the minimum and maximum resize of the Fl_Tile.  The second group, in the Fl_Tile (timelineGroup) is to draw the dotted lines as the separator.  This second group may be conflicting as it overlaps the bottom GL Window, I agree, but I also tried it without the overlaps and the results were worse.  This group should draw before the gl window, as the gl window is a child of it, so it should not have issues.

@ManoloFLTK I tried your test on Windows, and I saw that it did not work properly.  I put a movie of the problems at:

https://mega.nz/file/HHBBEIrb#VcuSxQue49YJhDdS2wcPTD6AsP54KhTC0iyYs-y4shE

In it, you can see that the border separators change size and by the end they don't refresh properly.

**Comment by imaclmaca** [comment] 2023-06-26 11:25
FWIW, I got rid of the overlapping groups, so that the tile only contained two sub-groups, correctly aligned with no gap.
The problem is still observed, on Win10, with an Nvidia GPU.

Further, I note that the "top" group refreshes smoothly, but the "lower" group is "bad", though it redraws cleanly once I stop moving the mouse.

If I reverse the order in which the two sub-groups are instantiated, so that the lower group is created first, then the problem flips over; then the lower group updates smoothly, and the upper group is messed up (until I stop moving the mouse...)

If I make the whole window resizable and set the min height/width smaller (256, 256 in this case) then I find I can resize the app and BOTH GL scenes then refresh smoothly with no rendering artefacts.

I infer from this that whatever Fl_Tile is doing is "different" from what happens in response to a simple resize, and that whatever Fl_Tile is doing favours the "first" child in some way and the subsequent child only gets properly updated periodically.
When dragging the divider up and down, I could probably convince myself there is a "timer tick" to the drawing of the flawed artefacts, like there is a background timer that decides to refresh the second sub-group.

I have no idea how Fl_Tile decides to refresh its children, but TBH I doubt it's via a timer tick!

**Comment by imaclmaca** [comment] 2023-06-26 11:39
Last comment should have said "than the more  **_basic_** Nvidia GPU in the other box".

Also, FWIW, I copied the Win10-compiled binary over - no discernible difference to the locally compiled version at runtime, so may well just be down to GPU speed.

Shouldn't be happening though, I think, since the window-resize behaviour updates both GL sub-groups smoothly and free from artefacts...

**Comment by ggarra13** [comment] 2023-06-26 12:11
> I infer from this that whatever Fl_Tile is doing is "different" from what happens in response to a simple resize, and that whatever Fl_Tile is doing favours the "first" child in some way and the subsequent child only gets properly updated periodically. When dragging the divider up and down, I could probably convince myself there is a "timer tick" to the drawing of the flawed artefacts, like there is a background timer that decides to refresh the second sub-group.
> 
> I have no idea how Fl_Tile decides to refresh its children, but TBH I doubt it's via a timer tick!

Fl_Tile does not do anything special to move its children upon FL_DRAG.  It calls move_intersection which in turn calls damage_resize on each child widget except the resizable one. 

The problem, I think, which I already run into on Windows at least, is that the resize on the child opengl widget is called from within a handle() call and it changes the *position* not just the size of the gl window.  I think *that* is what WIndows (and it seems Wayland too) don't like.

**Comment by ManoloFLTK** [comment] 2023-06-26 13:11
> @ManoloFLTK I tried your test on Windows, and I saw that it did not work properly. I put a movie of the problems at ……

Sorry. I see everything working properly in this movie.

**Comment by Albrecht-S** [comment] 2023-06-26 17:02
Hmm, some really interesting news: I ran **all** test programs provided so far in my Windows VM and they all worked like a charm. No artifacts, GL drawing fine.

Note: my test system has Intel graphics. All test apps have been cross-compiled (MinGW 64-bit) on Linux (just in case this is relevant but I don't think so).

AFAICT this seems to indicate that it's a GL issue caused by the graphics driver which we can never fully exclude.

@ggarra13 What graphics card/driver do you have on the failing system(s)?

**Comment by ggarra13** [comment] 2023-06-26 17:27
> Sorry. I see everything working properly in this movie.

Huh?  Here's a snapshot of one frame of the movie.  See how it redraws incorrectly?

![FLTK_bug](https://github.com/fltk/fltk/assets/6072843/3e7a979e-e045-4b23-92b4-46bcdefd18ff)

**Comment by ggarra13** [comment] 2023-06-26 17:39
> AFAICT this seems to indicate that it's a GL issue caused by the graphics driver which we can never fully exclude.

But according to Ian, he sees the problem with both NVidia and AMD graphics cards.  I don't think it is a driver issue.

**Comment by Albrecht-S** [comment] 2023-06-26 17:49
@ggarra13 Do you have another system where you can test your programs?

**Comment by Albrecht-S** [comment] 2023-06-26 17:52
>  Here's a snapshot of one frame of the movie. See how it redraws incorrectly?

I agree that this looks wrong, but I can't see **any** issues on my system (VM). Usually VM's are worse than real systems, but I can try to boot into a real Windows system later (very likely not today).

**Comment by ggarra13** [comment] 2023-06-26 17:55
@Albrecht-S I have another dual boot machine (Ubunut 22.04 LTS and Windows 8.1), but it also has an (older) NVidia graphics card.  A macOS Intel laptop with Ventura.    The problem, AFAICT, shows up only on the Windows machine (I will now try the Windows 8.1 machine to see if the problem shows up there too).

**Comment by erco77** [comment] 2023-06-26 17:56
I think we've seen in the past where "generic" graphics drivers can have bugs that cause the same problem with different hardware, and installing hardware specific drivers can fix the problem. That weird problem we had with the dotted-line drawing of focus boxes with the generic X11 drivers comes to mind.

**Comment by ggarra13** [comment] 2023-06-26 22:14
@Albrecht-S @ManoloFLTK  I tried it on my Windows 8.1 box with an older NVidia card (GeForce GTX 960/PCIe/SSE2 and older driver: 4.6.0 NVIDIA 386.13).  There was still refresh issues (lags in the opengl windows redrawing) and the shapes would not fill the gl window, but there were no artifacts left-over of the redrawing as I posted in the picture.

I will now try to update in my Windows 11 box to the latest Windows drivers (and hope for the best!).

**Comment by Albrecht-S** [comment] 2023-06-26 22:19
Great, thanks for testing, and good luck with the driver update. Good night, going offline now...

**Comment by ManoloFLTK** [comment] 2023-06-27 07:27
> Sorry. I see everything working properly in this movie.

More exactly, what I mean is that there are quite visible artefacts, but they are all transient and disappear as soon as the (sub)window resizing operation is stopped. I would believe the FLTK public API is not capable of preventing such artefacts to appear transiently.

**Comment by imaclmaca** [comment] 2023-06-27 14:51
So, a few comments on recent post (though probably nothing that will help us).
Albrecht says his Windows VM does not exhibit this behaviour - is this a VBox VM? I find the GL behaviour under VBox quite odd at times (though it may depend on whether the VM GPU accel. is enabled or not.) 
Anyway, FWIW I am cautious about any behaviours I see with Windows GL under VBox, since I find it is often different from what I see with a "real" GPU...
In my tests with "real" GPUs I have seen some artefacts with the (fairly high spec. but older) AMD GPU, a newer but lower spec. Nvidia GPU and with an Intel built-in GPU, now. All were running the latest drivers I could find. The Nvidia and Intel tests looked very similar, the AMD looked less bad - but that might just be a raw performance difference?

Anyway, on that basis, I'm not sure it is a GL driver issue per se... Not sure.

Also, referring to Manolo's observation about "is not capable of preventing such artefacts to appear transiently", the key for me is that if I resize the app window, both GL scenes update smoothly with no artefacts, but if I move the Fl_Tile border, the "second" GL scene gets artefacts, but the "first" scene does not.
So it seems to me there is something "different" about what Fl_Tile is doing, as compared to what resize does, for example and that it is possible to refresh both scenes without tearing...

**Comment by ggarra13** [comment] 2023-06-27 17:43
@imaclmaca @ManoloFLTK The newer driver did not work for me either.  But I already run into a similar issue on Windows.  Basically, when calling window->resize() from a handle() method of another FLTK widget, the window being called would not refresh.  I had to, and in this case I applied it too, call a Fl::add_timeout() to refresh the windows.   That seemed to solve my problems with the GL refresh issue on my real application.

Regarding Manolo's comments about the artifacts being transient, I find that sometimes this is not the case.  Sometimes the border between the two GL windows gets thicker or smaller, depending on the direction you are dragging, even though the coordinates, when I checked them, seem file.

**Comment by Albrecht-S** [comment] 2023-06-27 19:11
> Albrecht says his Windows VM does not exhibit this behaviour - is this a VBox VM?

@imaclmaca: Yep, running on Debian 12 Bookworm, with Intel graphics. Virtualbox 7.0.8, Video Memory: 128 MB, Graphics Controller: VBoxSVGA, "Enable 3D Acceleration" is OFF.

`inxi` on the host reports:
```
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics driver: i915 v: kernel
  Device-2: Intel DG2 [Arc A370M] driver: N/A
  Display: wayDevice-2land server: X.org v: 1.21.1.7 with: Xwayland v: 22.1.9
    compositor: gnome-shell driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: iris gpu: i915 resolution: 1920x1200~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: Mesa Intel Graphics (ADL GT2)
```

I don't know what "Device-2" is, maybe the HDMI port? That's not in use.

**Comment by ggarra13** [comment] 2023-07-07 08:17
@ManoloFLTK @Albrecht-S I tested @ManoloFLTK 's tileGL.cxx on macOS and I saw there are issues there too.  We have the return of the red screen window.  See this movie:

https://mega.nz/file/CDAwRLRC#NtABwVh1t_ze3-GaWpI4R_0Z-QQ1pBjaDmSTSTjo1HY

**Comment by ManoloFLTK** [comment] 2023-07-07 13:49
I don't think the FLTK public, cross-platform, API is enough to control what happens transiently during the resize of GL subwindows.

**Comment by ggarra13** [comment] 2023-07-07 21:32
> I don't think the FLTK public, cross-platform, API is enough to control what happens transiently during the resize of GL subwindows.

I don't think in the case of macOS it is an issue with the FLTK API.  It is an issue with FL_DOUBLE OpenGL subwindows.  If I take out the FL_DOUBLE from the shape_window class in your tileGL.cxx file, there's no red screen flickers.  However, in my application, without FL_DOUBLE sometimes I get redraws of the bottom GL window on top of the top GL window.  With FL_DOUBLE, I don't get bad redraws, but I get red screen flickers while resizing the tile or the window.

**Comment by ggarra13** [comment] 2023-07-12 08:03
@ManoloFLTK I built the latest from master and it flickers due to commit 81615bbe0.  I made a superbuild demo from your tileGL.cxx compiling Debug and Release (with the two git tags).  See the included README. file.

[red_flicker.zip](https://github.com/fltk/fltk/files/12025383/red_flicker.zip)

**Comment by rageworx** [comment] 2023-07-14 02:29
Dear @ggarra13 ,
I have interested in your issue, and tested on my MinGW-W64 (Windows + MSYS2), nVidia GTX1060-6GB ( nV drv 535.98 ).
I used [libfreeglut](https://freeglut.sourceforge.net/) with your source.

And nothing appears, maybe caused by GLUT ?
![image](https://github.com/fltk/fltk/assets/6948225/0c97ad95-5dd4-4297-9ebc-172c9305b0f0)

Here a zip file modified from yours, 
[red_flicker-rageworx-mingw-w64.zip](https://github.com/fltk/fltk/files/12045749/red_flicker-rageworx-mingw-w64.zip)

I think this issue may depend on GLUT on your system, not FLTK.
You can try the same way by this sequence.

1. Clone `libfreeglut` or download source [here](https://github.com/FreeGLUTProject/freeglut/releases).
2. I just made a build directory, and did `cmake ..` for result ninja (MinGw-W64 cmake produces ninja first).
3. Build `libfreeglut`, and test it - I've been checked all demo works on Windows (but fullscreen has some bug)

Hope this little experimental helps solve your issue.

**Comment by ggarra13** [comment] 2023-07-14 07:19
My problem is now with macOS.  I have a work-around for Windows under MSVC19.   My issue now is with macOS (Intel at least).

**Comment by ggarra13** [comment] 2023-07-14 07:49
> And nothing appears, maybe caused by GLUT ?

No, the demo is just that.  The purple and yellow sections are drawn with OpenGL3 (I just clear the screen not draw a fancy graphic as it is tricky to do so with OpenGL3).   The issue I see on Windows is when I drag the middle  section of the the purple and yellow sections (the Tile in the OpenGL windows).  On macOS, I see red flickering when I drag *and* when I resize the window.

**Comment by rageworx** [comment] 2023-07-14 13:09
> > And nothing appears, maybe caused by GLUT ?
> 
> No, the demo is just that. The purple and yellow sections are drawn with OpenGL3 (I just clear the screen not draw a fancy graphic as it is tricky to do so with OpenGL3). The issue I see on Windows is when I drag the middle section of the the purple and yellow sections (the Tile in the OpenGL windows). On macOS, I see red flickering when I drag _and_ when I resize the window.

Dear @ggarra13 ,
I have tested on my old MacBook Pro 2015-early CTO ( 16GB/1TB ) Intel by match your case.
![image](https://github.com/fltk/fltk/assets/6948225/26f42752-e402-495b-8dea-50908d6c6609)
I can make flickering as you described.

Before it continue, my macOS12 llvm-g++ displays deprecated OpenGL warnnings to me like this:
![image](https://github.com/fltk/fltk/assets/6948225/c04ff61b-89cf-47e0-ab89-0b66259a1189)
And I targeted my FLTK to minimal compatibility for macOS 10, universal binary (arm64+x86.64).

Anyway, it seems to this flickering caused by macOS glut, not FLTK, as my opinion.
Maybe better result if FLTK supports METAL instead of OpenGL, but latest version of macOS pushing OpenGL3 for now.

**Comment by rageworx** [comment] 2023-07-14 13:26
Dear @ggarra13 
I found something, you decided FL_DOUBLE, but I chosen FL_RGB and FL_OPENGL3, and main window for single (macOS doesn't care single or double as I know).
Here I attaching my modified test here, you may like it.
[red_flicker-rageworx-macOS12.tar.gz](https://github.com/fltk/fltk/files/12050808/red_flicker-rageworx-macOS12.tar.gz)

**Comment by ggarra13** [comment] 2023-07-14 17:05
@ManoloFLTK @rageworx I found something, you decided FL_DOUBLE, but I chosen FL_RGB and FL_OPENGL3, and main window for single (macOS doesn't care single or double as I know).

Yes, I am aware that without FL_DOUBLE it does not flicker.  Unfortunately, it does not create a back buffer for OpenGL, which creates other issues for code that relies on it (like mine).  Also, if you go to my original .zip file (and run the runme.sh superbuild script), you will see the GL compile warning is silenced and that the commit 81615bbe0 does not work, while commit 5196d6682 seems to work.

**Comment by MatthiasWM** [comment] 2023-11-05 21:55
I have tried this file [red_flicker-rageworx-macOS12.tar.gz](https://github.com/fltk/fltk/files/12050808/red_flicker-rageworx-macOS12.tar.gz) on macOS M1 and it does flicker and have tons of artifacts, but that is no surprise at all. The children of the tile are leaving gaps which creates overlapping widgets that fight for pixels and gaps that are not redrawn at all. I updated all widgets to have the touch without gap and all artifacts vanish.

I am not saying that there is no problem, but for the sake of isolating what is actually wrong, it is *very* important to use the Fl_Tile widget correctly.

It may also be worth a try to override `Fl_GL_Window::resize(...)`:

```
void MyClassDerivedFromGLWindow::resize(int x, int y, int w, int h) {
  Fl_GL_Window::resize(x, y, w, h);
  redraw();
}
```
and see if that changes anything. A more risky way would be to call `draw();` instead of `redraw();`. I would not put that into production, but it would be good to see if that changes anything.

**Comment by MatthiasWM** [comment] 2023-12-05 17:45
@ggarra13 did you have time to verify my suggestion? Did it fix the issue? If we don't hear from you, we will assume that this issue is fixed and close it. Thanks.

**Comment by ggarra13** [comment] 2023-12-05 17:53
@MatthiasWM I've verified that there are no overlapping issues with my widgets.  Redrawing in the resize has no effect as resize by itself redraws.  I've followed others suggestions to not use FL_DOUBLE and it works, and my OpenGL code seems not to be effected by it surprisingly (well, not so surprisingly as I realized I only draw on the current -GL_BACK- buffer).   Whether the issue should be closed as fixed is debatable.

**Comment by MatthiasWM** [comment] 2024-01-28 17:15
I have been checking th macOS code, and to me it seems that NSOpenGLContext::flushBuffer confuses the target buffer if multiple buffers are flushed at the same time. This is a bug in the Apple OpenGL driver that we can not fix. I was able to work around it by delaying flushBuffer calls to make the serial. It should also work by creating each OpenGL context in its own thread. But none of that is in the scope of FLTK. Apple no longer supports OpenGL, so I expect no update.

Does anyone else have any ideas?

**Closed** 2024-01-29 21:45 UTC
