### ISSUE TITLE
Fl_Native_File_Chooser::filter_value() [Kdialog] always returns 0

### ISSUE THREAD

**Issue by michel34** [fltk/fltk#899] opened 2024-01-30 22:09 UTC
**Describe the bug**
Making a "Save to..." dialog with Fl_Native_File_Chooser on Linux (it uses Fl_Kdialog_Native_File_Chooser_Driver) with a filter, the return value of filter_value() is always 0, whichever file type is selected. Of FLTK 1.3.9, the return value is appropriately set to the selected file type.

**To Reproduce**
[chooser.cpp.zip](https://github.com/fltk/fltk/files/14104718/chooser.cpp.zip)
1. uncompress file chooser.cpp
2. built with fltk-1.4.x-20240126-f2544509, with command
fltk-config --compile chooser.cpp
3. run executable:
./chooser
4. click on the only button "Save file"
5. on bottom right, select the 3rd choice: "CSV files"
6. enter a file name, such as "a.csv", and validate
7. see message box displaying result of filter_value(): should be 2, but is 0

**Expected behavior**
filter_value() should return 2 when I select the 3rd choice as the file filter.
Using FLTK 1.3.9, the value is 2 (OK).

**Screenshots**
N/A

**FLTK Version**
 - Version: 1.4.x-20240126-f2544509
 - Downloaded and self-built from: Weekly Snapshot from https://www.fltk.org/

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Please include all configure or CMake options and add all CMake options you changed by using CMake GUI tools (if any).
  ./configure --enable-cairo --enable-cairoext --enable-debug
  make clean
  make

**Operating System / Platform:**
- OS: Linux 64 bit
- OS Version: Ubuntu MATE 23.10
- CPU: AMD Ryzen 5 4600H with Radeon Graphics
- Linux runtime: X11

**Additional context**
N/A

**Comment by Albrecht-S** [comment] 2024-01-31 16:56
@michel34 Thank you for your report. I'm still investigating but here are my current findings as a short list:

1. This is not a regression, it's a feature. ;-)  ... Honestly: please see details below.
2. The selection of available system ("native") file choosers is not documented properly. This needs to be fixed.
3. The selection of available system ("native") file choosers is not correct in all cases and at least not as expected by users (at least not by me).

**_Details:_**

- FLTK 1.3 uses the native GTK file chooser internally by using its API (dynamically loaded library). This enables the retrieval of the user's filter selection and the result is returned to the caller. This explains why you see the expected result in your demo program. The same is true for FLTK's own file chooser.
- **IF** FLTK 1.4 uses the GTK file chooser the result is the same as that of 1.3.x (works as expected).
- In your case the `kdialog` file chooser is selected which is new in FLTK 1.4.0. This can have several reasons (for details see below). This particular system file chooser executes the system command `kdialog` in a pipe to retrieve the selected filename. The only return value is the file or directory name or a list of names. The filter selection changed by the user can't be returned. This needs to be documented.
- The `kdialog` file chooser can't give a preset value to select a particular filter list item. It does always use the first entry of the list as the primary selection.
- Another system file chooser has been added in FLTK 1.4.0: `zenity`. This is another system dialog similar in functionality to `kdialog`. From its man page: _"zenity  is a program that will display GTK+ dialogs ..."_. The same restrictions as for kdialog apply for `zenity`.

**_Relevant System Settings:_**
The system selects kdialog or zenity only if the commands are available on your system. If any of these file choosers are selected by the FLTK library and you don't want this (e.g. because you want the same behavior as in FLTK 1.3) you can and/or need to do one or more of the following:
1. Run the new FLTK tool `fltk-options` and disable `OPTION_FNFC_USES_ZENITY` in the `Native File Chooser Options` menu (obviously only necessary if `zenity` is installed on your system).

`fltk-options -h` shows how to do this from the commandline:
```
FLTK 1.4.0. Usage:
fltk-options [-Soption[=val]] [-Uoption[=val]] [-L] [-LS] [-LU] [-f] [-v] [-h[option]]
  -Soption[=value]  change or print system wide option
  -Uoption[=value]  change or print user option
      Values can be 0 or OFF to clear, or 1 or ON to set the option.
      The value -1 or DEFAULT sets the option to its default value.
      If no value is given, the current setting is returned as -1, 0, or 1.
  -L, -LS, -LU  list the value of all options, of all system settings, 
      or of all user setting
  -f  suppresses error messages concerning file access permissions
  -v, --verbose  prints additional information in command line mode
  -h[option], --help [option]  general help, or info for the given option

    This version of fltk-options supports the following options:
  OPTION_VISIBLE_FOCUS     Draw a dotted rectangle in widget with keyboard focus.
  OPTION_ARROW_FOCUS       Arrow keys will move focus beyond text input field.
  OPTION_SHOW_TOOLTIPS     Show or hide tooltips.
  OPTION_DND_TEXT          User can drag text from FLTK into other apps.
  OPTION_FNFC_USES_GTK     Use GTK file chooser instead of FLTK if available.
  OPTION_FNFC_USES_ZENITY  Use Zenity file chooser instead of FLTK if available.
  OPTION_PRINTER_USES_GTK  Use GTK printer dialog instead of FLTK if available.
  OPTION_SHOW_SCALING      Show the zoom factor in a transient popup window.

  Calling fltk-options without options will launch fltk-options interactive mode.
```

To disable the `kdialog` file chooser you have three options:
1. Disable `kdialog` in the FLTK's CMake build options. There's no equivalent option available if you build with configure/make though. This will not be changed (configure/make support will be dropped in FLTK 1.5).
2. Unset or change the environment variable XDG_CURRENT_DESKTOP **if its value is 'KDE'**.
3. Deinstall or rename the system tool `kdialog`.

Admittedly all these options are not optimal. There should be a better option for users and I'll investigate separately how this can be improved. But for now I can only recommend one or more of the three workarounds mentioned above.

**Comment by Albrecht-S** [comment] 2024-01-31 18:13
FYI: As a first step to better documentation I added the restrictions of the system file chooser dialogs kdialog and zenity to the [online documentation](https://www.fltk.org/doc-1.4/classFl__Native__File__Chooser.html#a10d5d4cbd82a1bcc939320c1341ef399).

This is only a first step though. More to come later...

Note: I set the label `bug` because the selection of native file choosers and the corresponding documentation is not correct. I'm going to improve that.

@michel34 Please don't close this issue, I'll let you and others know what we can do after further investigation. However, feedback is always appreciated (could you figure out what to do for your situation?).

**Comment by michel34** [comment] 2024-01-31 21:33
Thank you for your quick and precise answer. Indeed, on my system, Zenity is called.

It is absolutely required to write in the doc that filter_value() does not always work. But even like this, I fell somewhat uncomfortable, as for a portable library it is close to saying "you may use it if it works for you, but don't use it in a real project".

I might suggest, but I agree that nothing is ideal:
1. Detail what must be done to make sure that it works, but it is not so straight-forward
2. By default, use GTK rather than Zenity or Kdialog. The problem would be limited to the cases when GTK-dev if not available or not usable for any reason, but Zenity or Kdialog is available.
3. Define a constant, like .filter_value_available, to know when to use a fallback solution
4. Similarly, propose to add a first dummy filter, putting a '\n' as the first character of the filter string. A return value of 0 would then mean that the information is not available.

**Comment by Albrecht-S** [comment] 2024-02-01 01:49
@michel34 Thanks for your great feedback. We will definitely consider your points.

To understand the current situation let me tell you and others: Historically FLTK had only one filechooser, and AFAICT it was selected in a contest around 2002). The next development step was `Fl_Native_File_Chooser`, probably added in 2010. I'm not sure about its initial capabilities but over time it has been extended, and the main file chooser on Unix/Linux was the GTK file chooser which was dynamically linked and called via its API. So far, so good: all these platform dependent file choosers on Windows, Linux/Unix, and macOS have a working API and we could obviously support most - if not all - of the features of our original FLTK file chooser but use the platform specific look and feel.

During the last maybe two years (I'm not sure exactly when) we got user requests to include the `kdialog` and `zenity` file choosers for some reasons (one point may be for "sandboxed" apps). Details would be OT here. One of our core devs implemented these two file chooser interfaces as good as possible. Since these two are external tools (programs you can call from the commandline) they lack a better interface. The only thing they return when called are the filenames. Period. There's nothing we can do about this except documenting their (lack of) features. Which is what I did or tried to do today.

There's a common issue with cross-platform libraries like FLTK: we can only support the features provided by the particular platform, aka "the principle of the lowest common denominator". This is what hit us here.

[ There is a related issue concerning Wayland support: due to intended restrictions of the Wayland protocol we can't position windows in the same way (i.e. as free as) under X11. But nevertheless we support Wayland as good as possible... ]

What we still need are better options (maybe an API) for user programs so developers can select the file chooser a program is allowed to use.

You wrote above:
> It is absolutely required to write in the doc that filter_value() does not always work.

Done.

> But even like this, I fell somewhat uncomfortable, as for a portable library it is close to saying "you may use it if it works for you, but don't use it in a real project".

That's not what we are saying, it's more like the opposite: _"we support good file choosers across platforms. But if you want to use `zenity` or `kdialog` for some reason, then we support this as well. You are free to use one of them, however these two filechoosers lack some features, and these missing features are (now) documented"_.

What we missed was to recognize that these two file choosers can't provide all return values - and to document this fact. Thanks to you this has now been done.

For further improvement I believe we should use these two specific file choosers only as **_opt-in features_** and I'm investigating how this can be done best. The current strategy is more like "if we find it, then we use it" - which turned out not to be the best strategy. Thanks for pointing this out.

We do already have some options (as I wrote above) but I believe we need one for each file chooser and the default should be not to use them, i.e. opt-in rather than opt-out. This would IMHO improve the general look and feel, keep API compatibility, and allow developers or end users to use them if they like or need to. I'm working on this...

**Comment by Albrecht-S** [comment] 2024-02-17 14:49
**Summary:**

The documentation issues have been resolved, i.e. we document that _**some features**_, for instance `filter_value()` don't work with **_some filechoosers_**, e.g. `zenity` and `kdialog`.

**Remaining Issues:**

- [ ] better options (maybe an API) for user programs so developers can select the file chooser a program is allowed to use
- [ ] make `zenity` and `kdialog` opt-in features, i.e. extend fltk-options to have two distinct options for both filechoosers, and the default for both should always be off
- [ ] optional: remove the CMake option `FLTK_USE_KDIALOG` and compile `kdialog` support in whenever possible (needs investigation). Is this feasible?
- [ ] fix code that allows to use kdialog and/or zenity which is currently under the condition that the GTK filechooser is allowed (`Fl::OPTION_FNFC_USES_GTK`). This **_might_** be due to the fact that both `zenity` and `kdialog` use the GTK filechooser internally. If this assumption is true it should be documented clearly (currently the situation is IMHO confusing).
- [ ] maybe more ... (?)

Note: I deassigned myself and **_I tend to remove this issue from the FLTK 1.4.0 milestone_** because the remaining issues are not high prirority. However, if anybody feels inclined to resolve the remaining points (or more, if necessary) I wouldn't mind keeping it in the 1.4.0 milestone.

@MatthiasWM, @ManoloFLTK ? Any comments?

**Comment by MatthiasWM** [comment] 2024-02-17 14:52
Not much of a Linux user, so I am staying out of this. I have a list of API improvements, but not until 1.5 .

**Comment by ManoloFLTK** [comment] 2024-02-17 15:50
I support removing this from the 1.4.0 milestone.

**Comment by Albrecht-S** [comment] 2024-02-17 17:12
@ManoloFLTK, @MatthiasWM : Thanks for your comments. I removed this issue from the release milestone - we can pick this up later.

**Comment by ManoloFLTK** [comment] 2024-04-22 14:49
@michel34 Commit abfc8ee is a proposal to fix this issue. The logic of using `zenity` and `kdialog` to construct file choosers has been modified. Both are now false by default, so that they are opt-in options. FLTK by default won't use `kdialog` so it won't loose the effect of `Fl_Native_File_Chooser::filter_value()` member functions. The impact of `zenity` and `kdialog` on `Fl_Native_File_Chooser::filter_value()` is documented. Do you agree your issue is solved?

@Albrecht-S Here is a detailed description of what changed with the commit :
```
- remove build option FLTK_USE_KDIALOG replaced by an Fl::option() option
- new run-time option OPTION_FNFC_USES_KDIALOG
- make options OPTION_FNFC_USES_KDIALOG and OPTION_FNFC_USES_ZENITY
false by default
- add mention of new program fltk-options in the doc of Fl::option()
- change logic of choice of the native file chooser under X11/Wayland:
the zenity and kdialog choosers are opt-in; otherwise the GTK file chooser
is used, unless opted out with OPTION_FNFC_USES_GTK
- document that zenity may be interesting for sandboxed apps
- document that both zenity and kdialog make member functions
Fl_Native_File_Chooser::filter_value() inoperable
```
Do you see remaining issues?

**Comment by Albrecht-S** [comment] 2024-04-22 15:54
@ManoloFLTK Great, thank you very much for taking care of this.

> Do you see remaining issues?

Yes, one minor issue: we should not check the current desktop environment variable at all (Link: [it is done to check for KDE](https://github.com/fltk/fltk/blob/576f7bb9cca487cd7ffb2d3ebbb3cde3e01228df/src/Fl_Native_File_Chooser_GTK.cxx#L947)). This check can be removed entirely.

Rationale (not only for my environment, but let's use this as an example): I have both KDE and Gnome installed on my system, and both `kdialog` and `zenity` are available. If I (or any other user, of course) enable `OPTION_FNFC_USES_KDIALOG` then that's what I want to use. I'm currently using the Gnome desktop and I can't use `kdialog` although I set the option because it's blocked due to `XDG_CURRENT_DESKTOP=GNOME`. That's surprising for the user, unexpected, and not documented. Rather than changing the docs we should remove the `XDG_CURRENT_DESKTOP` check.

The documentation of the option states:
```
Meaningful for the Wayland/X11 platform /and the KDE-Plasma desktop/ only.
```

We should remove the part "and the KDE-Plasma desktop". As you can see in my example there's nothing wrong with using `kdialog` under the Gnome desktop (tested, works). We should allow this.

If you agree, please remove the check and feel free to close the issue.

**Comment by ManoloFLTK** [comment] 2024-04-22 16:40
@Albrecht-S Your suggestion is in commit 5ec7176. Closing issue.

**Closed by ManoloFLTK** 2024-04-22 16:40 UTC
Labels: fixed, documentation, Platform: X11, Platform: Wayland, Prio 2 - Low
