### ISSUE TITLE
usage in plugins on Linux

### ISSUE THREAD

**Issue by dbtx** [fltk/fltk#50] opened 2020-01-17 03:16 UTC
(sigh, fat fingered the Enter key)

I'd like some advice about thread support. The [documentation](https://www.fltk.org/doc-1.3/advanced.html#advanced_multithreading) says Fl::lock() must be called in the first thread somewhere under main(), but LV2 audio plugins (at least) can do no such thing-- main() naturally belongs to the plugin hosts.

If the lock isn't initialized before some part of the plugin tries to interact with the UI, we get a few junk bytes which appear in the terminal (when the host was launched from there). I first saw this when the lock in standalone Yoshimi wasn't being initialized "early enough". In fact, it wasn't being done in main() at all, so I moved it there, and the junk went away. Later someone wanted it moved it back to Yoshimi's separate UI thread in order to prevent crashing on a musl libc system, which was probably a musl problem anyway. But in this case the junk bytes didn't reappear, so I guess we just (apparently) kept on winning a race, somehow. Thinking about it is unpleasant.

Later still, I noticed that Qtractor gives the same symptom upon loading the Yoshimi LV2 plugin. I *seemed* to be able to work around the requirement by calling Fl::lock() in the plugin's ::instantiate() method so that before it attempted to create a UI, things would be "safe". But I'm not certain.

Is there an unofficial way to do this? What's the Right Thing™?

**Comment by abrolag** [comment] 2020-01-17 07:27
On Thu, 16 Jan 2020 19:16:18 -0800
Rob Couto <notifications@github.com> wrote:

I'd just like to add that similar junk bytes appear when the LV2 host is
Ardour, Muse or Carla, so it doesn't seem to be a problem with the host.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by dbtx** [comment] 2020-01-17 13:14
True, I left out that bit. The symptom also appears when loading Yoshimi in jalv.gtk, even though jalv doesn't support the required LV2 extension (external-ui) and makes no attempt to open a FLTK window. This could indicate we are trying to do at least one other thing at a bad time. Just the same, the early Fl::lock() workaround still cleans it up.

**Comment by ManoloFLTK** [comment] 2020-01-18 08:00
The requirement is that Fl::lock() be called once before any of the child threads
calls any of the 2 forms of Fl::awake(). Any location of that call to Fl::lock()
that respects this requirement will fit.

**Comment by Albrecht-S** [comment] 2020-01-18 17:48
Regarding the question "main() or not main()" there may be restrictions given by the platform (or OS). The FLTK team noticed and discussed in the past (I hope this is mostly correct):
- on some platforms you may only open windows in the main thread, i.e. typically in main() or a function called from main()
- on some (maybe all) platforms graphics/drawing functions (as issued by FLTK) can only be used in the same thread that created the (i.e. a particular) window.

Some of the restrictions caused by these facts might be able to overcome for different windows, but FLTK uses only one event loop for system events of all its windows. Other toolkits might be able to do graphics calls in multiple threads, but FLTK does not (at least not reliably).

Regarding plugins: if your plugin needs a GUI and this GUI is written in FLTK and shall coexist with the main GUI or other plugins written with other toolkits (or even also with FLTK), then I believe ... it depends ... Try to run all plugin graphics (i.e. FLTK) code in a single thread, start with Fl::lock() to initialize the FLTK lock, particularly before you open any windows with Fl_Window::show() and such.

I'd like to add to @ManoloFLTK's comment: Fl::lock() should also be called before you call any of Fl::run(), Fl::wait(), or any other call that might enter the FLTK event loop, for instance functions that open modal windows like fl_message() and friends.

Let me add one "warning": there can also be issues if you load and unload plugins (and load them again) or if you load/unload/use two or more plugins built with FLTK because FLTK uses some global variables that might conflict and/or not be (re-)initialized properly when a plugin is unloaded and reloaded later. Users have reported issues that have not been resolved (yet) AFAICT.

And at last one question: can you tell anything about the "junk bytes" you see? Are they on stdout or stderr, what contents? Can you run it with (i.e. pipe the output into) something like 'od -t x1' or similar to see the hex values of the junk bytes? That would be interesting.

**Comment by dbtx** [comment] 2020-01-18 23:32
Thanks very much! That is a relief. All of this ought to be manageable, and hopefully another bad interaction with musl doesn't land. I still need to test that again.

> And at last one question: can you tell anything about the "junk bytes" you see?

I tried using `od` on both stdout and stderr separately but they just kept appearing at the beginning of one row of its output. So I started to worry, and tried this:
![Screenshot_2020-01-18_16-39-47](https://user-images.githubusercontent.com/6508860/72670917-61ed0600-3a11-11ea-967a-cdf6f45864e6.png)

> Are they on stdout or stderr

I guess not, and your guess is better than mine. I managed to grab a bunch of them using a loop inside script(1) and hexdump'ed the log. I printed a newline between each run because they were just piling up. Hope this helps:
[log-hexdump.txt](https://github.com/fltk/fltk/files/4082038/log-hexdump.txt)

And here's the lot of it anyway
[jalv-stuff.zip](https://github.com/fltk/fltk/files/4082029/jalv-stuff.zip)

**Comment by erco77** [comment] 2020-01-19 00:39
Hmm, the junk chars sound like they're being written directly to the terminal device, neither stdout or err.
Sometimes the kernel sends messages directly to the user's tty. If it did, there's probably similar content in either dmesg(1) or the system log. But hopefully the kernel wouldn't be printing buggy messages.

An app might do this too; a lib even. A desperate way to communicate if it's thought there'd be no stdout/err. I'd suggest running the app under strace to see if it opens /dev/tty, as that could explain it, and if so, you could then use a debugger to break when it opens that device to see what code is generating it.

**Comment by dbtx** [comment] 2020-01-19 03:25
Never mind the gui host bits-- it was simpler to just run plain (headless) jalv and I just never thought of it. Everything is the same, just a bit faster. Also I found out exactly where in Yoshimi we would call Fl::awake() before anyone set up the lock. But it seems there's nothing in the trace about /dev except /dev/shm stuff for JACK and nothing really obvious in the vicinity of the traces where the problem "should" have been triggered. In fact, the two traces (for dirty and clean) are line-for-line comparable since quite a ways before we get to that point.

Putting Fl::lock() where I did worked because the same function [YoshimiLV2Plugin::instantiate()](https://github.com/Yoshimi/yoshimi/blob/62e9e41ffe27b2c4d10213d0b64fe85b5ae5ae27/src/LV2_Plugin/YoshimiLV2Plugin.cpp#L383) soon calls [Synth::installBanks()](https://github.com/Yoshimi/yoshimi/blob/62e9e41ffe27b2c4d10213d0b64fe85b5ae5ae27/src/Misc/SynthEngine.cpp#L2424) which (if compiled with FLTK) finally, unconditionally tries to [GuiThreadMsg::sendMessage()](https://github.com/Yoshimi/yoshimi/blob/62e9e41ffe27b2c4d10213d0b64fe85b5ae5ae27/src/Misc/Config.h#L277) and nobody is listening. Of course it was our fault anyway. But I can't see anything else yet about how it ends up on the terminal.

**Comment by dbtx** [comment] 2020-01-19 05:52
Well, it's trivial to reproduce.  On a hunch I scribbled this:
 ```
$ cat wake.c
#include <Fl/Fl.h>

int main (int argc, char **argv)
{
	int junk = 0x456789;
	Fl::awake((void*) junk);
	return 0;
}
```
Built like so:
```g++ -o wake wake.c `fltk-config --cflags --ldflags` ```
Ran in a loop with script(1) again... the random bytes only _look_ random-- they are the void pointer to the message object that we just got from ```new```.
``` 000000f0  7e 20 24 1b 5b 30 30 6d  20 77 68 69 6c 65 20 74  |~ $.[00m while t|
00000100  72 75 65 3b 20 64 6f 20  2e 2f 77 61 6b 65 20 26  |rue; do ./wake &|
00000110  3e 20 2f 64 65 76 2f 6e  75 6c 6c 3b 20 64 6f 6e  |> /dev/null; don|
00000120  65 0d 0a 89 67 45 00 00  00 00 00 89 67 45 00 00  |e...gE......gE..|
00000130  00 00 00 89 67 45 00 00  00 00 00 89 67 45 00 00  |....gE......gE..|
00000b50  00 00 00 89 67 45 00 00  00 00 00 5e 43 0d 0a 1b  |....gE.....^C...|
00000b60  5d 30 3b 64 62 74 78 40  70 65 77 74 65 72 3a 7e  |]0;dbtx@pewter:~|
```

Neat!

**Comment by erco77** [comment] 2020-01-19 06:26
Must be this:

void Fl_Posix_System_Driver::awake(void* msg) {
  if (write(thread_filedes[1], &msg, sizeof(void*))==0) { /* ignore */ }
}

Writing to stdin (here I think thread_filedes[1] is 0) probably writes to the tty, neither stdout nor stderr. Weird behavior.

Elsewhere in the code a check is made to see if the filedes[1] is valid, so we should probably do that here..

**Comment by erco77** [comment] 2020-01-19 06:30
I wasn't aware one could write to stdin and get output to the tty; works from bash too:

```
$ ( echo stuff 1>&0 ) &> /dev/null
stuff
$
```

**Comment by dbtx** [comment] 2020-01-19 07:23
Wow. That is quite unexpected and very satisfying. Thank you.

I had intended to make up a totally bare configuration for the synth so it wouldn't spew 32k+ lines in the trace while gathering up 1k+ instrument files, then I could wipe out each PID and try to diff them. But tracing 'wake' shows the needle in the haystack, right at the end:
```
<snip>
openat(AT_FDCWD, "/home/dbtx/.fltk/fltk.org/printers.prefs", O_RDONLY) = -1 ENOENT (No such file or directory)
write(0, "\211gE\0\0\0\0\0", 8)         = 8
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by abrolag** [comment] 2020-01-19 09:00
This has turned out to be quite fascinating!
I was aware the threadmessage system could cause problems and I've been (very) slowly trying to get rid of these calls. I hadn't noticed it was making that one uninitialised.

**Comment by erco77** [comment] 2020-01-19 18:27
I'd suggest the following as the obvious fix, but would want some input from Manolo, as this type of check may need to be added in other parts of the code as well:

```
void Fl_Posix_System_Driver::awake(void* msg) {
  if ( thread_filedes[1] != 0 ) { // ADD THIS
    if (write(thread_filedes[1], &msg, sizeof(void*))==0) { /* ignore */ }
  }                               // ADD THIS
}
```

**Comment by ManoloFLTK** [comment] 2020-07-22 06:32
The 2 elements of array thread_filedes are initialized to zero, and then given functional,
non null values by the first call to Fl::lock(). It's good to check thread_filedes[1] is not null
before writing to it. 
I would myself write it more concisely, but to the same effect:
  if (thread_filedes[1] && write(thread_filedes[1], &msg, sizeof(void*))==0) { /* ignore */ }

**Comment by Albrecht-S** [comment] 2020-07-22 09:10
:+1: +1 for Greg's version (with a more appropriate comment, for sure).

@ManoloFLTK Thanks for your comment and confirmation, but I had to read your code (more than?) twice to understand it. @erco77 's more verbose version is IMHO less confusing.

Do you know of other places we need to consider for adding such checks, as Greg assumed?

**Comment by ManoloFLTK** [comment] 2020-07-22 15:44
With that change, all uses of thread_filedes are protected by a test to make sure it's been assigned
its values.

**Comment by Albrecht-S** [comment] 2020-07-22 17:41
@ManoloFLTK Thanks. This issue has not yet been assigned, do you want to take it (assign it to yourself), commit, and close it?

If you do: please set also the label `fixed` when done. TIA.

**Comment by ManoloFLTK** [comment] 2020-07-23 07:10
Fixed.

**Closed by ManoloFLTK** 2020-07-23 07:10 UTC

**Comment by Albrecht-S** [comment] 2020-07-23 10:33
@ManoloFLTK Thanks. Note: added label `fixed`.
