### ISSUE TITLE
Cannot compile FLTK-1.3.5 with GCC due to narrowing conversion error

### ISSUE THREAD

**Issue by KatPurpy** [fltk/fltk#178] opened 2021-01-05 18:34 UTC
I use cmake and mingw64 gcc to try to compile fltk but it stops on ExternalCodeEditor_WIN32.cxx.
I use default cmake settings.

```
C:\CompilationStuff\fltk\fltk-1.3.5\fluid\ExternalCodeEditor_WIN32.cxx: In member function 'void ExternalCodeEditor::close_editor()':
C:\CompilationStuff\fltk\fltk-1.3.5\fluid\ExternalCodeEditor_WIN32.cxx:141:13: error: narrowing conversion of '-1' from 'int' to 'long unsigned int' [-Wnarrowing
]
  141 |       case -1:  // error
      |             ^
C:\CompilationStuff\fltk\fltk-1.3.5\fluid\ExternalCodeEditor_WIN32.cxx: In member function 'int ExternalCodeEditor::open_editor(const char*, const char*)':
C:\CompilationStuff\fltk\fltk-1.3.5\fluid\ExternalCodeEditor_WIN32.cxx:512:15: error: narrowing conversion of '-1' from 'int' to 'long unsigned int' [-Wnarrowing
]
  512 |         case -1:        // wait failed
      |               ^
```

**Comment by erco77** [comment] 2021-01-05 19:08
This was fixed in 1.4.x where reap_editor()'s return value is an int instead of a DWORD. Some other changes to the function were made to support this, so it's not a simple one-line change.

However, I believe you can copy the fluid/ExternalCodeEditor_WIN32.{cxx,h} files from 1.4.x and drop them into 1.3.5/fluid to solve the problem.

I'll investigate backportting a fix to 1.3.x that is basically along those lines.

**Comment by KatPurpy** [comment] 2021-01-05 19:11
I get some other error instead if I copy ExternalCodeEditor_WIN32.cxx
C:\CompilationSTuff\fltk\fltk-1.3.5\fluid\ExternalCodeEditor_WIN32.cxx:11:10: fatal error: FL/fl_string.h: No such file or directory
   11 | #include <FL/fl_string.h> // fl_strdup()

**Comment by erco77** [comment] 2021-01-05 19:12
Ah, OK, I'll try to have a commit for 1.3.5 for you, if not today, tomorrow.

**Comment by KatPurpy** [comment] 2021-01-05 19:13
Thanks! I'll be waiting!

**Comment by erco77** [comment] 2021-01-05 19:20
Hmm, try pulling 1.3.x current -- it seems like this has already been fixed.

This issue seems to be a dupe of issue  #92.
If you can confirm that solves, I'll close this issue as a dupe.

**Comment by KatPurpy** [comment] 2021-01-05 19:22
oh pardon

**Comment by erco77** [comment] 2021-01-05 19:23
The current branch of 1.3.x has not been released yet.

**Comment by KatPurpy** [comment] 2021-01-05 19:35
Thanks now stuff seem to be working.

**Comment by erco77** [comment] 2021-01-05 19:42
Great -- thanks for the confirm.
Closing as a dupe of #92.

**Closed by erco77** 2021-01-05 19:42 UTC
Labels: duplicate

**Comment by KatPurpy** [comment] 2021-01-05 20:00
Just last thing please update archives on the official website or else there will be even more duplicate questions like this one, it doesn't seem like they were updated as the fix was released since ```19 Jun 2020``` but archives still have the bug

**Comment by erco77** [comment] 2021-01-05 20:14
Albrecht-S is handling FLTK release scheduling; he could respond with an ETA.

**Comment by Albrecht-S** [comment] 2021-01-05 23:15
@KatPurpy "archives" on the web site are only for officially released versions, hence we'll put a new tarball online once it's officially released.

Regarding release schedule: the plan is to release 1.3.6 ASAP. Given the things still to do this will probably not be before February (2021 ;-)), but I hope we can hold this schedule.

Just in case someone needs to pull the current development version w/o using git: it's always possible to download a zip file with the current version of any branch (i.e. branch-1.3 or master) from GitHub. For instance, select branch [`branch-1.3`](https://github.com/fltk/fltk/tree/branch-1.3), click on the green "Code" button and select [Download Zip](https://github.com/fltk/fltk/archive/branch-1.3.zip).
