### ISSUE TITLE
 SelectObject(gc, fid) failed when create Fl_GDI_Font_Descriptor, GetLastError return 87

### ISSUE THREAD

**Issue by mlip-m** [fltk/fltk#356] opened 2021-12-23 09:13 UTC
`Fl_GDI_Font_Descriptor::Fl_GDI_Font_Descriptor(const char* name, Fl_Fontsize fsize) : Fl_Font_Descriptor(name,fsize) {

  int weight = FW_NORMAL;

  int italic = 0;

  switch (*name++) {

  case 'I': italic = 1; break;

  case 'P': italic = 1;

  case 'B': weight = FW_BOLD; break;

  case ' ': break;

  default: name--;

  }

  fid = CreateFont(

    -fsize, // negative makes it use "char size"

    0,              // logical average character width

    fl_angle_*10,                   // angle of escapement

    fl_angle_*10,                   // base-line orientation angle

    weight,

    italic,

    FALSE,              // underline attribute flag

    FALSE,              // strikeout attribute flag

    DEFAULT_CHARSET,    // character set identifier

    OUT_DEFAULT_PRECIS, // output precision

    CLIP_DEFAULT_PRECIS,// clipping precision

    DEFAULT_QUALITY,    // output quality

    DEFAULT_PITCH,      // pitch and family

    name                // pointer to typeface name string

    );

  angle = fl_angle_;

  HDC gc = (HDC)fl_graphics_driver->gc();

  if (!gc) gc = fl_GetDC(0);

  SelectObject(gc, fid);    // set failed sometimes, GetLastError return 87

 GetTextMetrics(gc, &metr);

//  BOOL ret = GetCharWidthFloat(fl_gc, metr.tmFirstChar, metr.tmLastChar, font->width+metr.tmFirstChar);

// ...would be the right call, but is not implemented into Window95! (WinNT?)

  //GetCharWidth(fl_gc, 0, 255, width);

  int i;

  memset(width, 0, 64 * sizeof(int*));

#if HAVE_GL

  for (i = 0; i < 64; i++) glok[i] = 0;

#endif

  size = fsize;

}`

**Comment by Albrecht-S** [comment] 2021-12-23 12:21
Which FLTK version (please exact Git or snapshot version)?
ISTR that such an issue has been fixed recently, could you please try the current Git version?

When does the error appear?

**Comment by mlip-m** [comment] 2021-12-28 09:43
> Which FLTK version (please exact Git or snapshot version)? ISTR that such an issue has been fixed recently, could you please try the current Git version?
> 
> When does the error appear?

version is 1.4.0

I use follow code to calculate string pixel length, Sometimes there are mistakes when font is bold

`string src = "BLOCK_ADDD";
if(bBold)
{
    fl_font(FL_HELVETICA_BOLD,13);​
}
else
{
    fl_font(FL_HELVETICA,13);​
}
int wi = 0,hi=0;
fl_measure(src .c_str(),wi,hi,false);`

**Comment by Albrecht-S** [comment] 2021-12-28 11:54
@mlip-m Thanks for the feedback and the code.

> version is 1.4.0

Sorry, this is not enough. Please specify either the full snapshot version or the Git version (aka SHA1, see `git log -1`.

Your given code looks fine. Are you using fl_set_font() in your program before you're measuring strings like above, or are you using other fonts than `FL_HELVETICA` and `FL_HELVETICA_BOLD` as given in your code fragment?

And one more question: what does "Sometimes" mean in this context? Does it depend on the string you're measuring, does it happen after a long runtime of your program, or how can you describe it?

I'm guessing that the problem is within your code, and without seeing real code it's hard to find out what could cause this. The Microsoft error code is unfortunately not helpful, it can mean anything.

Can you please post a short test case, i.e. a full program we can build and use for testing? Otherwise I'm afraid we can't help.

**Comment by mlip-m** [comment] 2021-12-29 13:12
> @mlip-m Thanks for the feedback and the code.
> 
> > version is 1.4.0
> 
> Sorry, this is not enough. Please specify either the full snapshot version or the Git version (aka SHA1, see `git log -1`).
> 
> Your given code looks fine. Are you using `Fl::set_font()` in your program to assign a font before you're measuring strings like above, or are you using other fonts than `FL_HELVETICA` and `FL_HELVETICA_BOLD` as given in your code fragment?
> 
> What does "Sometimes" mean in this context? Does it depend on the string you're measuring, does it happen after a long runtime of your program, or how can you describe it better?
> 
> I'm guessing that the problem is within your code, and without seeing real code it's hard to find out what could cause this. The Microsoft error code is unfortunately not helpful, it can mean anything.
> 
> Can you please post a short test case, i.e. a full program we can build and use for testing? Otherwise I'm afraid we can't help.

I just use "fl_font()" and "fl_measure()" two functions as shown above. No other functions are used.

**Comment by Albrecht-S** [comment] 2021-12-29 16:33
Can you please answer my (other) questions? Without enough information we can neither rule out a bug in your program nor find a bug in the FLTK library (which I consider to have a very low probability).

I still have no idea when the error you're observing happens. "Sometimes" doesn't mean anything to me. Except maybe that your program overwrites some data and then experiences this issue.

If you don't provide more details I must assume that the error is in your program and close this issue.

**Comment by Albrecht-S** [comment] 2022-01-16 20:48
My questions have not been answered for more than two weeks and according to the FLTK CMP I'm closing this issue now. If you have a concrete example that fails or if you can provide the requested information, please ask further questions in fltk.general.

That said (standard reply):

This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.

Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Closed by Albrecht-S** 2022-01-16 20:48 UTC
Labels: question, wontfix, no user support
