### ISSUE TITLE
FLTK 1.4 Window Rescale incorrectly stretches widgets

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#917] opened 2024-02-21 14:39 UTC
**Describe the bug**
The new CMD+- and CMD+= shortcuts for scaling a window up or down on macOS doesn't always scale the window correctly. It seems very inconsistent and unpredictable. Issues appear to be most common if the application is launched and then the window is manually resized before pressing CMD+- or CMD+= for the first time, but the side effects of scaling the window are different every time.

**To Reproduce**
For now, I've only produced this in my own program: https://github.com/dannye/crystal-tracker/tree/fltk1.4

If I end up reproducing this in an FLTK test program, I will report back.

**Expected behavior**
The sizes and positions of widgets should be scaled uniformly when the window is scaled.

**Videos**

https://github.com/fltk/fltk/assets/5231310/b35e8e47-bcae-4486-8e4f-b66b184c059e

https://github.com/fltk/fltk/assets/5231310/711d7e8a-2915-494e-8c9f-8350e6ceec09

In the second video, pay special attention to the piano keys which become over-stretched, and how the notes and the vertical background grid lines stretch differently than each other. It's very important in this program that the sizes of the vertical grid lines and of the notes correspond to each other.

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 681e22a

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Please include all configure or CMake options and add all CMake options you changed
by using CMake GUI tools (if any).
 - `./autogen.sh --prefix="$(realpath "$PWD/../..")"`
 - `make`
 - `make install`

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: macOS
 - OS Version: macOS 11.4
 - Processor if relevant: Intel

**Comment by Albrecht-S** [comment] 2024-02-21 16:15
Please try to reproduce this either with one of our test/demo programs, or try to build your own small but complete (i.e. compilable and linkable) pure FLTK test program (preferably one source file, less than about 100 lines) so we can test and verify the issue. We can't investigate your entire program, just to find that something in your code causes the issue (if that's the case which I do not want to say).

... unless @ManoloFLTK has an idea what can cause this issue.

Note that it's a Known Issue that the window can be distorted if resizing it makes it larger than the screen limits in one or both directions, but this doesn't seem obvious in your test case (I only watched parts of the 2nd video).

**Comment by Albrecht-S** [comment] 2024-02-21 16:34
When looking at your 2nd video I see that some of your objects change their sizes relative to the window and to each other. FLTK's scaling mechanism would not do that. It changes an internal scaling factor and uses this for drawing the UI. It does **never** change internal widget coordinates and/or sizes.

The conclusion is that this can only be caused by your own source code. Please try to find out where your code interacts with widget sizes and positions for your own internal resizing mechanisms (which you have IIRC), and try to switch that off.

Note that repeated resize operations may be susceptible to accumulating rounding errors. Since FLTK does never change coordinates FLTK's rescaling is immune to such effects.

**Comment by Albrecht-S** [comment] 2024-02-21 19:22
Sorry, @dannye, it's useless to post more videos. I can't see what is expected behavior, and what not.

If you can't provide a minimal, pure FLTK example (and I mean, a really short example), then we can't work on this and must close this issue.

**Comment by dannye** [comment] 2024-02-21 19:27
I will make a minimal repro soon. In the meantime, I am raising it to your attention that the window scaling does not cooperate well with very valid FLTK 1.3 code, and "fixing" it seems very non-trivial.

**Comment by Albrecht-S** [comment] 2024-02-21 21:03
> I am raising it to your attention that the window scaling does not cooperate well with very valid FLTK 1.3 code, and "fixing" it seems very non-trivial.

OK, this is a valid point. IIRC you can switch FLTK's built-in scaling off if you have your own scaling mechanism. That would be the way to "fix" it if these two approaches interfere. I don't know off the top of my head how you can switch it off though, @ManoloFLTK would probably know or find it out quickly. If this fixed your problem, we could talk about how this (a) can be made easy and (b) can be documented (better) if it isn't.

**Comment by dannye** [comment] 2024-02-22 14:58
> Note that it's a Known Issue that the window can be distorted if resizing it makes it larger than the screen limits in one or both directions

Hm, IMHO this is really bad. Even if this were the only issue with window scaling, I would want to turn this feature off. I don't mean to be offensive, just honest. I wouldn't want to ship an application that ruins its own layout just because the user hit a "standard" keyboard shortcut. Especially because re-shrinking the window immediately after the layout has been messed up does not fix the layout (in my experience).

I obviously don't know the technical limitations that led to this known issue, but it seems important to me to fix it.

> Note that repeated resize operations may be susceptible to accumulating rounding errors. Since FLTK does never change coordinates FLTK's rescaling is immune to such effects.

Both my window resizing and my window zooming are also not susceptible to accumulated rounding errors, as they always make explicit calculations. That makes it especially interesting that there clearly are accumulated rounding errors when the macOS window scaling is combined with my window resizing. (Hypothesis below)

> IIRC you can switch FLTK's built-in scaling off if you have your own scaling mechanism. That would be the way to "fix" it if these two approaches interfere.

Just to be very clear (sorry for being a bit pedantic), it's not that the build-in scaling interferes with my own scaling mechanism -- my scaling mechanism was never invoked in the above attached videos except for at the 50 second mark in the second video to "fix" much of the broken layout.

The issue seems to be mostly that the built-in scaling interferes with my window's resize handler, which is not used at all for zooming in or out. It's used to change the widths/heights of only a few widgets in order to correctly take up the space in the new window size. Most importantly, the Fl_Scroll that occupies most of the window. This resize code doesn't even touch the piano keys or note boxes that become distorted, so it's still unclear to me how that is even happening (I will continue investigating).

My current hypothesis is that the Fl_Window::resize() is being called with the "true" desktop dimensions/position of the window, so when my Fl_Window uses this data to resize the few top-level widgets, it's all wrong. This wouldn't explain all the issues I'm seeing, but it would explain a lot.

If I'm correct, I think some reasonable possible fixes could be to either not call the Fl_Window's ::resize at all after a built-in window rescale, or to call it with the scaled width and height instead of the "true" width and height.

**Comment by Albrecht-S** [comment] 2024-02-22 17:04
> ... to call it with the scaled width and height instead of the "true" width and height.

You mention "true width and height" twice and OTOH "scaled width and height". What do you mean with this distinction? The latter sounds to me like what you seem to mean with the former. I'm not trying to nitpick, it's just meant to clarify so we don't talk about different things. Maybe what you call "**_scaled_** width and height" should better be called "**_unscaled_** width and height". Is this what you mean?

In FLTK speech there are "FLTK coordinates" or "FLTK units" which is what your program sees and uses in your code. One "pixel" in previous (1.3) documentation would be one "FLTK unit" in your program (code). In FLTK 1.3 this is obviously the same, but in FLTK 1.4 it's different. Aside from FLTK's scaling feature macOS Retina displays use four (2x2) "real" pixels for one "FLTK unit". All FLTK scaling is (and must be) hidden from the program, except for OpenGL, where we must discern this (w() as opposed to pixel_w() etc. IIRC). But you are not using OpenGL IIRC.

This makes it clear that Fl_Window::resize() **must** be called with "FLTK coordinates", not "real screen pixels" or "scaled coordinates", as I would call it (see above). Whether Fl_Window::resize() is being called for a pure zoom action should not matter. You get the old width w() and height h() and the new arguments (let's call them W and H, respectively). Note that Fl_Window::resize() can also be called if only the x() or y() positions are changed. Your own resize algorithm should probably do nothing if w() or h() don't change.

> My current hypothesis is that the Fl_Window::resize() is being called with the "true" desktop dimensions/position of the window ...

Please test this, add some `printf()` statements or whatever to verify this. If that would be the case, then this would be a bug, but I don't think so. At least if you mean the "scaled", or "physical" pixel coordinates here (which I assume). And, BTW, if this would be the case, then we should probably see this in all other test apps etc..

Looking forward to your test results, and - even much better - to a minimal example that exhibits the problem.

PS: please let's exclude the known issue mentioned above (the potential window size changes when the screen limits are crossed) for this issue. This would be another topic. Feel free to discuss this in fltk.development (not fltk.general) so we can get input from other devs. Thanks

**Comment by dannye** [comment] 2024-02-23 03:26
> You mention "true width and height" twice and OTOH "scaled width and height". What do you mean with this distinction? The latter sounds to me like what you seem to mean with the former. I'm not trying to nitpick, it's just meant to clarify so we don't talk about different things. Maybe what you call "**_scaled_** width and height" should better be called "**_unscaled_** width and height". Is this what you mean?

Yes, you're right. By "true" I meant the "real" dimensions that the OS sees, and by "scaled" I meant the "virtual" dimensions that my application sees, but I agree with you that it's best to call those the "unscaled" dimensions. (I was thinking "scaled" from the perspective of the OS window dimensions, but that's unhelpful and confusing.)

---

Here is a minimal repro of the issue. I do not know if it's the only issue, but I do believe that it is the largest issue:

**The macOS window scaling does not work correctly for Fl_Groups with a `resizable_` of `NULL`.**

Code:

```cpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Spinner.H>

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(600, 100);
    w = o; (void)w;
    { Fl_Group* o = new Fl_Group(10, 10, 580, 80);
      { Fl_Spinner* o = new Fl_Spinner(100, 20, 40, 30, "Spinner 1");
        (void)o;
      }
      { Fl_Spinner* o = new Fl_Spinner(220, 20, 40, 30, "Spinner 2");
        (void)o;
      }
      { Fl_Spinner* o = new Fl_Spinner(340, 20, 40, 30, "Spinner 3");
        (void)o;
      }
      { Fl_Spinner* o = new Fl_Spinner(460, 20, 40, 30, "Spinner 4");
        (void)o;
      }
      o->box(FL_ENGRAVED_BOX);
      o->resizable(NULL);
      o->end();
    }
    o->resizable(o);
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
```

Video:

https://github.com/fltk/fltk/assets/5231310/df43ff5c-943c-4343-81e5-fd9802c549e9

Note that rescaling repeatedly back to back always produces the same result, but manually resizing the window followed by rescaling has unpredictable effects on widgets whose positions and sizes should not change at all.

**Comment by dannye** [comment] 2024-02-23 04:10
This bug is also witnessable in the test program **test/clipboard.cxx**.

And this may or may not be the same issue, but the macOS window scaling also causes bugs with **test/tile.cxx**:

https://github.com/fltk/fltk/assets/5231310/8e1cab8d-ee1d-4686-ac44-60b273371d7f

**Comment by Albrecht-S** [comment] 2024-02-23 13:42
@dannye Thank you for the minimal reproducer and for insisting on your points. I can confirm the issue with your minimal reproducer and with test/clipboard.cxx (tested on Linux). This doesn't seem to be macOS specific. I'm going to investigate...

I can't reproduce the issue of Fl_Tile on Linux and Windows though, but I see it on macOS. It looks like a similar issue that got fixed a long time ago but I can reproduce it on macOS with current Git (a6dc84ac833a8d4). This Fl_Tile issue seems to have to do with subwindows whose handling **is** platform dependent.

**Comment by dannye** [comment] 2024-02-23 14:04
> This doesn't seem to be macOS specific.

Oh interesting. I've always been referring to this as the "macOS window scaling" because I naively assumed it was an FLTK feature only available on Mac because of the high DPI Retina display or whatever. It makes sense that it's available on all platforms though, and that's exciting.

I never noticed that the keyboard shortcut Ctrl+= also works on Windows or Linux because my application has its own shortcut in the menu bar for Ctrl+=, and commit 681e22a did not work as intended. So on Mac, the FLTK CMD+= still has priority over my app's CMD+= despite the intentions of that commit.

Now that I know the window scaling works on all platforms, I really could get rid of my own zoom function and replace it with FLTK's. But (and sorry this is slightly off topic from the issue), can FLTK's zoom-in/zoom-out be triggered arbitrarily by my application code? I would like to keep my application's toolbar buttons for zooming, but make them trigger the FLTK zoom upon mouse-click. Thanks.

**Comment by dannye** [comment] 2024-02-23 14:11
I also apologize and take back what I said [here](https://github.com/fltk/fltk/issues/917#issuecomment-1959628971) about the known issue. The "damage" done to the window layout no longer appears permanent after the bugfix. When the window exceeds the screen size, the aspect ratio is changed and some widgets are not resized exactly right. But as soon as the window is re-shrunk and manually resized, the correct layout is fully restored, which is certainly acceptable.

**Comment by Albrecht-S** [comment] 2024-02-23 14:38
@dannye I was curious and investigated how this resizing bug could have happened. So far I could find out that the bug was introduced by a commit in **July 2017**, more than 6 years ago: 225c3d6da316838aba9432a319bbdd33da97a001. Wow, that's really a long time for a bug that hasn't been found meanwhile. Great that you found it and that you also found a fix (even if the real fix will likely be different, but the gist is the same). I'll keep you updated.

**Comment by Albrecht-S** [comment] 2024-02-23 18:38
Commit f288aea10a5691f7fbf12609e22e07b10581fdce should fix the rescaling issue for groups w/o resizable() widget. The demo program works as expected, and test/clipboard works fine for me now.

@dannye Please confirm that it fixes your program as well.

This commit also fixes parts of the issue reported for test/tile.cxx. This is definitely another issue and will be targeted separately.

**Comment by dannye** [comment] 2024-02-23 19:06
It works great, thank you. This issue can be closed from my point of view.

Would you like me to submit an issue for the subwindow bug or do you have that handled?

**Comment by Albrecht-S** [comment] 2024-02-23 19:30
@dannye Thanks for confirmation.

> Would you like me to submit an issue for the subwindow bug or do you have that handled?

I'll see if I can find a solution (quickly), or I'll open an issue for this. Thanks.

**Closed by Albrecht-S** 2024-02-23 19:30 UTC
Labels: bug, fixed
