### ISSUE TITLE
macOS installs fluid in sudo Application directory instead of CMAKE_INSTALL_PREFIX/bin

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#482] opened 2022-08-16 00:25 UTC
The current head of fltk1.4 on macOS installs fluid on the application directory instead of the ${CMAKE_INSTALL_PREFIX}/bin.  This is different from Linux or Windows where CMAKE_INSTALL_PREFIX is respected.  
This is a problem when using ExternalProject_Add() to automate builds as the Application directory needs sudo permissions to install.
For more reference on the issue (as some sample ExternalProject_Add code), see:
https://groups.google.com/g/fltkcoredev/c/tYhruYzyu88/m/GlHTBkvABgAJ

**Comment by Albrecht-S** [comment] 2022-08-16 11:20
@ggarra13 Thanks for filing the bug report. I added it to the FLTK 1.4 milestone.

**Comment by Albrecht-S** [comment] 2022-08-16 11:26
See commit 14ae784f7fe08b8c051e2109a8325b671a8e1b23 which introduced this bug in an attempt to improve installation of fluid (confirmed in above mentioned fltk.coredev thread).

**Comment by MatthiasWM** [comment] 2023-01-05 14:22
I assigned myself as well because I may be the one to blame.

**Comment by ManoloFLTK** [comment] 2024-02-16 08:39
@MatthiasWM ,@albrecht-S I would believe this is now fixed, so this issue can be closed.

**Comment by MatthiasWM** [comment] 2024-02-16 11:03
@ManoloFLTK Yes, thank you. I kept this open to remind me to check if this changed in @Albrecht-S 's version. Yes, it is fixed.

**Closed by MatthiasWM** 2024-02-16 11:03 UTC
Labels: bug, CMake, Platform: macOS, Prio 3 - Moderate
