### ISSUE TITLE
[BUG] test/tree: hangs and crashes on wayland

### ISSUE THREAD

**Issue by ngortheone** [fltk/fltk#617] opened 2022-12-30 06:52 UTC
OS: FreeBSD 14
Wayland: sway 1.7

Pressing "Select All" in `test/tree` hangs the application, spikes CPU usage to a 100% (or close), the window stops reacting to mouse clicks or any other input, then the window disappears, application crashes shortly after with this message

`Fatal error while communicating with the Wayland server: Broken pipe`

**Comment by ngortheone** [comment] 2022-12-30 06:53
[recording(1).webm](https://user-images.githubusercontent.com/18271144/210042890-94405d89-fa2b-4b6a-a9ec-9af48b3369f5.webm)

a video that demonstrates the bug

**Comment by ManoloFLTK** [comment] 2022-12-30 07:32
I will close this because that is a duplicate of issue #300 which is currently under consideration.

**Closed by ManoloFLTK** 2022-12-30 07:32 UTC
Labels: duplicate

**Comment by erco77** [comment] 2022-12-30 07:41
Yes -- dupe of issue #300 and related issue #596.

Problem is the use of Fl_Simple_Terminal which currently uses Fl_Text_Editor as the base class to handle output. Turns out a fix to Fl_Text_Editor made is very slow when lots of data is sent to it, as Fl_Simple_Terminal does, and as the test/tree exacerbates.

I'm actually actively working on a [rewrite of the terminal widget ](https://github.com/erco77/fltk/issues/1) in my fork to solve this, by implementing a full terminal widget. Should be a better fit for Fl_Simple_Terminal than abusing Fl_Text_Editor as the base class. The newer widget will support things like background colors, attributes like underline, bold, dim, and improved ANSI/XTERM escape code support. I've been keeping that fork issue up to date with daily progress. Hope to have something in the next few weeks to apply to FLTK master.
