### ISSUE TITLE
Lots of LNK errors of MSVC when building. (fltk is installed by Conan)

### ISSUE THREAD

**Issue by hwhsu1231** [fltk/fltk#446] opened 2022-05-22 05:50 UTC
This issue is related to that: https://github.com/conan-io/conan-center-index/issues/10852

After I build the project, lots of LNK errors show up:

- LNK2001
- LNK2005
- LNK2019
- LNK4099

What might be the reason of that? How to solve it?

**Comment by MoAlyousef** [comment] 2022-05-23 20:38
There seems to be work to fix the build issue on conan’s side.

**Comment by Albrecht-S** [comment] 2022-05-24 11:46
@hwhsu1231 Some points to notice:

1. For the time being building stock FLTK 1.4 **shared** libraries with `CMake` and `MSVC` doesn't work yet. Please use an option to build static FLTK libraries instead. Building shared libs with MSVC is work in progress and will be fixed before the release of FLTK 1.4.0.

2. Many of the linker errors may be caused by missing FLTK and other libraries in your linker command. You should link with `fltk.lib` but also - if required - `fltk_images.lib` and `fltk_gl.lib`. There may be more required libraries though, for instance some for OpenGL, GLU, etc. (dependent on which FLTK libs you need and your application).

3. Some of the error / warning messages referred to above seem to be Chinese or Korean or any other eastern language I don't understand. You'd need to translate these messages to English for more help.

4. We can't help building software with conan.

That said, if you need help building your software please see below...

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by MatthiasWM** [comment] 2022-11-23 10:51
Can we close this?

**Comment by MatthiasWM** [comment] 2022-11-23 10:51
Ah, never mind. No reply since May. Closed.

**Closed by MatthiasWM** 2022-11-23 10:51 UTC
