### ISSUE TITLE
Cairo and new ABI

### ISSUE THREAD

**Issue by bikepunkmaggie** [fltk/fltk#350] opened 2021-12-19 20:37 UTC
I built and installed on my Linux machine today (been about 3 days since I done a build).  All went well with the build.  Went to work on my project using FLTK and it bombed on build stating Fl_Cairo.H cannot find cairo.h (line 33 of Fl_Cairo.H).

On my machine, cairo.h is in /usr/include/cairo.  To make work real quick, I just updated Fl_Cairo.H to have the include as  # include <cairo/cairo.h>.

My cmake options:
CXX=clang++ CC=clang  cmake \
-D CMAKE_BUILD_TYPE=Debug \
-D FLTK_BUILD_EXAMPLES=ON \
-D OPTION_CAIRO=ON  \
-D OPTION_USE_PANGO=ON  \
-D OPTION_INCLUDE_DRIVER_DOCUMENTATION=ON   \
-D OPTION_INSTALL_HTML_DOCUMENTATION=ON \
-G Ninja ..

My project cmake (hasn't changed in a while):
find_package(FLTK REQUIRED NO_MODULE)

add_executable(foo ....)

target_link_libraries(foo PRIVATE fltk fltk_images)

I am running Fedora 35 and KDE Plasma 5.23, with an aging Celeron that loves FLTK.

**Comment by Albrecht-S** [comment] 2021-12-19 20:46
Did you update FLTK from git and/or which commit are you (now) using?
If not from Git, which snapshot or where did you download FLTK from?
How did you build FLTK itself (configure/make or CMake)?
I assume CMake.

And what do you mean with "new ABI"?

Whatever the answers are, please try to update FLTK to the latest Git version and run a complete fresh build.

If you built FLTK with configure/make: please execute
```
make distclean
autoconf
./configure (your options here...)
```

**Comment by Albrecht-S** [comment] 2021-12-19 20:52
Another question: does the FLTK demo program test/cairo.cxx work? Does it display the Cairo image as shown in the documentation?
Link: https://fltk.gitlab.io/fltk/cairo_test.png

**Comment by bikepunkmaggie** [comment] 2021-12-19 21:28
I was updating using git (just a git pull).  As for the name, I just used ABI as that was in the commit message.  I build fltk with Cmake with Ninja.  The demo worked, it was the first program I ran when I could not compile my code.

I did attempt to remove the fltk source dir I was using, did a new clone and build (latest  commit https://github.com/fltk/fltk/commit/47164bf9541486f3fd7b32c361f1784f4745c2c3); however, I still get the same error and the demo works.

**Comment by Albrecht-S** [comment] 2021-12-19 22:25
Thanks for your feedback. (FYI: It's not a new ABI, it's just another filename.)

The statement `#include <cairo.h>` has been introduced in 2016 and never changed since. The [official Cairo FAQ](https://www.cairographics.org/FAQ/#minimal_C_program) also uses `#include <cairo.h>`.

Hmm, I don't know what happened. It looks like something in your build must have changed. Your CMake info posted above looks correct. Can you please try to regenerate your own project from scratch? I just want to rule out that something in your project has been affected by a change in FLTK or something like that.

Last questions for now: how do you search for Cairo in your project? Do you at all? On my system cairo.h is also `/usr/include/cairo/cairo.h` and I `pkg-config` prints
```
$ pkg-config --cflags cairo
-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16
```
which includes `-I/usr/include/cairo` which should then be able to resolve the statement `#include <cairo.h>` to find the header file.

Can you please check the commandline of your build?

**Comment by bikepunkmaggie** [comment] 2021-12-20 16:00
I spent a little more time on this--a big note is that I am not using any of the Cairo functions in my programs as of yet.  Perhaps why no issues came up before.  Sorry, should have started off with that tidbit.

Note that if I use fltk-config to build, all works fine on my program.

To fix (besides going back to a previous commit), I added the library in my CMake file: 
`target_include_directories(foo PUBLIC /usr/include/cairo)`

Maybe it is a RTFM, but I did not do this before.  I assume I will have to add same for the libs once I start using Cairo in FLTK.

As for my pkg-config:
```
pkg-config --cflags cairo
-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/libxml2 -pthread 
```

**Comment by Albrecht-S** [comment] 2021-12-20 18:38
OK, thanks for the feedback, it's very much appreciated.

Our CMake support is not yet perfect (not even complete) and I'm trying to improve it continuously. I still don't know why you may have encountered the reported regression but I found out that our CMake build did not export the required include directories if FLTK was built with Cairo support.

I added this in commit b91db00d9. Can you please test again w/o setting the Cairo include directories explicitly and report if this commit fixes it for you? TIA.

FTR: I built my own Cairo test project using FLTK's cairo_test.cxx from Git current and the following CMakeLists.txt worked for me after the fix (before this commit I had to add the include dirs as well):
```CMake
cmake_minimum_required (VERSION 3.2)

project (CairoTest)

# Find FLTK (replace with your own path as needed)
set (FLTK_DIR "/path-to/fltk/build"
  CACHE FILEPATH "FLTK installation or build folder"
)
find_package (FLTK REQUIRED NO_MODULE)

# Define the executable GUI ("WIN32") program to be built
add_executable (cairo_test WIN32 /git/fltk/master/test/cairo_test.cxx)

# Set build properties
target_include_directories (cairo_test PRIVATE ${FLTK_INCLUDE_DIRS})

# Libraries we need to link
target_link_libraries (cairo_test fltk fltk_cairo)
```

**Note:** the extra library `fltk_cairo` will probably be removed before FLTK 1.4.0 will be released.

**Comment by bikepunkmaggie** [comment] 2021-12-20 21:10
Confirmed (once I remember` target_include_directories (foo PRIVATE ${FLTK_INCLUDE_DIRS})`).

Thanks!

**Comment by Albrecht-S** [comment] 2021-12-21 00:07
> Confirmed once I remember target_include_directories (foo PRIVATE ${FLTK_INCLUDE_DIRS})).

Thanks for confirmation. I'd like to get rid of this too, see #207.

**Closed by Albrecht-S** 2021-12-21 00:07 UTC
Labels: bug, fixed, CMake, waiting for confirmation
