### ISSUE TITLE
Fl_Choice mess up the menu location when there are many menu items

### ISSUE THREAD

**Issue by etorth** [fltk/fltk#476] opened 2022-08-08 19:38 UTC
I don't know if you guys notice this, when Fl_Choice has many items, it start to mess up the menu location.
Following as example

![image](https://user-images.githubusercontent.com/1754214/183507543-894720a1-db54-43df-8838-75168c002572.png)

Reproduce is by:

put Fl_Choice in a Fl_Group
put a lot of menu items in FL_Choice, I here put 40, I also tried 20, also can reproduce.

Seems this is an old bug, someone metioned here:, 1.4 still reproduces, 1.3.8 also has this issue.

https://fltk.easysw.narkive.com/m7JJGL1t/1-1-5rc2-bug-fl-choice-menu-position-changes

I am using WSL, os is ubuntu20.8

**Comment by Albrecht-S** [comment] 2022-08-09 11:16
@etorth Thank you for reporting this, but please don't report the same issue twice. It is generally preferred to report different issues in different GitHub issues, but this one is very closely related to issue #465:

This is a duplicate of https://github.com/fltk/fltk/issues/465#issuecomment-1208528941, a comment to another issue. Although we could keep both issues open I decided to close this one and keep the other because a potential solution would (should) fix both issues if possible.

Thank you, closing this issue now.

**Comment by Albrecht-S** [comment] 2023-01-04 20:09
Sorry for the noise, closing this issue and reopening it again. After reading back and forth the two issues #465 and this one (#476) I decided that we need two separate issues. The first post of @etorth to issue #465 should be ignored and we should investigate the "menu location" issue here.

@etorth That said, can you please provide a short but complete source file (not longer than about 100 lines) that we can use to reproduce and investigate this issue? This would be very helpful.

Please note that it **might** be possible that the issue is caused by your environment (WSL). I don't say that this is the case, but it's possible. Can you maybe try to reproduce the issue directly on Windows or in a full Linux environment? What happens in these environments?

Note also that there is a "Huge" menu in `test/menubar.cxx` and we don't know of any issues with this "Huge" menu. Can you please try this demo in your WSL environment? Unfortunately I don't have WSL installed and can't test this. TIA.

**Comment by ManoloFLTK** [comment] 2023-01-15 04:58
I've modified test/menubar to make it use a very large Fl_Choice. It's enough to change line #245 of test/menubar.cxx from
```
ch.menu(pulldown);
```
to
```
ch.menu(hugemenu);
```
The modified program runs OK on X11, Windows, Wayland and macOS.
This would suggest the issue is caused by WSL.

**Comment by Albrecht-S** [comment] 2023-01-15 13:12
@ManoloFLTK Thanks for testing. If you like, please take over this issue (assign to yourself, remove my assignment) and close it if we can't find a solution - or if the OP confirms that the issue is only on WSL.

@etorth Please test on other platforms, as Manolo suggested. If you can't test your program on another platform (Windows or a real Linux system), please try at least test/menubar and report what you see. If we don't get a sufficient answer to these questions this issue must be closed within a week or two. Thanks.

**Comment by Albrecht-S** [comment] 2023-04-11 17:28
Closing this issue as announced on Jan 15.

**Closed by Albrecht-S** 2023-04-11 17:28 UTC
Labels: wontfix
