### ISSUE TITLE
Fl_Choice has too many options, how to add scroll bar

### ISSUE THREAD

**Issue by chengpengvb** [fltk/fltk#465] opened 2022-07-13 07:43 UTC
I added more than 150 options to Fl_Choice, the drop down is too long, can you add a scroll bar, does anyone have the same problem as me?
![image](https://user-images.githubusercontent.com/28288567/178679003-1d5c3c79-8ece-499c-8a38-630a73c038c0.png)

**Comment by erco77** [comment] 2022-07-13 17:12
If you move the mouse to the bottom of the screen in the menu, it auto-scrolls downward.

Indeed it'd be nice to either:

    a) Have a scrollbar
    - or -
    b) A visual indication at the top/bottom when the list is larger than the screen (an arrow maybe)
        to give the user a visual cue for the currently implemented auto-scroll behavior
        
Some would argue it's bad to make a chooser list that large, and have the app break the list up into submenus, such as by categories, or if the content is not fixed (e.g. from a database), break it up into submenus by first letter.

So instead of:

```
     alpha
     alfred
     aldus
     amount
     :
     azure
     barry
     beta
     bill
     :

```
..using submenus instead:

```
     A -> alpha
          alfred
          aldus
          :

     B -> barry
          beta
          bill
          :
```

**Comment by erco77** [comment] 2022-07-13 17:13
Oh crap, sorry, I didn't mean to close that.. reopening

**Comment by chengpengvb** [comment] 2022-07-15 03:05
✌️

**Comment by etorth** [comment] 2022-08-08 19:35
I don't know if you guys notice this, when Fl_Choice has many items, it start to mess up the menu location.
Following as example

![image](https://user-images.githubusercontent.com/1754214/183499385-371b9f38-796b-4a96-8f4a-a81af7dda47f.png)

Reproduce is by:
1. put Fl_Choice in a Fl_Group
2. put a lot of menu items in FL_Choice, I here put 500

Looks this is an old bug, someone metioned here:, 1.4 still reproduces, 1.3.8 also has this issue.

https://fltk.easysw.narkive.com/m7JJGL1t/1-1-5rc2-bug-fl-choice-menu-position-changes

**Comment by etorth** [comment] 2022-08-08 19:36
I am in WSL envrionment, using Ubunt20.8

**Comment by Albrecht-S** [comment] 2023-01-04 20:14
@etorth I hid your two comments in this issue because they were about another issue and duplicates of your newer issue #476.
Please follow-up in issue #476 which should be used to track the menu positioning issue mentioned by you. Thank you.

**_This issue_** is about adding a scrollbar or some other means to large menus of `Fl_Choice` widgets and should be reserved to this topic.

**Comment by ManoloFLTK** [comment] 2023-11-01 09:55
This issue is part of a new issue #768. It will be handled there. Closing here.

**Closed by ManoloFLTK** 2023-11-01 09:55 UTC
Labels: duplicate
