### ISSUE TITLE
Fl_Text_Editor fails when it removes key bindings (cur->next)

### ISSUE THREAD

**Issue by MariwanJ** [fltk/fltk#158] opened 2020-11-17 06:58 UTC
This peace of code is not correct. If cur->next is invalid the code will fail. you have to check if the object is valid before you try to get the next item. 

/**  Removes all of the key bindings associated with the text editor or list.*/
void Fl_Text_Editor::remove_all_key_bindings(Key_Binding** list) {
  Key_Binding *cur, *next;
  for (cur = *list; cur; cur = next) {
    next = cur->next;
    delete cur;
  }
  *list = 0;
}

Version : FLTK nightly released (\version 1.3.4 ABI feature)

**Comment by MariwanJ** [comment] 2020-11-17 07:18
Naturally, this shouldn't happen. I don't know how I get this error. I checked the cur->next .. sometimes is NULL other times points to invalid memory. 
Maybe when Fl_Group remove widgets in wrong order could cause this issue as Fl_Group remove the widget having the keybinding before NULL pointer .. which results in a bad memory location. 
Do Fl_Group put NULL at the location after removing it?

**Comment by Albrecht-S** [comment] 2020-11-17 11:34
Hi @MariwanJ, can you tell us more about **when** this happens to you?
- Is it with one of the included test and demo programs or is it with one of your own apps?
- Does it happen while the program is running or at exit?
- If it happens while the program is running, do you delete / recreate Fl_Text_Editor widgets?

Also, I suspect your FLTK version (above) is not correct. There's no "FLTK nightly released" version. Is your version from Git (that should be the master branch, i.e. 1.4.x) or is it one of our weekly "snapshots" (should be 1.4 as well). Hence `version 1.3.4 ABI feature` doesn't seem to make sense. Can you please clarify?

**Comment by Albrecht-S** [comment] 2020-11-17 11:43
@MariwanJ  Regarding your 2nd comment: unfortunately there's no way to determine if a given key binding is "_valid_" or "_in valid memory_". We must rely on the first key binding given and the entire list of key bindings to be valid (up to `next == NULL`).

When a widget is deleted it is removed from its parent group (if any). The Fl_Group (or any other parent derived from Fl_Group) then removes the widget from the list of children, hence there's no longe any reference to the removed widget. The memory owned by the widget is returned to the system w/o actually clearing it (intentionally!), i.e. if your code or any other part of the program code had a reference (pointer) to the deleted widget, accessing that memory would likely cause trouble.

**Comment by Albrecht-S** [comment] 2020-11-17 11:46
Note: this issue **might be related** to issue #89, at least if it happens at program exit.

**Comment by MariwanJ** [comment] 2020-11-18 09:35
Sorry for late answer. 
Yes it is the snapshots and the mentioned version is from the source code. So how can I know which version it was? File name is as bellow 
fltk-1.4.x-20201113-a4bacf83.tar.bz2
Ok. What happens is I have a customized FL_Text_Editor (cursor blinks) that the object is created, deleted, recreated during the process. 
When I load a text file to the buffer, and then when I close that file (I delete the old Fl_Text_Editor object) and re-create it.. This causes different problems sometimes. 
One problem was what I mentioned, the other is a "heap corruption" when I delete the old object. 
I create the new object and link it to the parent window and then I remove the old object (in a saved pointer) .. but still I get the heap corruption some times (not always). I don't understand why?  and if I just retry the running it works ... or if I debug the assembler code it works!
At the moment I don't get the mentioned problem but the heap corruption happens from time to time.

**Comment by MariwanJ** [comment] 2020-11-18 09:43
You might be right .. It could be the same issue as you mentioned. The solution might be to avoid deleting recreating the fl_text_editor object or the buffer.

**Comment by Albrecht-S** [comment] 2020-11-18 18:45
@MariwanJ, thanks for your explanation. Unfortunately I can't reproduce the issue here with FLTK 1.4 (current Git version). I used a test program that switches Fl_Text_Editor buffers like that posted by @erco77 in issue #89, modified to delete and recreate the `Fl_Text_Editor` widget (as you described), but everything I tried seemed to work flawlessly. I also used valgrind to check for memory and double delete issues but this didn't reveal anything - as long as my demo program was correct WRT creating and deleting widgets.

The issue in #89 is probably not related because it's something that has to do with static variables and their destructors which is not the case in your program AFAICT from your description.

Can you please try to create a demo program that does what you are doing and that shows the effects you experience? Often the issue lies in details like using local (stack) variables for widgets so they go out of scope earlier than expected, not creating them with operator new, stale or overwritten pointers or similar.

> how can I know which version it was? File name is ... fltk-1.4.x-20201113-a4bacf83.tar.bz2

The filename contains several portions: date = `2020-11-13` and Git revision `a4bacf83` which specify an exact version (the date is not even needed, the git rev. is sufficient).

**Comment by MariwanJ** [comment] 2020-11-19 06:45
My project is huge. Unfortunately I cannot remove dependencies I have from one widget to another. In short it is an IDE editor for a special Operating system I made for NUCLEO boards (interpreter). It gives suggestion words, code-completion, syntax highlighting  ..much more.
Unfortunately, it is for my job and cannot share the code. I tried to separate the text editor- widget ..but it was depending on many other things that make it impossible to separate it from the whole project.
I try each time I add code to check it with cppcheck .. I cannot find any significant problem so. 
Anyway If I figure out the problem I will share the solution with you. Thanks for your help.

**Comment by MariwanJ** [comment] 2020-11-19 13:00
Really strange, just retrying running the deletion of the old object in debug mode passes the error.. So, it seems that it needs more time before being able to delete the object? maybe this object 
Fl::add_timeout(REPEAT, blinkCursor, this);

Might be the operation "this" as the object is not static? I don't know

**Comment by Albrecht-S** [comment] 2020-11-20 17:45
@MariwanJ It is often the case that code with bugs like overwritten variables, pointers and such behaves differently if you rebuild it with even minor changes or with/without debug mode. This is very likely due to a changed memory layout so different vars/pointers get overwritten. It is even possible that a different order of actions/events causes different appearance of bugs. Tools like cppcheck can only find some kinds of programming errors but they can never confirm that the program code is error-free.

I'm not saying that it's sure that **your code** is buggy but I tend to assume that your program failures are not caused by FLTK. If you can't show us more code then I don't think that we can help you. Sorry.

That said, I believe that we should close this issue because this is no longer considered an issue of the FLTK library itself but it's more likely a user support question. However, the standard reply to those questions follows:

> This is the wrong place to ask questions about building or running programs built with FLTK (user support). Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

I'm not (yet) closing this issue but if you agree I'm asking you to close it yourself and (maybe) go to our fltk.general user group to ask further questions. TIA.

**Comment by Albrecht-S** [comment] 2020-11-20 17:53
> maybe this object Fl::add_timeout(REPEAT, blinkCursor, this); ...

I don't find the string "blinkCursor" in the FLTK code so I have to assume this is in your own code. If the usage of `this` is a problem depends on your code. But if you delete the editor widget in your code and there are outstanding timer callbacks that would access the deleted object then this is calling for trouble. You have to make sure that any outstanding time callbacks are cancelled before the `Fl_Text_Editor` object is deleted. Maybe you should look closer into this. It's only a guess but as you say it happens "sometimes" that's a hint that it could be related to a timer callback. Maybe. HTH

**Comment by MariwanJ** [comment] 2020-11-23 05:40
Difficult to know what exactly cause this problem. I close it now ..

**Closed** 2020-11-23 05:39 UTC
Labels: question
