### ISSUE TITLE
Tooltip causing Window to "unfocus" on Windows

### ISSUE THREAD

**Issue by wyhinton** [fltk/fltk#261] opened 2021-07-20 16:59 UTC
Moving https://github.com/fltk-rs/fltk-rs/issues/797 to here. 

Looks like the Tooltip widget is causing the app window to unfocus.

```C
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Pack.H>

int main() {
  Fl_Window win(400, 300, "Window");
  Fl_Pack pack(160, 20, 80, 300);
  pack.spacing(5);
  for (int i = 0; i < 5; i++) {
    auto btn = new Fl_Button(0, 0, 0, 40, "Button");
    btn->tooltip("Button");
  }
  pack.end();
  win.end();
  win.show();
  win.redraw();
  return Fl::run();
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)
project(monitors)

include(FetchContent)

set(FLTK_BUILD_TEST OFF CACHE BOOL " " FORCE)
set(OPTION_USE_GDIPLUS ON CACHE BOOL " " FORCE)

FetchContent_Declare(FLTK
    GIT_REPOSITORY https://github.com/fltk/fltk
    GIT_SHALLOW TRUE
)
FetchContent_MakeAvailable(FLTK)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE fltk gdiplus)
target_include_directories(main PRIVATE ${fltk_SOURCE_DIR} ${fltk_BINARY_DIR})
target_link_libraries(main PRIVATE fltk)

```
build.bat
```
cmake -S. -Bbin -DCMAKE_BUILD_TYPE=Release && cmake --build bin --config Release
```
![image](https://user-images.githubusercontent.com/38958118/126079933-e1733040-b1c4-4d24-8b78-01d5f2f5c704.gif)

**Comment by Albrecht-S** [comment] 2021-07-21 09:51
@wyhinton Thanks for the report. I'm not sure if this can be changed though.

FTR: @MoAlyousef wrote in https://github.com/fltk-rs/fltk-rs/issues/797#issuecomment-882117871
> I was looking at the fltk source code and it seems to be related to this line:
https://github.com/fltk/fltk/blob/41b1f1f91197b40b243b6a0b38cc36ff3bc824fe/src/Fl_Tooltip.cxx#L304

Thanks for looking into it.

**Comment by wyhinton** [comment] 2021-07-26 14:52
> I'm not sure if this can be changed though.

By this do you mean that this kind of "unfocusing" in the toolbar is something that can not be changed on Windows?

**Comment by Albrecht-S** [comment] 2021-07-26 18:53
I don't know. Fact is that the tooltip is a window and that "switching" windows is likely to "unfocus" one window because the other window gets the focus. I have no idea what exactly is happening and if any Windows properties can be changed (in FLTK code) to suppress this or ... whatever. I don't know, and that's all I wanted to say. This needs investigation.

Of course, patches and pull requests would be appreciated.

**Comment by wyhinton** [comment] 2021-07-27 20:47
I'm guessing what's going has something to do with the tooltip being "outside of" the window. Putting a window inside of a window does not cause a new window to show up in the taskbar, or cause the unfocusing effect.

Simple example in rust:
```rust 
fn main(){
    let app = App::default();
    let mut win = Window::new(200, 200, 500, 300, "Event Trickle");
    let win2 = Window::new(100,50, 200, 200, "WINDOW IN WINDOW");
    let mut button= Button::new(0,0,250,200,"button in window 2");
    button.set_color(Color::Red);
    win2.end();
    win.end();
    win.show();
    app.run().unwrap();
}
```
I think for a design perspective however, this "window in a window" approach might not be great because our tooltip will be clipped off at the boundaries of the parent window.

**Comment by erco77** [comment] 2021-08-27 23:23
Looks good to me!
- Tooltips no longer flash the title bar
- Tooltip timeouts seem to work (~10 secs)
- Doesn'taffect keyboard focus when tips appear/disappear, etc.

**Comment by Albrecht-S** [comment] 2021-08-28 09:17
@erco77 Thanks, Greg, for testing and feedback. I'll wait for confirmation from the OP @wyhinton and/or @MoAlyousef (the fltk-rs maintainer) and close this issue then.

This commit should also fix fltk-rs/fltk-rs#797 once it is applied to fltk-rs.

**Comment by Albrecht-S** [comment] 2021-08-28 09:19
> Are we still interested in reporting compiler warnings? I've got 93 warnings in VS 2017 from the 1.4.x current.

Our CI build logs show lots of these warnings (go to the FLTK GitHub page, click on `Actions` and follow the links to the latest builds, e.g. [this one](https://github.com/fltk/fltk/runs/3445464056)). There's no need to report any warnings we can see in these build logs. See also #109.

**Comment by MoAlyousef** [comment] 2021-08-28 10:24
Thank you. I pulled latest master and built on my Windows 10 machine, using both msvc and mingw and I can confirm it's fixed. Same with the Rust bindings.

**Comment by Albrecht-S** [comment] 2021-08-28 10:48
@MoAlyousef Thanks for confirmation, closing this issue now.

**Closed by Albrecht-S** 2021-08-28 10:48 UTC
Labels: bug, fixed, Platform: Windows
