### ISSUE TITLE
The subwindow change in FLTK has brought a number of redraw issues

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1003] opened 2024-07-02 00:23 UTC
**Describe the bug**
There a number of redraw issues under Wayland when OpenGL subwindows are used inside Fl_Tile/Fl_Flex.

**To Reproduce**

[wayland_bugs.zip](https://github.com/user-attachments/files/16060085/wayland_bugs.zip)

This .zip contains a simple main.cpp file that mimics the layout of my program.  It also contains a README.txt file describing all the bugs that show up under Wayland with latest NVidia drivers at least.  Some redraw issues (like dragging of Fl_Tile) show in XWayland too.  Only X11 works perfectly.

**Expected behavior**
No redraw issues.  It should work like X11.

**Screenshots**

**FLTK Version**
 - Version: 1.4.0 master
 
**FLTK Configure / Build Options**
Default cmake options.

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Ubuntu 24.04.4 LTS

**Linux/Unix Runtime, if applicable:**
 - Wayland
 - XWayland

**Comment by ManoloFLTK** [comment] 2024-07-02 15:12
There's a major problem in the way you resize your main window to adapt it to the screen it's mapped on. Your timeout function computes what should be the window height to fill the screen based on Fl::screen_work_area(), and then you call Fl_Window::resize() with the computed height, and the program assumes your main window will accept this height, in the sense that the content of the main window is based on this height.
But Wayland doesn't work like that, because it hides the position of the window on the screen. It doesn't give you the work area size, just the display size, so that the height the program asks is too big. What happens is that after your timeout, your size computations and your resize calls have returned, when your program is in its event loop, Wayland calls your main window's resize() again with the max possible height given the screen and the menu bar at the screen top. Your program then redraws the main window but not correctly because some values depend on the previous height computations done by the timeout function that are no longer valid.

The layout of your window must be completely determined by its size and its resizing rules, and must be applied when your main window's resize function runs and only then. Your timeout function can compute a putative window height, and then call resize() with that height, but it MUST NOT assume that this height will be obeyed. When Wayland, later, in the program's event loop, calls the main window's resize function again, that window's content should adapt to the new height transmitted as a parameter of this call, and no computation done in the timeout function must have any effect on the new window layout.

With such an approach that can be applied to Wayland but also to any other platform, your main window will be correctly resized to fill the available display space.

**Comment by ggarra13** [comment] 2024-07-02 21:31
> There's a major problem in the way you resize your main window to adapt it to the screen it's mapped on. Your timeout function computes what should be the window height to fill the screen based on Fl::screen_work_area(), and then you call Fl_Window::resize() with the computed height, and the program assumes your main window will accept this height, in the sense that the content of the main window is based on this height. 

Correct.  I am using this approach on Windows, X11 and macOS with no issues.

> But Wayland doesn't work like that, because it hides the position of the window on the screen. It doesn't give you the work area size, just the display size, so that the height the program asks is too big. What happens is that after your timeout, your size computations and your resize calls have returned, when your program is in its event loop, Wayland calls your main window's resize() again with the max possible height given the screen and the menu bar at the screen top. 

Okay.  I did not follow you here.  Why does Wayland call resize again in the main loop?  And why would it call it with other values exceeding the screen work area if my timeout resize did not exceed those values?

> Your program then redraws the main window but not correctly because some values depend on the previous height computations done by the timeout function that are no longer valid.
> 

This is indeed what partially happens.  Some parts of the screen redraw with old values.

The timeout function, as currently written, should calculate a full work area screen as the "renderSize" image is too big for the monitor.   I don't understand what's the difference between what you call the "display" area.

> The layout of your window must be completely determined by its size and its resizing rules, and must be applied when your main window's resize function runs and only then. Your timeout function can compute a putative window height, and then call resize() with that height, but it MUST NOT assume that this height will be obeyed. When Wayland, later, in the program's event loop, calls the main window's resize function again, that window's content should adapt to the new height transmitted as a parameter of this call, and no computation done in the timeout function must have any effect on the new window layout.
> 

I don't know the size of the window until the video is opened and read.  That's why I need to resize the window on a timeout.   

The resize timeout both resizes and *repositions* the window to be at 0,0 if it too big.  I understand the repositioning might not be honored by Wayland.

The window does resize properly and does not exceed the desktop area (screen work area).  It is the other opengl subwindow (the timeline at the bottom) that does not resize correctly, which I don't resize manually (I expect it to have Wayland resize it for me).

> With such an approach that can be applied to Wayland but also to any other platform, your main window will be correctly resized to fill the available display space.

This approach works fine on all platforms but Wayland.  Find attached a new main.cpp screen that resizes the window barely and that still exhibits the redraw issues.

[main.cpp.txt](https://github.com/user-attachments/files/16074398/main.cpp.txt)

You suggested a new approach.  Can you modify main.cpp to explain what you mean?

**Comment by ManoloFLTK** [comment] 2024-07-03 13:32
I'm working to fix remaining problems to resize and move subwindows and hope to get that sorted out.

**Comment by ManoloFLTK** [comment] 2024-07-03 15:59
I find here (Ubuntu 24.04 in VM) all these issues fixed with the commit mentioned above.

**Comment by ggarra13** [comment] 2024-07-03 18:55
My ISP is down for todas.  I'll try it tomorrow.

**Comment by ggarra13** [comment] 2024-07-04 17:37
> I find here (Ubuntu 24.04 in VM) all these issues fixed with the commit mentioned above.

I confirm all the bugs are fixed under Ubuntu 24.04.4 LTS with NVidia drivers.  Great work Manolo and sorry for having you work so hard!

**Comment by ggarra13** [comment] 2024-07-04 17:51
Actually, I spoke too soon as I was incorrrectly testing on X11.  There's a problem (at least with NVidia drivers), when dragging the Fl_Tile separator (red bar - uiTimelineGroup).  It sometimes shrinks the blue bar (which should remain a constant size) and sometimes it leaks the red color of the uiTimelineGroup at the bottom.  Attached movie showing problems:

[Wayland_blue_bar_shrink.webm](https://github.com/fltk/fltk/assets/6072843/b69f2dba-3fb6-4953-8758-96df8572329f)

**Comment by ggarra13** [comment] 2024-07-04 18:03
Also, clicking on the Edit button leads to this unpredictable behavior on Ubuntu 24.04.4 LTS with NVidia drivers:

[Wayland_Edit_button.webm](https://github.com/fltk/fltk/assets/6072843/aae54be1-0523-451a-b738-ecf2526a0160)

**Comment by ManoloFLTK** [comment] 2024-07-04 18:18
> There's a problem (at least with NVidia drivers), when dragging the Fl_Tile separator (red bar - uiTimelineGroup). It sometimes shrinks the blue bar (which should remain a constant size) and sometimes it leaks the red color of the uiTimelineGroup at the bottom.

I see this here too, only transiently, while resizing operations are being performed. The posted video also shows only transient changes of the blue bar. That's not a bug in my view and I won't try to change that.

**Comment by ManoloFLTK** [comment] 2024-07-04 18:23
> Also, clicking on the Edit button leads to this unpredictable behavior on Ubuntu 24.04.4 LTS with NVidia drivers:

What is the meaning of "unpredictable" here?

What I see on the posted video doesn't occur here. I can't take care of that, which may be an NVidia driver problem, without reproducing it.

Could you try with the Mesa GL driver?

**Comment by ggarra13** [comment] 2024-07-04 21:56
> What is the meaning of "unpredictable" here?
> 

The gl window is sometimes drawn outside (below) the main window.

> What I see on the posted video doesn't occur here. I can't take care of that, which may be an NVidia driver problem, without reproducing it.
> 
> Could you try with the Mesa GL driver?

I tried it with the nouveau driver and it indeed does not happen.  It is indeed an nvidia driver issue.

**Comment by ggarra13** [comment] 2024-07-05 00:18
> I see this here too, only transiently, while resizing operations are being performed. The posted video also shows only transient changes of the blue bar. That's not a bug in my view and I won't try to change that.

Actually, it is not just transient.  If I drag the bar really fast to the bottom, the blue bar disappears.

**Comment by ManoloFLTK** [comment] 2024-07-12 15:57
@ggarra13 Could you, please, try with branch **wayland** of my FLTK fork at
https://github.com/ManoloFLTK/fltk ? I would believe these problems are fixed.

**Comment by ManoloFLTK** [comment] 2024-07-12 19:37
>  The Fl_Tile now has transient redraw issues with the blue bar and the red group below it. Once the dragging is done, the blue bar seems to restore itself to the actual shape, unlike before. 

Another thing that was not correct before was the fit of the window to the screen at startup that produced an incorrect layout of GL subwindows. Is that fixed now?

I consider a resize operation to be correct if it produces the expected layout at its end, independently of what happens transiently while the resize progresses. If no unexpected, stable layout occurs, I would think this issue is fixed.

**Comment by ggarra13** [comment] 2024-07-12 21:05
> Another thing that was not correct before was the fit of the window to the screen at startup that produced an incorrect layout of GL subwindows. Is that fixed now?

With NVidia, it is broken.  With nouveau it works correctly.

**Comment by ManoloFLTK** [comment] 2024-07-13 07:00
Is there any remaining, non-transient issue with the nouveau driver ?

**Comment by polter-rnd** [comment] 2024-07-13 11:49
> @ggarra13 Could you, please, try with branch **wayland** of my FLTK fork at https://github.com/ManoloFLTK/fltk ? I would believe these problems are fixed.

I have tried this on Intel with 2k display, and can notice very significant rendering slowdown in comparison with current master branch.

First I'm launching original version, and then Manolo's fix:

https://github.com/user-attachments/assets/c85bf73b-db86-445c-899f-05a213659b9c

**Comment by ManoloFLTK** [comment] 2024-07-13 15:18
@polter-rnd Your video doesn't leave the window untouched for 3 seconds until a timeout fits it to the screen size. Therefore the bug the new code fixes isn't visible in the video. The new code also takes care of problems when moving a child window to support "window docking" under Wayland. The program used in the video doesn't test for these issues. The slowed down window resizing is the cost to pay for these fixes.

@ggarra13 Is there any remaining, non-transient issue with the nouveau driver ?

**Comment by ggarra13** [comment] 2024-07-13 15:21
> @ggarra13 Is there any remaining, non-transient issue with the nouveau driver ?

Not that I can see.

**Comment by ManoloFLTK** [comment] 2024-07-13 19:36
>  > @ggarra13 Is there any remaining, non-transient issue with the nouveau driver ?

> Not that I can see.

Then, you may consider to close the issue.

**Closed** 2024-07-13 19:39 UTC
