### ISSUE TITLE
Regression: CMake error when generating a VS project with default settings

### ISSUE THREAD

**Issue by CyprinusCarpio** [fltk/fltk#1001] opened 2024-07-01 15:51 UTC
**Describe the bug**
CMake errors during generation of a VS 2022 project with default settings since a6651e10f. The error pertains to the GLU include directory, which is not found. Using CMake gui, the problem can be circumvented by setting the variable `OPENGL_GLU_INCLUDE_DIR` to empty, and clicking Generate again, which yields a fully functional FLTK project, GLU and all. CMake log attached.
[cmake log.txt](https://github.com/user-attachments/files/16056034/cmake.log.txt)

**To Reproduce**
1. Clone the repo and checkout a6651e10f
2. Using CMake GUI, try configuring and generating a VS 2022 project.
3. Observe that the error goes away once `OPENGL_GLU_INCLUDE_DIR` is set to empty, and the library can be fully built without problems
4. Likewise, checkout 5de880a and observe that there is no error to begin with.

**Expected behavior**
No error.

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - Branch master
 - Commit a6651e10f

**FLTK Configure / Build Options**
Default

**Operating System / Platform:**
 - OS: Windows 10

**Comment by Albrecht-S** [comment] 2024-07-01 16:25
Thanks for the report, I'll check it...

**Comment by Albrecht-S** [comment] 2024-07-01 17:13
Checked with
- Windows 10
- VS 2019
- CMake 3.29.2
- Git commit 1c6a0c1a8fb254945179276ecbd359cc1926fbb1 from Jun 29, 2024 (because that was a commit I had checked out on my VM).

I can't confirm the issue, the build works w/o issues, and `glpuzzle` and `fractals` work as expected.
Result of CMake (in cache):
`OPENGL_GLU_INCLUDE_DIR:PATH=OPENGL_GLU_INCLUDE_DIR-NOTFOUND`.

We need more info:

- Did you make sure that the cache was clear(ed)? If not, please try again in a fresh build folder.
- What is the contents of `OPENGL_GLU_INCLUDE_DIR` before you set it "to empty"?
- Which CMake version?
- Please post full CMake errors if the issue remains.
- Please let us know **exactly** how you run CMake (particularly if you use the included version of VS 2022)

**Comment by Albrecht-S** [comment] 2024-07-01 17:31
Sorry, I missed that you had included the CMake log.
There is an obvious error:
```
CMake Error in src/CMakeLists.txt:
  Target "fltk_gl" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "C:/Programowanie/fltk-glu/src/OPENGL_GLU_INCLUDE_DIR-NOTFOUND"

  which is prefixed in the source directory.
```

Investigating further. I don't know why this doesn't happen in my build but I believe I can fix it if necessary.

**Comment by Albrecht-S** [comment] 2024-07-01 17:55
> ... I believe I can fix it if necessary.

Unfortunately I can't. The only way to set this wrong `INTERFACE_INCLUDE_DIRECTORIES` property is, AFAICT, one of these statements:
```
src/CMakeLists.txt:852:  if(OPENGL_GLU_INCLUDE_DIR)
src/CMakeLists.txt:853:    target_include_directories(fltk_gl PUBLIC ${OPENGL_GLU_INCLUDE_DIR})
src/CMakeLists.txt-854-  endif()
--
src/CMakeLists.txt:915:    if(OPENGL_GLU_INCLUDE_DIR)
src/CMakeLists.txt:916:      target_include_directories(fltk_gl-shared PUBLIC ${OPENGL_GLU_INCLUDE_DIR})
src/CMakeLists.txt-917-    endif()
--
src/CMakeLists.txt:959:    if(OPENGL_GLU_INCLUDE_DIR)
src/CMakeLists.txt:960:      target_include_directories(fltk-shared PUBLIC ${OPENGL_GLU_INCLUDE_DIR})
src/CMakeLists.txt-961-    endif()
```

In all of these instances we use the condition `if(OPENGL_GLU_INCLUDE_DIR)` which should be `false` if the contents is `OPENGL_GLU_INCLUDE_DIR-NOTFOUND`.

If nothing helps, can you please check another `CMake` version? I noticed that you used `3.29.0-rc1` which may be buggy. I double checked with the latest commit from master and with CMake 3.20.6 which worked flawlessly.

Note: on Windows you can easily download different CMake versions and install them in different directories - which I am doing for such bug checks...

**Comment by CyprinusCarpio** [comment] 2024-07-01 18:31
I tried CMake 3.29.6 and the result is the same. But I think I know what's going on. I'm pretty sure you can reproduce this by clicking "Configure" twice, it will set the variable `OPENGL_GLU_INCLUDE_DIR`. Which will make those if statements you've pointed out evaluate true. I'm no CMake expert, but I thought that doing the "configure" step more than once (after changing some options for a "production" build for my purposes) isn't a problem and does not constitute a "dirty" cache, and it indeed wasn't until that "faulty" commit. So, partly my blame. But the good news is that it shouldn't be hard to fix, according to my understanding you'd only need to check for the `OPENGL_GLU_INCLUDE_DIR-NOTFOUND` value in the if statements. Correct me if I'm wrong.

**Comment by Albrecht-S** [comment] 2024-07-01 18:58
> ... it shouldn't be hard to fix, according to my understanding you'd only need to check for the OPENGL_GLU_INCLUDE_DIR-NOTFOUND value in the if statements. Correct me if I'm wrong.

Yep, I need to correct you. It's a CMake property that `something-NOTFOUND` evaluates to `false`.
https://cmake.org/cmake/help/latest/command/if.html#basic-expressions :
> False if the constant is 0, OFF, NO, FALSE, N, IGNORE, NOTFOUND, the empty string, or ends in the suffix -NOTFOUND. ...
>  if(\<variable>)
> True if given a variable that is defined to a value that is not a false constant. 

I also tried doing the configure step multiple times which didn't change my positive (i.e. working) result. Running the configure step multiple times should never change the result - theoretically.

I'm puzzled. We need to investigate further but I don't know where to start. I may think about it and ask you for some debug steps, probably tomorrow.

**Comment by CyprinusCarpio** [comment] 2024-07-01 20:51
#1002 removes the symptoms for me, now I can configure and reconfigure to no end. But why does `OPENGL_INCLUDE_DIRS` have this value is completely beyond me.

**Comment by Albrecht-S** [comment] 2024-07-02 16:20
@CyprinusCarpio I noticed your PR #1002 but I wonder too why and how it fixes the issue for you.

Thanks for the PR anyway, this added some more info to look for.

> Better yet, why did setting OPENGL_GLU_INCLUDE_DIR to "" removed the symptom too.

That's a good question. As long as we (i.e. I) don't know what's going on I can't accept your PR or commit something. I'm going to investigate the issue further...

**Comment by CyprinusCarpio** [comment] 2024-07-12 18:57
I did some digging on my own and I have some answers and a question:
> why does OPENGL_INCLUDE_DIRS have this value is completely beyond me.

The value of `OPENGL_GLU_INCLUDE_DIR` is appended to `OPENGL_INCLUDE_DIRS` at the line 755 in FindOpenGL.cmake, regardless of it's actual value (more on that in the question part of this comment).
I'm not sure of it, but this may mean that the explicit inclusion of the `OPENGL_GLU_INCLUDE_DIR` in `src/CMakeLists.txt` is redundand.
> Better yet, why did setting OPENGL_GLU_INCLUDE_DIR to "" removed the symptom too.

Because if `OPENGL_GLU_INCLUDE_DIR` is empty in the cache, there is nothing to append on the line 755 in FindOpenGL.cmake, thus `OPENGL_INCLUDE_DIRS` will not contain this value.

Now the question, which I'll do my best to answer too:
The appending to `OPENGL_INCLUDE_DIRS` is inside a if statement checking for `OPENGL_GLU_FOUND`. It evaluates true both on the first and subsequent configurations. On the first one, `OPENGL_GLU_INCLUDE_DIR` is empty. On subsequent ones, it contains the value `OPENGL_GLU_INCLUDE_DIR-NOTFOUND` but the if statement still evaluates true. Why that is? Why does it evaluate true in the first place if the value is empty?

`OPENGL_GLU_FOUND` is being set in the if statement at the line 528 in FindOpenGL.cmake:
```
if(OPENGL_glu_LIBRARY AND (WIN32 OR OPENGL_GLU_INCLUDE_DIR))
  set( OPENGL_GLU_FOUND "YES" )
else()
  set( OPENGL_GLU_FOUND "NO" )
endif()
```
Which means that on windows, the only thing that needs to be valid is `OPENGL_glu_LIBRARY`. And according to my understanding, it's just a normal variable that's being set to `glu32` at the line 227:
```set (OPENGL_glu_LIBRARY glu32 CACHE STRING "GLU library for win32")```
which means that it's always the same on Win32 (and not Borland compiler, but that's besides the point).

So, it's reasonable to expect that `OPENGL_INCLUDE_DIRS` will contain `OPENGL_GLU_INCLUDE_DIR-NOTFOUND` when GLU isn't found, and it's reasonable to check for this. 

Also BTW, I tried using the CMake from my VS installation, and the problem wasn't there. Perhaps it's because somehow this CMake instance can find GLU whereas the standalone can not. Normally I'm using standalone CMake because I also use gcc sometimes, and I like the gui.

**Comment by Albrecht-S** [comment] 2024-07-13 15:25
@CyprinusCarpio Awesome sleuthing!

I'm investigating...

**Comment by Albrecht-S** [comment] 2024-07-13 16:34
:-( Sigh, this is a bad coincidence of using the same (cache) variable name `OPENGL_GLU_INCLUDE_DIR` in our own (FLTK) CMake build files and in `FindOpenGL` - but only since CMake 3.29.0 (!):

1. The CMake cache variable `OPENGL_GLU_INCLUDE_DIR` was introduced in the `FindOpenGL` module that comes with **_CMake 3.29.0_**. Therefore CMake versions up to 3.28.x supposedly don't suffer from this issue.

2. FLTK used this variable much earlier, but FLTK executes first `find_package(OpenGL)` (in [CMake/options.cmake: line 653](https://github.com/fltk/fltk/blob/ee05d4bd3ac001e729786684e7e3f3a66684b3ee/CMake/options.cmake#L653)) and later `find_path(OPENGL_GLU_INCLUDE_DIR ...)` (in [CMake/options.cmake: line 684](https://github.com/fltk/fltk/blob/ee05d4bd3ac001e729786684e7e3f3a66684b3ee/CMake/options.cmake#L684)). The latter defines `OPENGL_GLU_INCLUDE_DIR` **after the first invocation** of `find_package(OpenGL)`.

3. Note that `FindOpenGL.cmake` does **_NOT_** define `OPENGL_GLU_INCLUDE_DIR` on Windows but doesn't "expect" it to be defined before `FindOpenGL.cmake` is executed.

4. This search order (see 2.) explains why the first configuration may succeed but subsequent configurations fail:
  - in the first configuration `OPENGL_GLU_INCLUDE_DIR` has not yet been defined by FLTK's search and `FindOpenGL` doesn't append the `-NOTFOUND` string.
  - in subsequent executions of `find_package(OpenGL)` our (FLTK's) search has defined `OPENGL_GLU_INCLUDE_DIR` in the cache (in a prior run) as `OPENGL_GLU_INCLUDE_DIR-NOTFOUND` and `FindOpenGL` appends this value to `OPENGL_INCLUDE_DIR` - even on Windows although it never defined it on this platform.

5. If one defines `OPENGL_GLU_INCLUDE_DIR` to the empty string (in the cache) our search is not executed anymore because the cache variable already exists and `FindOpenGL` appends the empty string which doesn't do any harm.

Oh well, that's really a bad accident. I'm now going to work on a proper solution. This might not be as easy as it looks at a first glance because FLTK must work with all CMake versions since 3.15 (our current minimum version) up to the latest version. The latest CMake version (3.29) adds more useful output variables but we can't rely on this because we can't assume that the user uses 3.29 or higher. This makes it difficult but I'm confident that I can find a working solution.

@CyprinusCarpio Thank you very, very much for finding the root cause of this issue. This saved me a lot of research, particularly because I couldn't reproduce the issue!

**Comment by CyprinusCarpio** [comment] 2024-07-13 19:54
Glad to be of help. So, #1002 can be binned?

**Comment by Albrecht-S** [comment] 2024-07-13 20:52
Yes, thanks for this hack anyway. I'll let you know when I got a - hopefully - better fix.

**Comment by Wakeelfahmed** [comment] 2024-07-22 16:05
> If nothing helps, can you please check another `CMake` version? I noticed that you used `3.29.0-rc1` which may be buggy. I double checked with the latest commit from master and with CMake 3.20.6 which worked flawlessly.

On your suggestion i gave CMake 3.20.6 a try but it does not contain VS 22 (i guess u missed that @CyprinusCarpio mentioned VS 22)
I myself trying to run FLTK on MS VS 22 (Wins 11) but facing issues. (I will update regarding my issues)

**Comment by Albrecht-S** [comment] 2024-07-22 17:59
@Wakeelfahmed Thanks for your help.

1. For the OP's problem there's at least the pragmatic solution to rename the CMake variable in question. This should work for all CMake versions and all CMake generators. I could commit this but I would like to find a better solution (but I'm busy with other stuff as well).

> I myself trying to run FLTK on MS VS 22 (Wins 11) but facing issues. (I will update regarding my issues)

2. If you have different issues than the OP with VS 2022 (and CMake) please open another GitHub issue. We really need **_one GitHub Issue per problem_** so we can test and document each problem and the solution separately.

3. However, if your problem is more like a question on how to build FLTK, then you'd better post in GitHub [Discussions in the "Q&A" category](https://github.com/fltk/fltk/discussions/categories/q-a).

 Thanks in advance.

**Comment by MatthiasWM** [comment] 2024-08-04 12:53
If it is enough to replce `OPENGL_GLU_INCLUDE_DIR` with `FL_ OPENGL_GLU_INCLUDE_DIR`, I am happy to do that and close the issue.

**Comment by CyprinusCarpio** [comment] 2024-08-05 12:41
> If it is enough to replce `OPENGL_GLU_INCLUDE_DIR` with `FL_OPENGL_GLU_INCLUDE_DIR`, I am happy to do that and close the issue.

I did that and the problem as reported is no longer present. But as a side effect, the value `FL_OPENGL_GLU_INCLUDE_DIR` now appears as ungrouped in the cmake gui, whereas before it was in the OPENGL category. I also don't know whether this would compromise what the faulty commit was trying to achieve.

**Comment by Albrecht-S** [comment] 2024-08-06 18:44
> If it is enough to replace `OPENGL_GLU_INCLUDE_DIR` with `FL_OPENGL_GLU_INCLUDE_DIR`, I am happy to do that and close the issue.

@MatthiasWM You could do me a favor and replace `OPENGL_GLU_INCLUDE_DIR` with `FLTK_OPENGL_GLU_INCLUDE_DIR` (note the prefix `FLTK_`, not `FL_`!) but please leave this issue open until I have more time to find a better solution - if possible. Please leave the issue assigned to me. All this CMake/OpenGL stuff needs more work but I'd appreciate if we had at least a workaround. TIA.

@CyprinusCarpio The "grouping" doesn't affect operation, it's just a user convenience, but thanks for mentioning it. But anyway, our CMake convention is to use the `FLTK_` prefix as mentioned above.

**Comment by Albrecht-S** [comment] 2024-08-08 09:36
I wrote:
> You could do me a favor and replace OPENGL_GLU_INCLUDE_DIR with FLTK_OPENGL_GLU_INCLUDE_DIR ...

@MatthiasWM No, **_please don't do this_**. I noticed that we should attempt to "repair" the CMake cache which we can do under certain circumstances but probably not always. This must be done in the first run with the changed variable name!

I'm going to check the details now and I'll commit my change soon (hopefully today).

**Comment by Albrecht-S** [comment] 2024-08-08 13:03
Commit e65681c9ac51dda850162a89397b3eec6ee8123a should fix the issue. This is an intermediate fix that avoids using a CMake variable with the prefix `OPENGL_` which must be considered _"reserved to FindOpenGL"_.

Since this issue appears in CMake 3.29 which introduces the cache variable `OPENGL_GLU_INCLUDE_DIR` and we can assume that many users will eventually upgrade to this or a higher version I added code to remove the old variable (used by FLTK before e65681c9ac51dda850162a89397b3eec6ee8123a) from the CMake cache if and only if we can be sure to remove "our" definition. Otherwise we abort the CMake configure step with a message that tells the user to rebuild in a clean directory. This should rarely happen.

FTR: Full error message if we can't remove the old cache variable:
```
FLTK configure: CMake cache inconsistency detected
CMake Error at CMake/resources.cmake:98 (message):
  Please rebuild FLTK in a clean CMake build directory
Call Stack (most recent call first):
  CMakeLists.txt:73 (include)
```

@CyprinusCarpio, @Wakeelfahmed, @Micha-2021: Please confirm that this commit fixes the issue for you. Thanks in advance.

**Comment by CyprinusCarpio** [comment] 2024-08-08 13:28
Can't seem to reproduce the issue after the patch. Thanks.

**Comment by Albrecht-S** [comment] 2024-08-08 14:59
@CyprinusCarpio Thanks for confirmation. Waiting for others...

**Comment by Albrecht-S** [comment] 2024-08-10 15:07
OK, I'm closing this issue now. If anybody still has issues with this, please drop a note and I will reopen it.

**Closed by Albrecht-S** 2024-08-10 15:07 UTC
Labels: bug, fixed, CMake
