### ISSUE TITLE
Fl_Check_Browser check marks off

### ISSUE THREAD

**Issue by darealshinji** [fltk/fltk#68] opened 2020-03-28 12:03 UTC
Sometimes some of the Fl_Check_Browser check marks are slightly "off". See screenshot.

![checklist](https://user-images.githubusercontent.com/5700937/77822589-81c93600-70f4-11ea-9d9e-3b93181811de.png)

**Comment by erco77** [comment] 2020-05-24 16:36
Hmm, can't replicate here -- probably need more info: FLTK version, operating system (platform/distro), code example demonstrating the problem. Curious if you changed the default Fl::scheme() or box settings on the widgets, as that might affect the problem.

I've attached my test code and a screenshot; fltk 1.4.x current on linux with default build flags.

If possible, change the attached code to show the problem, and include the above information.
![checks](https://user-images.githubusercontent.com/6484779/82759384-f68db900-9da1-11ea-929b-6d0bbc036de9.png)
[testcheck.zip](https://github.com/fltk/fltk/files/4673939/testcheck.zip)

**Comment by Albrecht-S** [comment] 2020-07-20 18:37
@darealshinji 
- Minor field width or height differences might be caused by rounding errors and show such effects
- We are unable to resolve this problem with the information provided
- Please provide more info as requested above
- Please close the issue if you're no longer interested in this issue
- Otherwise this issue will be closed w/o resolution

**Comment by darealshinji** [comment] 2020-07-21 15:03
I often use the Gtk+ scheme on FLTK apps, that might cause this?

**Comment by erco77** [comment] 2020-07-21 15:24
Something like that could I suppose.
Perhaps see if you can replicate the problem by modifying the check-browser program I attached earlier, and if so, attach a screenshot and the modified code. Hard to fix if we can't replicate, so trying to get a canned version of the problem is a good first step.
I did try modifying the check-browser program above to use the "gtk+" just now, but still couldn't replicate. e.g.
```
  int main() {
+      Fl::scheme("gtk+");
       Fl_Window *win = new Fl_Window(640, 480);

```

**Comment by wcout** [comment] 2020-08-05 06:40
What system are you on?

I have a Ubuntu 16.04 (virtual box) machine, where the DPI setting is slightly off 96dpi:

```
xrdb -query | grep dpi
Xft.dpi:	96.11328125
```

This makes FLTK use a screen scaling of 1.001180, which causes minor drawing anomalies e.g. with check boxes.

**Comment by Albrecht-S** [comment] 2020-08-05 09:45
@wcout Thanks for your comment. I was curious and experimented with odd screen scaling factors and I can see all kinds of drawing issues with check marks. IMHO we need to consider this _"normal"_ because it's impossible to do **exact** drawing with odd scaling factors.
This screenshot demonstrates how checkmarks can look with `FLTK_SCALING_FACTOR=1.142857142857` (8/7):

![issue-86_check-browser](https://user-images.githubusercontent.com/26235500/89397422-1d585c00-d710-11ea-9f67-54790e476b45.png)

The screenshot was scaled with Gimp by a factor of 2 in x and y to show the drawing diffs more clearly.

FWIW: I used the attached file [check-browser.cxx.txt](https://github.com/fltk/fltk/files/5027502/check-browser.cxx.txt) (a modified version of @erco77 's demo program) for this test. The screenshot was taken with scheme `gtk+` but I don't see essential differences with the standard scheme.

I suggest to close this issue with label `wontfix`.

**Comment by Albrecht-S** [comment] 2020-08-18 10:09
No replies since 13 days ... closing this now (won't fix).

**Comment by darealshinji** [comment] 2020-09-04 20:34
I'll try to replace it with some Unicode symbols: https://unicode-table.com/en/sets/check/

**Comment by Albrecht-S** [comment] 2020-09-05 10:42
Interesting idea. But there are some issues we'd need to consider:
- Unicode fonts are not always available.
- On X11 we'd likely need Pango to be able to render such "text".
- We'd need a build option or a working automatic fallback to "drawing" code.
- The check mark and the frame (box) can have different colors.

Question: how did you colorize the (red) check mark above, and which Unicode code points are your examples?

**Comment by darealshinji** [comment] 2020-09-06 10:10
I started using them on a program and so far it seems to work. The colored emoticon versions don't seem to be used.

``` C++
const char *u = "\u2610";  /* Ballot Box */
const char *c = "\u2611";  /* Ballot Box with Check */
//const char *c = "\u2612";  /* Ballot Box with X */

const char *u = "\u25CB";  /* White Circle */
const char *c = "\u25C9";  /* Fisheye */
//const char *c = "\u25CF";  /* Black Circle */

fl_font(FL_HELVETICA, tsize);
fl_draw(i->checked ? c : u, X, Y);
```

**Comment by Albrecht-S** [comment] 2020-09-06 10:57
Thanks for the additional info. It would IMHO be more consistent to render only the check mark '✓' itself ([U+2713: "check mark"](https://www.unicode.org/charts/PDF/U2700.pdf)) as a character since the box may be drawn in another color, for instance a black box (frame) with a green check mark.

Note: reopening this issue for further discussion...

**Comment by erco77** [comment] 2020-09-06 18:38
Hmm, sounds scary to use special unicode characters for the check, because what if the environment the application is running in doesn't have that Unicode font glyph available? (Think embedded devices here, which might have ASCII only) In such a case, the font renderer might render anything, and if that 'anything' in any way might confuse the end user into not knowing if a button is checked or not, this could lead to misrepresenting the on/off status, which depending on what the check button is controlling, such as motion control hardware, could be very bad.

Probably better we draw the check with lines to ensure the on/off status is represented correctly.

**Comment by darealshinji** [comment] 2020-09-19 16:20
One could also use NanoSVG (if enabled during build) to render checkboxes at different sizes. Just another idea.

**Comment by Albrecht-S** [comment] 2021-11-06 22:22
My solution of this issue: instead of drawing multiple lines we're now drawing a filled polygon. This is done in a new function `fl_draw_check()` that can and should be called by all widgets that need to draw check marks. I'm still testing but you can already see the result. Left hand side: old code, right hand side: new code. Top row 100 %, bottom row 133% scaling.

![issue-68-solved](https://user-images.githubusercontent.com/26235500/140625173-7064176c-b190-4560-af7e-8c546b21bb2e.png)

You may notice that I also introduced a minimum and a maximum check mark size for better user experience. Drawing over the box borders is **intentional** if the box is too small.

The fix is not only for Fl_Check_Browser but also for Fl_Check_Button. I still need to check if other widgets also need such fixes.

I'll commit my solution as soon as possible.

**Comment by Albrecht-S** [comment] 2021-11-06 23:47
I committed 12faae53fd3e009c to my fork in branch ['issue-68-browser-checkmarks'](https://github.com/Albrecht-S/fltk/tree/issue-68-browser-checkmarks) if anybody is interested to test.

The test program I used (slightly modified after taking the screenshots above) is [check-browser.cxx](https://github.com/fltk/fltk/files/7491402/check-browser.cxx.txt).

All feedback would be appreciated.

**Comment by erco77** [comment] 2021-11-07 01:35
Tested on my ubuntu 20.x machine. Looks good to me, here's my result:
![screenshot](https://user-images.githubusercontent.com/6484779/140628930-f7614c36-75f0-4fde-bd4d-7b43cc98d606.png)

**Comment by Albrecht-S** [comment] 2021-11-15 13:56
I committed my final solution. I changed all widgets I could find (`Fl_Check_Browser` and `Fl_Check_Button`) to use the new `fl_draw_check()` function. In a future version we might use anti-aliasing or - as suggested above - use nanosvg to draw even better check marks but that's out of the scope of this issue.

I'm closing this issue now.

**Closed by Albrecht-S** 2021-11-15 13:56 UTC
Labels: bug, fixed
